### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by serpentiem** [serpentiem/ddmk#1]
This post contains all currently planned features for each entry in no particular order. I will update it periodically to reflect what has been implemented.
# Devil May Cry 3
- ~~Allow adjusting the FOV.~~
- ~~Modify the RGB values of compatible moves.~~
- ~~Allow Air Hike regardless of selected melee weapon.~~
- ~~Introduce Arcade mode.~~
- ~~Artemis: Allow instant charging.~~
- ~~Artemis: Swap Normal shot and Multi-lock.~~
- ~~Introduce Boss Rush mode.~~
- ~~Allow adjusting mobility values like setting the number of Air Hikes and Trickster Dashes.~~
- ~~Introduce quality of life enhancements like certain perks available in the Easy Automatic mode.~~
- ~~Allow reasonable adjustment of the game's speed variables.~~
- ~~Introduce on demand style switching while in game.~~
- ~~Introduce on demand weapon switching for all of Dante's arsenal while in game.~~
- ~~Introduce training utilities like infinite hit and magic points, Crazy Combo buffer requirement adjustment, etc.~~
- ~~Allow adjustment of the magic point depletion rate and red orb reach.~~
- ~~Allow cosmetic-only adjustments like character model not changing when entering devil form and hiding certain weapons.~~
- ~~Allow inversion of camera axes.~~
- ~~Allow instant cutscene skipping.~~
- Introduce enemy wave editor.
- Introduce Lua script engine.
- ~~Introduce Quick Drive attack.~~
- ~~Allow swapping character models while in game.~~ **DISCONTINUED**
- ~~Introduce teleporter.~~
# Devil May Cry
- Allow usage of the Sparda Devil Trigger throughout the entire game.
- Allow selecting missions.
- Introduce Bloody Palace mode.
- Introduce Arcade mode.
- Allow switching melee and ranged weapons on demand while in game by using the d-pad or triggers.
- Allow usage of the Bangle of time without being equipped.
- Assign weapon attack to 'empty' B button.
- Make Nightmare-ß not drain magic points.
- Allow charging ranged weapons while attacking.
- Allow using ranged weapons without having to hold the Lock-on button.
- Allow hiding certain weapons like Ifrit.
- Only show weapons when they're equipped.
- Boost Force Edge by giving it access to some of Alastor's moves and Charged shot.
- Allow Force Edge to activate Sparda's devil form - also change Force Edge's model to Sparda and back depending on the devil state.
- Introduce playable Nero Angelo.
- Introduce Lock-on display.
- Allow devil form to show as long as devil mode is active instead of just when attacking with a melee weapon.
# Devil May Cry 4
- Introduce local multiplayer.
- Allow adjusting the speed and range of Vergil's Stinger attack.
- Introduce 'classic' teleports for Vergil.
- Allow hiding certain weapons like Gilgamesh and Beowulf.
- Introduce Lua script engine.
# Devil May Cry 2
- Allow all heart items to be usable at the same time.
- Replace Dante's moveset with Trish's or replace Trish's model with Dante's.
- Introduce starting missions with full magic points.
- Allow Dante to use special devil form at all times.
- Allow reasonable adjustment of the game's speed variables.
# All
- If the textures are natively available introduce the ability to change button prompt platform.
- Introduce variable editor.
- Allow mode adjustments.
- Introduce reset motion state mechanic.
- Introduce remappable hotkeys for certain options that can be executed or toggled.

**Comment by Jareson** [comment]
Question: Under All, you state "Allow Mode Adjustments". Does this include turbo mode being added for DMC2?

**Comment by serpentiem** [comment]
Merged into #233.
