### ISSUE TITLE
DDMK 2.5 - DMC4SE - Picking Vergil as P2-3 Crash

### ISSUE THREAD

**Issue by bjgent237** [serpentiem/ddmk#103]
For some reason, having Vergil set as P2 or 3 with multiplayer enabled causes the game to crash when the mission starts and you just get in-game. Tested on Bloody Palace.

[Kyrie](https://pastebin.com/YNZ69G9s) (P1 - Nero | P2 - Dante | P3 - Vergil)

**Comment by ngoduythien** [comment]
I had the same situation when I used the mod 2.5 version. P1 vergil, P2 dante, game crash in misson and bloody place. Thank serpentiem, yur mod is very great^^

**Comment by serpentiem** [comment]
Merging with #186.
