### ISSUE TITLE
Yamato X Rebellion Combat Mod

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#104]
I got reference from this site
https://xiaransbackyard.wordpress.com/2017/07/01/yamaxrebellion-mod/
i't show how about this mod 

Gameplay Mod Video 
https://www.youtube.com/watch?v=LU-LsOtZPm0 YamatoxRebellion
https://www.youtube.com/watch?v=OzuIFHbfg-o&feature=youtu.be YamatoxRebellion v3

Expanding yamato moveset with including original dante technique from lending rebellion animation & new yamato x rebellion combo may be good idea to dmc4se and probably dmc3se too

- [ ] Add Built in Yamato X Rebellion Combat Mod with DDMK

**Comment by serpentiem** [comment]
Sounds more like a job for the modding forums. Denied.
