### ISSUE TITLE
DMC3 Cutscene Skip freezes game on mission clear screen

### ISSUE THREAD

**Issue by maddszerotwo** [serpentiem/ddmk#106]
Just recently picked this up, and the cutscene skip seemed ideal until I found that it consistently froze the mission clear screen forcing me to restart the game every time I complete a mission. Didn't see any mention of this anywhere, but I'm pretty new to browsing github, so apologies if this has already been noted and addressed.

**Comment by serpentiem** [comment]
Should be fixed in the latest nightly.
