### ISSUE TITLE
the style rank  miss

### ISSUE THREAD

**Issue by sd23589** [serpentiem/ddmk#107]
i have use ddmk2.6beta2hotfix,than I find that if I use use Doppelganger ,I cant see the style rank  ,it only see when I choose the  force a single actor ~

**Comment by ymsx8535** [comment]
> 我已经使用了ddmk2.6beta2hotfix，比我发现如果我使用Doppelganger，我看不到样式等级，只有当我选择了一个演员时才看到〜

You can view https://github.com/serpentiem/ddmk/issues/95 This article

**Comment by ymsx8535** [comment]
> 我已经使用了ddmk2.6beta2hotfix，比我发现如果我使用Doppelganger，我看不到样式等级，只有当我选择了一个演员时才看到〜



> 我已经使用了ddmk2.6beta2hotfix，比我发现如果我使用Doppelganger，我看不到样式等级，只有当我选择了一个演员时才看到〜

In addition, after the style is enabled, clone will not be available.

**Comment by sd23589** [comment]
今天我在用ddmk2.6hotfix的时候，在用相机功能，live功能是正常的，但是当我在coifing功能里设置了过量的参数后，游戏就崩溃了，然后就再也打不开DMC3了，我重新下载了dmc3-0.nbz，但是不起作用，然后我重新装了GData.afs文件夹，但是也不工作，我可能要哭了！！！！！！！！

**Comment by ymsx8535** [comment]
> 今天我在用ddmk2.6hotfix的时候，在用相机功能，live功能是正常的，但是当我在coifing功能里设置了过量的参数后，游戏就崩溃了，然后就再也打不开DMC3了，我重新下载了dmc3-0.nbz，但是不起作用，然后我重新安装了GData.afs文件夹，但是也不工作，我可能要哭了！！！！！！！！

Don't worry，Have you backed up the game?，If not, you can restart the game，Then according to the author's instructions，Restart

**Comment by ymsx8535** [comment]
Or you can try to reinstall the plugin

**Comment by ymsx8535** [comment]
nbz Files are not required. After decompression, you can delete nbz or backup nbz.

**Comment by ymsx8535** [comment]
> 今天我在用ddmk2.6hotfix的时候，在用相机功能，live功能是正常的，但是当我在coifing功能里设置了过量的参数后，游戏就崩溃了，然后就再也打不开DMC3了，我重新下载了dmc3-0.nbz，但是不起作用，然后我重新安装了GData.afs文件夹，但是也不工作，我可能要哭了！！！！！！！！

CLEAN  "DMC3-0.NBZ" LINK:  https://drive.google.com/file/d/1y4IplqhWktzSHxSyvSoHFZD6GdUo6kDt/view

**Comment by ymsx8535** [comment]
https://github.com/serpentiem/ddmk/issues/108，Maybe you can refer to this article

**Comment by ymsx8535** [comment]
> 今天我在用ddmk2.6hotfix的时候，在用相机功能，live功能是正常的，但是当我在coifing功能里设置了过量的参数后，游戏就崩溃了，然后就再也打不开DMC3了，我重新下载了dmc3-0.nbz，但是不起作用，然后我重新安装了GData.afs文件夹，但是也不工作，我可能要哭了！！！！！！！！

Maybe you can refer to this articlehttps://github.com/serpentiem/ddmk/issues/108

**Comment by sd23589** [comment]
> > 今天我在用ddmk2.6hotfix的时候，在用相机功能，live功能是正常的，但是当我在coifing功能里设置了过量的参数后，游戏就崩溃了，然后就再也打不开DMC3了，我重新下载了dmc3-0.nbz，但是不起作用，然后我重新安装了GData.afs文件夹，但是也不工作，我可能要哭了！！！！！！！！
> 
> 也许您可以参考这篇文章https://github.com/ [/ issues / 108](https://github.com/serpentiem/ddmk/issues/108)

Thank you. I solved my problem. My game is a steam version. Without dmc3-0.nbz, I can't enter DM3. I can only stay in the dmclancher interface. I downloaded the entire dmc3 folder again, and then reinstalled 2.6hotfix to solve this problem

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
