### ISSUE TITLE
DMC3 doesn't open when dinput8.dll is on the root folder

### ISSUE THREAD

**Issue by anominu** [serpentiem/ddmk#108]
After installing DDMK the game stopped launching, also when i remove dinput8.dll the game launches like normal but the mod doesn't work

**Comment by ymsx8535** [comment]
> 安装DDMK之后，游戏停止启动，同样，当我删除dinput8.dll时，游戏也像正常一样启动，但mod无法正常工作

Forgive me English badly you can try upgrading the game

**Comment by anominu** [comment]
what do you mean by upgrading your game? if you mean updating, it is updated to the latest version on steam

**Comment by serpentiem** [comment]
Please upload your log files and share the link.

**Comment by lalmans** [comment]
i am having the same issue if i delete mary.dll it works but cant use menu

**Comment by lalmans** [comment]
[Mary.txt](https://github.com/serpentiem/ddmk/files/4399372/Mary.txt)

**Comment by LuR3n** [comment]
Been having the same issue. Any way to fix it yet?

**Comment by vatrys** [comment]
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5487763/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/5487764/Mary.txt)
Fresh install, none of the games run if dinput8.dll is in the collection root folder, and if deleted, DDMK doesn't work

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
