### ISSUE TITLE
DMC4SE Multiplayer bugs/crashes

### ISSUE THREAD

**Issue by TheRipper9O** [serpentiem/ddmk#109]
-Vergil as Players 2-4 causes the mission to crash.
-Nero using snatch as players 2-4 while player 1 isn't Nero causes a crash.
-When Player 1 is Nero, if players 2-4 use snatch they go to the center of the screen.
-idk if its just a game bug, but Sometimes while playing as vergil, the battle never ends, even after all enemies are killed.
-Only one lady can grapple at a time, or it breaks for the other Lady player.

**Comment by serpentiem** [comment]
Merging with #186.
