### ISSUE TITLE
Advanced Reset Motion State

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#111]
well,Reset Motion State feature is great for ddmk.but it's still lack from copy paste middle & latter(final) for transition motion state i've tried this feature on game and it's feel uncomplete.because this only allow reset beggining motion state and use it for multiple times. i know this feature can't allow player use for middle & latter(final) transition motion.if you like add some feature to fully copy / partial copy motion state (at beggining  / middle / in between middle - final / latter(final) ) by create custom button "hold button to record transition motion state from ... to .." and another button to release recorded transition motion state for multiple times or anything else similiar like this it's might make this feature more perfect.it may increase playability and also applied for all dmc 1- 4.
Example = use and release transition motion state from middle / latter (crazy combos) then use it multiple time's and more.

**Comment by serpentiem** [comment]
Denied.
