### ISSUE TITLE
Is it possible to turn off the camera collision? Or reduce the camera collision radius?

### ISSUE THREAD

**Issue by zhm86** [serpentiem/ddmk#112]
Your work is amazing. I'd like to ask you for advice about the camera of DMC3.
I am trying to fix the annoying camera of DMC3.
As we know, every scene\area\room in the game is labeled "stxxx.pac" in the game files (They can be found by unpacking GData.pak).
For example, in the the second scene of Mission 3, which is named "Bull's Eye Bar", is labeled "st003" in the game file.
In Bull's Eye Bar, the camera changes suddenly as you move around, which makes people feels pretty bad.
I did some research, the data that defines\controls camera is located in the stxxxcfg.pac. For "Bull's Eye Bar", it is st003cfg.pac.
Open st003cfg.pac with Winhex, the camera data is located between the code "CAM" and "EVE". I can roughly see the camera data structure, but I can't figure it out what they mean. They seem to be matrixes.
So I replace every byte of the camera data(between "CAM" and "EVE") with "00". I erase the camera code from all the stxxxcfg.pac files.
Then I launch the game. All the camera of all mission do not change suddenly any more, they all behave like what they do in Mission 1 and Mission 2.
That is to say, the camera always follows the player, and you can adjust the camera with your right trigger of controller. This is exactly what I want.
However, I came across a problem in the third scene of Mission 4, which is "st102". When the player go to the above platform, the camera will not follow him.
If the player go further on the platform, we can not even see him. As far as I can see, the camera get stuck on the stairs.
So here comes the question: 1. How can I turn off the camera collision? 2. Is it possible to reduce the camera collision radius? 3. Do you know the meaning of camera data?
Thanks.

**Comment by serpentiem** [comment]
> 1. How can I turn off the camera collision?

Of course, by default, you can't. You'd have to find out how the collision works.

I'd first search for the camera position vectors to get some basic understanding of how it works. Then I'd search for state changes at the moment of collision. In theory you only need two vectors, but camera events in games usually emit more data. Once you have the states, you can check what accesses them and modify that as you see fit.

> 2. Is it possible to reduce the camera collision radius?

Probably. Should just be a float value.

> 3. Do you know the meaning of camera data?

No, haven't looked at it yet.

**Comment by zhm86** [comment]
Thank for your reply. I am not capable of dealing with it on my own, I have got a lot of things to learn.
By the way, I found the address of FOV based on your address. You may add it in your next release if it is necessary.
![fov](https://user-images.githubusercontent.com/16450203/77822165-35e5b380-712b-11ea-9724-b2e79299a17c.png)
I tried IDAPro, I think the function sub_140247E80 and sub_140247AD0 have something to do the camera collision. If you are interested in it, could you please take a look at it when you have free time? I would like to donate if you have a BTC address.

**Comment by serpentiem** [comment]
At this point I'm not interested in turning off the camera collision.
