### ISSUE TITLE
Can't open include file when trying to compile in Visual Studio

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#114]
Hello serpentiem

i was to wanted take a look and trying compile this project,i clonned the project and opened the "ddmk.sln" with Visual Studio and hit "Build Solution"

> 1>------ Build started: Project: Eva, Configuration: Release x64 ------`
> 1>Config.cpp1
> 1>File.cpp
> 1>GUI.cpp
> 1>E:\Games\Devil May Cry HD Collection\ddmk-odcs\ddmk-odcs\Core\GUI.h(4,10): fatal error C1083: Cannot open include file: '../ImGui/imgui.h': No such file or directory
> 1>Done building project "Eva.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

it's also show similiar error in the "Kyrie","Mary" and "Lucia" Sub-Project
and only work while compiling dinput8

I am on Windows 10 using Visual Studio 2019.

according the error  GUI.h(4,10) header should normally  reference

>4 |#include  '../ImGui/imgui.h'

but then ImGui/imgui.h can't be located / detect even sub directory and file exists

i am just newbie apprentice, i will be glad if you help me

**Comment by serpentiem** [comment]
The build process has changed greatly. Maybe I'll add new instructions.
