### ISSUE TITLE
Cant use under water gun under water in DMC 1 and some more issues

### ISSUE THREAD

**Issue by 69NEPHILIM69** [serpentiem/ddmk#115]
@#First of all mod is awesome and I cant wait for a final version you are just the best
second about DMC1:

1. I just can not use underwater gun under water it says the same as i'm on the ground
2. I think problem with start of missions in the DMC 1 is that the wrong spawn coordinates of Dante or something like that 

Hope that will help you find and solve the problem...
And I have one question about DMC3:

- Can I use not the only one DT but all each one to the it's own weapon? I mean Like it was in original

**Comment by adamkenway007** [comment]
> @#First of all mod is awesome and I cant wait for a final version you are just the best
> second about DMC1:
> 
>     1. I just can not use underwater gun under water it says the same as i'm on the ground
> 
>     2. I think problem with start of missions in the DMC 1 is that the wrong spawn coordinates of Dante or something like that
> 
> 
> Hope that will help you find and solve the problem...
> And I have one question about DMC3:
> 
>     * Can I use not the only one DT but all each one to the it's own weapon? I mean Like it was in original

what DDMK version are you using?
1. when i try DDMK 2.3 its fine while use underwater gun underwater (i don't know with latter ver)
2. problem still occured

- already done by serpentiem probably next comes build

**Comment by 69NEPHILIM69** [comment]
> what DDMK version are you using?
> 
> 1. when i try DDMK 2.3 its fine while use underwater gun underwater (i don't know with latter ver)
> 2. problem still occured
> 
> * dmc3  = already done by serpentiem probably comes next build

1. I'm Using last version 2.6 beta 2 and I can not use the underwater gun
2. Hmmm I see hope you will solve it  (Otherwise, I have to play only with ddmk only in a DMC3)

- dmc3 = Awesome can't wait to see it

**Comment by 69NEPHILIM69** [comment]
Ok want to say It is not a mod bug it was something other... Now I reinstal game to try new vrsion of mod and now all perfectly working I do not know why and how... but I think it was some kind of bug from some not official localization or IDK but you can stop researching these one issue
