### ISSUE TITLE
DMC3 - CTD Mission 14

### ISSUE THREAD

**Issue by ArcadeDan** [serpentiem/ddmk#116]
So when I play on mission 14, at seemingly random points of the level, I crash to desktop. I have been using the style switcher and a couple of other options.

I think it may be due to the fact that I configured for Dante to have Beowulf on level start. I do so I don't have to pick it up and select, etc, etc. 

Not sure if anyone has had this issue or not.

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
