### ISSUE TITLE
Suggestion: Make Reset Motion State active without having to press a specific button 

### ISSUE THREAD

**Issue by Omaerahmed123** [serpentiem/ddmk#119]
This way you can easily switch between attacks at a fast rate without "delay"

**Comment by adamkenway007** [comment]
> This way you can easily switch between attacks at a fast rate without "delay"

Then how to make your suggestion to work able implement work into gamepad?doesn't it make harder to implement / complicated because more button to add & conflict with another move's

**Comment by serpentiem** [comment]
Denied. "Reset Motion State" has been renamed to "Remove Busy Flag" and merged into the Actor module. If enabled, it's activated when changing the style. Permanently removing the busy flag would make moves unreliable and look stupid.
