### ISSUE TITLE
If the resolution is too small, the ddmk menu buttons become unclickable using the mouse 

### ISSUE THREAD

**Issue by Omaerahmed123** [serpentiem/ddmk#121]
If I'm playing on 800x600 fullscreen, the ddmk menu buttons become unclickable

**Comment by adamkenway007** [comment]
> If I'm playing on 800x600 fullscreen, the ddmk menu buttons become unclickable

I'm also play in 320x240 i can't click menu button (seriously) because my video card doesn't support directx 11 so i must enabled force wrapped dx11 layer
To able play it 30fps

my spec:
Intel Celeron 1.80 Ghz
Intel HD (R) series 32 MB Vram
2 GB RAM
Windows 10 Pro Update 2004

**Comment by serpentiem** [comment]
Merged with #168.
