### ISSUE TITLE
Make tune-up bufferable

### ISSUE THREAD

**Issue by oscurums** [serpentiem/ddmk#122]
Hey, if it's possible, I think making Nevan's tune-up (neutral melee) bufferable would make the weapon more smooth to play with.
Video of how it is right now: [https://puu.sh/FXPim/3aa384510e.mp4](url)

**Comment by rlreis90** [comment]
Personally I'd rather remove tune-up entirely and let it go straight into the move.

**Comment by serpentiem** [comment]
At this point I'm not interested in modifying this behaviour.
