### ISSUE TITLE
modding "devil may cry 3 special edition"

### ISSUE THREAD

**Issue by lemons13** [serpentiem/ddmk#124]
I have dmc3 special edition and not the hdcollection edition. Their files seems to be not the same. If it can be modded, someone mind helping out?

**Comment by adamkenway007** [comment]
> I have dmc3 special edition and not the hdcollection edition. Their files seems to be not the same. If it can be modded, someone mind helping out?

dmc3 special edition already modded, you can check in nexusmod,but serpentiem abandon it because hdcollection releases
Sorry i couldn't help about modding

**Comment by serpentiem** [comment]
DDMK is for the HD Collection and the Special Edition of 4.
