### ISSUE TITLE
dmc3 not opening with ddmk 

### ISSUE THREAD

**Issue by royulte** [serpentiem/ddmk#127]
i have searched online and followed all the instructions even to the point of reinstalling the whole game and as soon as i open dmc3 it instantly crashes
[Mary.txt](https://github.com/serpentiem/ddmk/files/5147736/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5147737/dinput8.txt)

**Comment by berserkingyadis** [comment]
how did you manage to fix?

**Comment by royulte** [comment]
there was a post about a patched exe that i found after googling, and i also reinstalled
