### ISSUE TITLE
DMC 3 Not opening with ddlk

### ISSUE THREAD

**Issue by NecroLuxx** [serpentiem/ddmk#128]
Self explainatory title, whenever i start hdc and pick dmc 3 with ddlk the game just dosent run. Also both Dmc 1 and Dmc2 give a 'stoped working' error before launching when ddlk is installed.

**Comment by adamkenway007** [comment]
have you done check antivirus? idk probably mark as false positive  (cracked version)
or try update game on steam and check your drivers 

if your gpu wasn't strong enough to handle DMC:HDC like me (intel hd first gen 32 mb vram with directx10 gpu) 
you could adapt dxcpl method to force warp/convert your gpu from directx 10 to directx 11

mark as duplicate [#130](url)

**Comment by adamkenway007** [comment]
> 
> 
> Self explainatory title, whenever i start hdc and pick dmc 3 with ddlk the game just dosent run. Also both Dmc 1 and Dmc2 give a 'stoped working' error before launching when ddlk is installed.
mark as duplicate #130

please close this issue
