### ISSUE TITLE
All 3 games dont start

### ISSUE THREAD

**Issue by NecroLuxx** [serpentiem/ddmk#130]
When ddlk is installed the HD collection launcher runs, but as soon i select a game, in both dmc 1 and dmc 3 the game just dosent load, and dmc 2 gives "dmc2.exe" stopped working error.
I tried ddlk 2.5, 2.3, 0.9, 1.3

**Comment by adamkenway007** [comment]
have you done check antivirus? idk probably mark as false positive  (cracked version)
or try update game on steam and check your drivers

**Comment by NecroLuxx** [comment]
im running dmc HDC on a rx5700xt with drivers up to date, btw, here are the log files
[Mary.txt](https://github.com/serpentiem/ddmk/files/5331521/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5331522/dinput8.txt)

**Comment by adamkenway007** [comment]
> 
> 
> im running dmc HDC on a rx5700xt with drivers up to date, btw, here are the log files
> [Mary.txt](https://github.com/serpentiem/ddmk/files/5331521/Mary.txt)
> [dinput8.txt](https://github.com/serpentiem/ddmk/files/5331522/dinput8.txt)

your rig spesification is very much better than mine and i don't error there
have you try remove ddmk & mod then verify game file on steam

**Comment by NecroLuxx** [comment]
as soon as i remove mary.dll or dinput8.dll from the game directory the game launches perfectly, im playing on a cracked version to check if i can make this mod work and then buy the hdc on steam, i tried 3 different versions of the hdc and allways came to the same issue.

**Comment by adamkenway007** [comment]
> 
> 
> as soon as i remove mary.dll or dinput8.dll from the game directory the game launches perfectly, im playing on a cracked version to check if i can make this mod work and then buy the hdc on steam, i tried 3 different versions of the hdc and allways came to the same issue.

ah i see if you use cracked version try update 1 on codex

**Comment by NecroLuxx** [comment]
ill close it, but.... i've already done that lol, ty anyways

**Comment by NecroLuxx** [comment]
nevermind, it seems that it has solved the issue after a clean installation and installing update 1, thank you very much for your help
