### ISSUE TITLE
[question][not a issue] didn't Sepentiem twote something about "continue with DMC3SE and possible not touching DMCHDC"?

### ISSUE THREAD

**Issue by KateHanami** [serpentiem/ddmk#131]
I think I ready  tweet about it saying they would not want anything to do with HD Collection because the PC port was just as buggy and poorly ported as the Original DMC3SE at launch
just want to stay up to date after coming back to DMC after 5 years since DMC4

**Comment by Kazero21** [comment]
![image](https://user-images.githubusercontent.com/68538334/97104865-1bc38200-16c8-11eb-870d-7c968657ce85.png)

**Comment by KateHanami** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/68538334/97104865-1bc38200-16c8-11eb-870d-7c968657ce85.png)

in short
"that's a switch"
"just go... I don't care anymore..."
