### ISSUE TITLE
DDMK 2.7 Mary Nightly 27 October 2020 mod not working

### ISSUE THREAD

**Issue by SteveCraft1** [serpentiem/ddmk#133]
Today i have installed the latest version by the date of 10/27/2020.

I have installed the mod correctly(exactly like instructions says),but it doesnt work at all and when i check dinput8 log,it says this:
21:00:45.577 Session started.
21:00:45.582 Init
21:00:45.589 Load
21:00:45.648 Critical error: LoadLibrary failed. Mary.dll 7E

How i can resolve this(just to know,my game is updated,only this version of DDMK is giving me this problem which i never had before)?

**Comment by adamkenway007** [comment]
its work perfectly on my crappy laptop
btw my spec

Intel(R) Celeron(R) B830 1.80 GHZ
2,00 GB Of RAM
Intel HD Graphic 32 MB  of VRAM (used DirectX 10 GPU)
Windows 10 Pro 20H2
DirectX 12 Pre-Installed

I've Tried set Force Wrap Compability  & set Device Setting Feature Limit 12_0 method in Dxcpl. to force read GPU manipulate directx10 to directx 12, and set graphic setting lowest as possible

i'm sure something wrong with your pc/laptop or it's your fault (human error).

i'm recommend you to read this closed issue #130

**Comment by SteveCraft1** [comment]
i have tried to do just like the closed issue showed,i have installed the game and update again but still the same problem happen.
what more i can try to do to solve this issue?

**Comment by leo412** [comment]
Same Issue for me, 2.6 works but 2.7 doesn't.

**Comment by SteveCraft1** [comment]
Since nobody was able to solve the issue,i will close It now
