### ISSUE TITLE
DDMK 2.7 Mary Nightly 1 November 2020 DMC3 does not count my style points at dopelganger mode

### ISSUE THREAD

**Issue by 69NEPHILIM69** [serpentiem/ddmk#134]
While I'm using doppelganger mode style point counter just doesn't appear during the battle, it is just does not work and does not count my style points but at the others modes it works perfectly

**Comment by 69NEPHILIM69** [comment]
![Скриншот 2020-11-02 17 00 08](https://user-images.githubusercontent.com/63955611/97876615-236cd180-1d2d-11eb-9a29-da5689247475.png)
![Скриншот 2020-11-02 17 00 53](https://user-images.githubusercontent.com/63955611/97876622-24056800-1d2d-11eb-83e7-b88281b9b417.png)

**Comment by serpentiem** [comment]
Try the latest nightly.
