### ISSUE TITLE
DMC 3 Crashing in mission 6 - 2.7 Mary Nightly 28 October 2020

### ISSUE THREAD

**Issue by cursemex** [serpentiem/ddmk#135]
Hello there,
I've experience crashing in Mission 6 at the middle "puzzle" room with the spikes in it right after picking up Essence of Technique right when the enemies spawn. What triggers it for me is turning on actors option for player one. I've experienced crashes with Virgil and Dante. Bob(Virgil showed up for me) got caught in the spikes and died then the game froze.

[Mary.txt](https://github.com/serpentiem/ddmk/files/5454056/Mary.txt)

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, please open a new issue and attach your log files.
