### ISSUE TITLE
Crazy Combo value not working & others

### ISSUE THREAD

**Issue by KyoDMC** [serpentiem/ddmk#137]
Hey there. Congratulations for pulling this out.

When setting it up, I noticed that the Crazy Combo value change wouldn't change how fast Dante does Million Stab (Combo B) or Wildstomp. I also noticed that I could not do Million Stab out of Stinger.

Other issues/things:
- Summoned Swords carry over to Dante and can go back to Vergil, that's to keep even if they cannot be turned into Storm/Blistering until you change to Vergil again
- However (and expected), Melee charge doesn't. Would be cool if there was a way to keep this buffering (maybe a buffer accel to simulate it?) so you can switch into a Judgement Cut for example.
- I suggest putting the basic toggle on Taunt, since the switcher requires a D Pad input anyway. If it conflicts with the backwards wheel feature you inputted, maybe make the latter optional?
- (I expect you to have noticed it by now, still writing it) You cannot put a character on two different inputs or else it will be duplicated.

One last thing, is porting the chara switch over to OG 3SE planned at any point? The knockback cancellation found in OG makes it all the more tasty :'D 

Keep going man!

**Comment by 868king9999999999** [comment]
How do you update the mod

**Comment by serpentiem** [comment]
The bugs should be resolved in the latest nightly. If not please open a new issue and attach your log files. Also, no, porting back is not planned at the moment.
