### ISSUE TITLE
Multiple requests for 2.7

### ISSUE THREAD

**Issue by frog4510** [serpentiem/ddmk#138]
・Crazy combo improvement mod is not working.
・If you try to increase the value of the orb reach function, it will definitely crash.
・In 2.6, all weapons and style action sound effects worked, but they no longer work.
・I'm very happy that it didn't crash in the M19's joint battle part, but even if Vergil doesn't move and my physical strength becomes zero, the continue screen doesn't appear and I can't proceed.
I want a function to skip the joint battle part like the old PC version style switcher.
・The devil trigger does not become infinite even if you use a super character.
・For some reason, the cursor is on the sword master even though I have selected a different style when moving to an area or starting a mission. The cursor is on the sword master, but another style of technique appears. It returns to normal when the style is switched.
・There are options to increase the number of trickster tricks of Dante and Vergil, dark slayer tricks, and air hikes, but I want you to be able to activate those tricks indefinitely like the old PC version style switcher.
・All Artemis related mods are not working.
・I want an infinite devil trigger mod like the old PC style switcher.
・I want you to be able to relax the number of point blanks from Gunstinger.
・Why did you lose the sword and devil form selection function?
・Why did you lose the style switcher and weapon switcher options?
・Why did you disable the quick drive?

I am very happy that you were still alive. I hope you will continue to update DDMK.
Sorry for the unnatural English.I'm using Google Translate.

**Comment by serpentiem** [comment]
All bugs should be resolved in the latest nightly. Quick Drive will be re-added in a future update.
