### ISSUE TITLE
Changing Style Switching hotkeys

### ISSUE THREAD

**Issue by danysterkhov** [serpentiem/ddmk#139]
Hey! Thank you for your hard work on new updates.

Me and some other people ran into a problem, where our style switching hotkeys (1234) are swapped with arrows on the keyboard, for no apparent reason. 

Steam HDC version, DDMK 2.7 Mary Nightly 28 October 2020 release.

**Comment by serpentiem** [comment]
You can change the key bindings in the launcher.
