### ISSUE TITLE
DDMK 2.7 Mary Nightly 1 November 2020 DOPPELGANGER STYLE does not even choosable and two more problems

### ISSUE THREAD

**Issue by 69NEPHILIM69** [serpentiem/ddmk#142]
I can choose it only at doppelganger mode but in the others i can not even choose simple doppelganger style i tryed to place it at different buttons but i can not choose it in a game not at default mode not at character switcher

And again at doppelganger mode style rank(style points meeter) does not work

And one more at quicksilver style Dante mooves slowly too

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
