### ISSUE TITLE
Suggestion Pinnable & auto Responsive resizeable DDMK Gui

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#143]
Dear Serpentiem

Thanks for your dedication making this mods compilation for years,i know you was abandoned OG DMC:SE and move to DMC:HDC instead.change DDMK GUI from fixed area to float area is great idea, but somehow in every ddmk gui problem always make me adjust screen to higher resolution to enable every DDMK feature options then lowering after that,but the only problem isn't only me.others knew it even in 4k resolution or even 320p.Originaly DDMK always set up to 1080p / atleast 1366x768 for users. can users configure ddmk gui size as they want ?,DDMK gui can't be pin on other area in monitor screen & it's don't have auto resize Aka Responsive in DDMK Options save configuration after game close.my hope is ddmk can be used in every screen options and auto optimize it automatically detect game screen size while game launch.

Would you like add pinnable & auto responsive / resizeable DDMK GUI in future?

**Comment by SteveCraft1** [comment]
Want a tip to make It easier to touch on ddmk menu?

Go into windowed mode,It will make your mouse touch the options more easier(It make It more easier,It will not remove the entire problem)

**Comment by adamkenway007** [comment]
> Want a tip to make It easier to touch on ddmk menu?
> 
> Go into windowed mode,It will make your mouse touch the options more easier(It make It more easier,It will not remove the entire problem)

that's not work on other resolution below 1024x768 because some part of ddmk menu was missing
and also it's doesn't work to me,i play this game in 320p resolution because performace issue

**Comment by SteveCraft1** [comment]
Strange,i play on 600 x 800 of resolution and the ddmk menu doesn't disappear(also i play on 2.6 beta 2 If this help somehow) and this trick work

**Comment by adamkenway007** [comment]
> Strange,i play on 600 x 800 of resolution and the ddmk menu doesn't disappear(also i play on 2.6 beta 2 If this help somehow) and this trick work for me

i'm already to that before,your trick doesn't work to me.every ddmk updates i must increase game screen resolution to configure ddmk menu then lowering game screen  for play this game, because this problem

**Comment by SteveCraft1** [comment]
Then i don't know How to help you to use DDMK easier unfortunately,Just like you i also Hope that ddmk menu get fixed for smaller resolutions

**Comment by adamkenway007** [comment]
> Then i don't know How to help you to use DDMK easier unfortunately,Just like you i also Hope that ddmk menu get fixed for smaller resolutions
@SteveCraft1 thanks for support me.

Here are example screenshots for you @serpentiem. ddmk menu can't be drag with cursor with those resolutions

**320 x 240** resolution
![Capture](https://user-images.githubusercontent.com/24690518/98393062-5d223d00-208b-11eb-970f-1cc76f92e6e7.PNG)

**512 x 324** resolution
![Capture1](https://user-images.githubusercontent.com/24690518/98393075-627f8780-208b-11eb-82fa-f8c34669f6b1.PNG)

**640 x 480** resolution
![Capture2](https://user-images.githubusercontent.com/24690518/98393083-63181e00-208b-11eb-80dd-2ba49be2ce7d.PNG)

change either fullscreen or borderless mode won't fix this issue.

**Comment by SteveCraft1** [comment]
So this was the issue,i thought It was to press on check/uncheck box,i have a idea for that but i'm not with the laptop at the moment to show you how to pick the ddmk window

**Comment by adamkenway007** [comment]
> So this was the issue,i thought It was to press on check/uncheck box,i have a idea for that but i'm not with the laptop at the moment to show you how to pick the ddmk window,i will Record later to show How to pick the window and drag It to be completely visible

where? 
did you solve this issue ?

**Comment by SteveCraft1** [comment]
Here,i have done this on 800 x 600 resolution(windowed mode),remember that staying on fullscreen will make it harder to pick the window
![ezgif com-gif-maker](https://user-images.githubusercontent.com/73554591/98524912-8ba04380-2256-11eb-8745-e2d1ecd122f4.gif)

**Comment by adamkenway007** [comment]
> Here,i have done this on 800 x 600 resolution(windowed mode),remember that staying on fullscreen will make it harder to pick the window
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/73554591/98524912-8ba04380-2256-11eb-8745-e2d1ecd122f4.gif)
> I hope that this will help you understand how to pick the window

Umm,thanks for notice me.but have you check first which clip record version is that?
you give me DDMK menu version under 2.7 nightly clip record .yeah im understand its work on 800 x 600 resolution in previous DDMK 2.6 beta 2 but DDMK 2.7 nightly menu gui is different.your clip is it's fixed menu not floating menu

**Comment by SteveCraft1** [comment]
I don't think it's gonna happen,any version of 2.7 don't work for me and i thought that It was possible to pick the menu window Just like 2.6 beta 2 with the extra windows(like speed)

**Comment by adamkenway007** [comment]
> I don't think it's gonna happen,any version of 2.7 don't work for me and i thought that It was possible to pick the menu window Just like 2.6 beta 2 with the extra windows(like speed)

Strange,any version of 2.7 nightly work for me but with increasing resolution. is your version pirated or steam version ?

**Comment by SteveCraft1** [comment]
Pirate

**Comment by adamkenway007** [comment]
> Pirate

same here, i had pirate version try reinstalling and update 1 codex then put ddmk 2.7 nightly,i'm sure it's work.

**Comment by SteveCraft1** [comment]
The worst thing of this is that,when i Said on the other issue that i have done exactly like the closed issue,It was the reinstall game and update that i did

**Comment by adamkenway007** [comment]
> The worst thing of this is that,when i Said on the other issue that i have done exactly like the closed issue,It was the reinstall game and update that i did and even It didn't worked this New version,i don't know If memory ram count to make New version work

then,i don't know how to help you,my game always run nice with every ddmk version(with some force close problem of course in some part as bug).but i'm stuck with lowest resolution and still waiting ddmk gui fix for ddmk modder.i can't close this issue until @serpentiem fix this

**Comment by serpentiem** [comment]
Merged with #168.
