### ISSUE TITLE
2.7 new issues

### ISSUE THREAD

**Issue by frog4510** [serpentiem/ddmk#147]
・Infinite Rainstorm and Foursome Time may or may not work.
・The number of air hikes does not increase.
・There are various bugs in Vergil mode.
・There is an option to make the hit points infinite in training mode, but I want an option to make only the enemy's hit points infinite or the player's hit points infinite.
・Effects such as Volcano, Ranged Weapon Charge, Round Trip, Drive, etc. are not working.
・Doppelganger is not functioning properly.
・I have enabled the style switcher, but I can't use Quicksilver in Vergil.
・The Crazy Combo Improvement Mod is basically working, but it's still not working very well with some tricks such as satellites.
・You can switch styles with the staff roll, but it crashes when you switch weapons.
・Even if the time lag of Quiksilver is released, the movements of Doppelganger and Boss Vergil remain slow.
Probably the other bosses too.

Thank you so much for making Mission 19 work properly.
Please continue to update this mod.
Sorry for the unnatural English. I'm using Google Translate.

**Comment by serpentiem** [comment]
Try the latest nightly, all bugs should have been resolved.
