### ISSUE TITLE
DDMK 2.7 Mary Nightly 13 November 2020 my style is not rated after the mission

### ISSUE THREAD

**Issue by 69NEPHILIM69** [serpentiem/ddmk#148]
**First of all**, the mod is now simply _**magnificent**_ and _**beyond all praise**_, even now you can safely play with it and have fun.

But there is also, **secondly**, or rather, small roughness, and one of them that caught my eye right away - the game gives _**the lowest rating**_ to my style and _**considers that I earned 0 style points**_, no matter what costumes I use for the characters

**Comment by serpentiem** [comment]
Thank you! The issue should be fixed in the latest nightly.
