### ISSUE TITLE
Request to 2.7

### ISSUE THREAD

**Issue by frog4510** [serpentiem/ddmk#150]
・I know it's a difficult task, but could you make it possible to switch characters by pressing two buttons at the same time with the keyboard layout of a character switcher or the like?
・I want you to be able to set individual key layouts for Vergil and Dante.

I'm sorry to always post a silly request.
Sorry for the unnatural English.  This English is translated by Google Translate.

Postscript
I say to the fastball.
I would be grateful if you could switch characters by pressing the X and A buttons at the same time.
(The button is xinput compliant.)

**Comment by serpentiem** [comment]
Denied. I will not work on new keyboard key bindings.
