### ISSUE TITLE
multiple problems

### ISSUE THREAD

**Issue by MrSandman00** [serpentiem/ddmk#151]
game will just crash randomly, a lot on mission 5, and usually happens after enemies not being in a room where they are supposed in or the trailing effects disappearing from weapons before entering a room, every time i've tried vergil 1 it shows me a couple frames of dante next to his doppelganger and then gives me an automatic win, and i dont even have doppelganger yet

**Comment by MrSandman00** [comment]
after re downloading a lot of these issues have cleared up

**Comment by serpentiem** [comment]
Issues seem to be resolved. Closing.
