### ISSUE TITLE
dinput8.txt Has this issue, game can be open but ctrl+d will not open the ddmk table

### ISSUE THREAD

**Issue by leo412** [serpentiem/ddmk#152]
21:18:44.500 Session started.
21:18:44.504 Init
21:18:44.510 Load
21:18:44.622 Critical error: LoadLibrary failed. Mary.dll 7E

2.6 works but 2.7 all version does not work

**Comment by SteveCraft1** [comment]
You found How to solve the issue?

**Comment by serpentiem** [comment]
7E means it can't load the module. That either means the file is missing or something is blocking it. Try again with the latest nightly. If the problem persists you can try adding exceptions for the mod files to your antivirus.
