### ISSUE TITLE
Encountered Crashes & Inconsistencies

### ISSUE THREAD

**Issue by TOYSIPO** [serpentiem/ddmk#153]
Using the November 13th 2.7 Nightly build:

* Trying to change the magic drain rate crashes DMC3. Setting it to default hangs DMC3. [Mary_magicpointcrash.txt](https://github.com/serpentiem/ddmk/files/5600944/Mary_magicpointcrash.txt)
* Certain voice lines or sound effects with Dante weapons don't play. I'm not sure if this is connected to wielding them before you should have them as a result of the weapon switcher functionality. Before I beat Cerebus, I noticed I didn't have the sound effects for the Cerebus nunchucks. Right now, I still don't have sound effects for Nevan or Beowulf, but I have the sound effects for Agni & Rudra.
* You don't get style points at the end of a mission, it seems to always stay at 0. This is a relative improvement over the 2.6 I'd used, where the style gauge simply didn't display, but the post-mission report was intact. Still somewhat unfortunate.
* Crashed on a new game after playing up to Cerebus, beating it, then walking into the next room in Mission 4. Didn't think to grab the log at the time. Crash didn't happen again next boot. This was just after I noticed Cerebus' sound files not playing correctly. My completely blind guess is that this might relate to unlocking Cerebus while Cerebus is present in the inventory.
* After enough random weapon switching throughout Mission 4, I noticed the sound on most of the guns didn't apply, and eventually Ebony & Ivory lost some of their respective sounds. After taking the elevator weighed down by the chess pieces, the game crashed. [Mary_weaponswitchroomcrash.txt](https://github.com/serpentiem/ddmk/files/5601073/Mary_weaponswitchroomcrash.txt)
* Is Dante's 2nd outfit supposed to be his normal one again? 1 seems to be shirtless, 0 and 2 look the same, and 3 is his DMC1 outfit. I ask this 'cause at some point I crashed while messing with the outfits while restarting a mission repeatedly.
* On the next boot, I limited my weapon slots to 2 each. Took Nevan and Cerebus, Spiral and Ebony & Ivory. Rapidly switching guns would cause Ebony & Ivory to lose sound effects. Spiral and Nevan were missing some sound effects. Trying to enter the combat sequence after the chess piece storage room on Mission 4 crashed the game.
* Experimented with costumes, switched to 6 then to 0, game crashed. [Mary_switchcrash.txt](https://github.com/serpentiem/ddmk/files/5601173/Mary_switchcrash.txt)
* Booting with just E&I, Shotgun, Rebellion and Cerebus on MIssion 4 still doesn't get me past the room after the chess storage room, where the sand enemies spawn. For some reason, Rebellion's firing sounds still don't play on this mission. [Mary_chesscrash.txt](https://github.com/serpentiem/ddmk/files/5601216/Mary_chesscrash.txt)

Not sure if I should refrain from being a crazy person and trying to use weapons way earlier than I should, or if something is wrong. Considering I couldn't manage even with a standard loadout, I feel like a lotta bug fixing still has to be done.

**Comment by Lory9811** [comment]
I too don't have sound, not only on guns but also on devil's arms.

**Comment by serpentiem** [comment]
Should all be fixed in the latest nightly.
