### ISSUE TITLE
Cannot start the game after installing the mod

### ISSUE THREAD

**Issue by KerrangR** [serpentiem/ddmk#154]
This is what i did:

Saw the mod, downloaded the 2 dll files (dinput8.dll and Mary.dll), tried to launch dmc3 and nothing happens. Even checked task manager, the process shows up for a few seconds then disapears. 

Then, i read that i have to patch a file by downloading 2 .rar and running "patch.bat". I do it as well. game still does not launch. 

I saw that someone having the same issue was directed to another issue post and that same post also had someone directing people to ANOTHEr issue. said something about downloading dmc3-0.nbz fixing the issue. I downloaded it, backed up my .nbz and pasted the one i just downloaded, its still not working. 

here are my logs:

[dinput8.txt](https://github.com/serpentiem/ddmk/files/5646523/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/5646524/Mary.txt)

**Comment by SteveCraft1** [comment]
It's the version 2.7?

**Comment by KerrangR** [comment]
> It's the version 2.7?

I think so, ive used the "ddmk_2.7_mary_nightly_13_november_2020".

As for the patching thing, i used this link [https://github.com/serpentiem/ddmk/wiki/Installation-Instructions](url)

**Comment by SteveCraft1** [comment]
Try 2.6 beta 2 to see If you have the same problem as me and some other players

**Comment by KerrangR** [comment]
> Try 2.6 beta 2 to see If you have the same problem as me and some other players

ok, just tried ddmk_2.6_beta2_hotfix, it actually showed a black screen for a split second, this is the log for that one
[Mary ddmk_2.6_beta2_hotfix.txt](https://github.com/serpentiem/ddmk/files/5647998/Mary.ddmk_2.6_beta2_hotfix.txt)

Just tried normal ddmk_2.6_beta2 and the same thing happened, this is the log:
[Mary ddmk_2.6_beta2.txt](https://github.com/serpentiem/ddmk/files/5648006/Mary.ddmk_2.6_beta2.txt)

dinput8 log stays the same
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5648007/dinput8.txt)

**Comment by SteveCraft1** [comment]
Strange,for me,the other versions work normally,you have the update of the game(the only update dmc HD Collection have) installed?

**Comment by KerrangR** [comment]
> Strange,for me,the other versions work normally,you have the update of the game(the only update dmc HD Collection have) installed?

Also, just tried using the old dmc3-0.nbz file the game already comes with and i got the same results

**Comment by SteveCraft1** [comment]
From the time when i re installed It,i didn't needed to do the patching stuff,only needed to put the Mary and dinput 8 file on the folder and install the update on game,otherwise It always will crash

**Comment by KerrangR** [comment]
> From the time when i re installed It,i didn't needed to do the patching stuff,only needed to put the Mary and dinput 8 file on the folder and install the update on game,otherwise It always will crash

But what update? can you link me to it?

Or maybe its crashing bc i patched it? I didnt back up that data file :/

**Comment by SteveCraft1** [comment]
Your version is steam or CODEX?

**Comment by SteveCraft1** [comment]
Also,the original folder i have of the game,the nbz is patched twice(or three times) with the same method and i don't have a single crash because of that

**Comment by KerrangR** [comment]
CODEX.

I think i know what update ur talking about, looks like its gonna be another 500mb ill comment after downloading it.

**Comment by KerrangR** [comment]
Yeah, been searching since the last comment, no dice finding the update on its own, im just gonna download it all again, will post results when its done

**Comment by SteveCraft1** [comment]
devil may cry hd collection igggames
Try searching that,Just a warning,when you enter on the website,none of the links will open a new browser,so If one of them open another website(linking you to iq update or something)close It fast and try to press It again,the same thing is when you reach into the website where the update is. Good luck

**Comment by KerrangR** [comment]
Aight so, i installed it and it runs, now theres this special K stuff that wont let me control anything that shows up in the upper left menues

**Comment by KerrangR** [comment]
Also, thank you a lot for the info, i really appreciate it

**Comment by SteveCraft1** [comment]
No problem,it's 2.6 or 2.7 version,my game only let me run 2.6 and below,i Just receive a Critical error when i try to run 2.7 version,so i can't help with that

**Comment by KerrangR** [comment]
im still using the 2.6 version you told me to test, but cant do anything because some yellow letters seem to cover the buttons

**Comment by SteveCraft1** [comment]
Yellow letters? I never Saw them when i use the 2.6 version,can you show me a image of How It is on your game?

**Comment by KerrangR** [comment]
So, i installed some other mod, looks like thats whats showing those yellow letters
![image](https://user-images.githubusercontent.com/11544024/101269069-dd969500-3740-11eb-8178-85111116f92d.png)

i found the mods here: [https://www.pcgamingwiki.com/wiki/Devil_May_Cry_HD_Collection](url)

**Comment by SteveCraft1** [comment]
It seems that this thing is to show part of your computer during game
I never used It so i don't know How to solve it

**Comment by KerrangR** [comment]
Its ok, but i got another problem, i enabled the style switcher and the multi weapon stuff, but now missions instantly start, i cannot choose to customize and mission 2 starts at the inside of dantes office, basically locking me in it

**Comment by SteveCraft1** [comment]
Did you activated arcade mode? Because arcade mode will use the set parameters to instantly begin before even pressing New game or load game,to deactivate It,you need to be in mission menu or during mission

**Comment by SteveCraft1** [comment]
Anyway,i'm gonna sleep now,until tomorrow

**Comment by KerrangR** [comment]
Yeah, i did, its disabled now, just crashed but idk, its prolly bc of the other mod, thanks for all the help gn 👍

**Comment by KerrangR** [comment]
Well, i belive i can close this now, the issue was i didnt have update 1. If anyone ever sees this, and has the SAME issue as me, go check fitgirls DMCHD Collection page's comments ;)
