### ISSUE TITLE
DDMK 2.7 Mary Nightly 10 December 2020 bug. (Scheduled to be updated at any time)

### ISSUE THREAD

**Issue by frog4510** [serpentiem/ddmk#155]
・The costume becomes half-naked Dante every time you start the game.
・Switching costumes in the game will crash.
・It's inconvenient because you can only switch costumes within the mod.
・The Ebony & Ivory option does not apply at startup.
・Cerberus and Nevan's air hike does not work at startup.
・The Crazy Combo Improvement Mod is basically working, but it's still not working very well with some tricks such as satellites.

Doppelganger still has bugs.

・Doppelganger does not lock on enemies.
・Doppelganger's style action does not switch.
・Doppelganger weapons do not switch.
・Doppelganger does not pull the devil trigger.
・The bug that Doppelganger becomes slow motion when Quiksilver is released remains.
・Doppelganger's costume is fixed to half-naked Dante.

Thank you for fixing most of the bugs we reported.
We will update this page every time we find a bug.

**Comment by serpentiem** [comment]
Thank you for the bug report! These should all be fixed with the latest nightly.
