### ISSUE TITLE
It's a lie

### ISSUE THREAD

**Issue by goshante** [serpentiem/ddmk#156]
I thought it was online multiplayer.
I was looking in dmc4 for IP and port settings, but found out that this is local multiplayer with real co-player...
This kinda sucks and useless, I thouhgt i can play this with friend online. This the most disappointing and useless coop mod i ever seen...

**Comment by SteveCraft1** [comment]
I use Parsec to play online on local Coop games,maybe you will like the program

**Comment by vainiuss1** [comment]
Google parsec. Then delete this issue.
