### ISSUE TITLE
DDMK 2.7 December 10 Dmc 3 crashes After 30 to 45 minutes of playtime.

### ISSUE THREAD

**Issue by Ronneberg468** [serpentiem/ddmk#157]
I dont know whats causing but if anyone could please have a fix for this or a confirmation that it will be fixed would be very nice.

**Comment by cowboytanaka** [comment]
Exact same thing is happening to me.  Here's two separate instances:
[Mary.txt](https://github.com/serpentiem/ddmk/files/5759486/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5759487/dinput8.txt)

[Mary 2.txt](https://github.com/serpentiem/ddmk/files/5759488/Mary.2.txt)
[dinput8 2.txt](https://github.com/serpentiem/ddmk/files/5759489/dinput8.2.txt)

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
