### ISSUE TITLE
dmc3 Not loading with Mary.ddl in the Devil May Cry HD Collection folder

### ISSUE THREAD

**Issue by Behnny** [serpentiem/ddmk#158]
Here is what the Devil May Cry HD Collection folder looks like. Is there anything wrong?
![image](https://user-images.githubusercontent.com/76176637/102519958-114fb400-408b-11eb-89ea-f600b11def17.png)

**Comment by danielspanel** [comment]
I have the same problem and i see you have the codex64.dll im guessing that you got ur game cracked as well, sooo i guess it doesnt work on the cracked version.

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
