### ISSUE TITLE
Question/Suggestion: Is it possible to enable weapon/style switching separate from locking in game costumes?

### ISSUE THREAD

**Issue by DomoPANDAS** [serpentiem/ddmk#159]
Is there a setting I can toggle to where I can select the costume in-game like normal but still have weapon/style switching? Also why doesn't the Doppelganger in DT and is there a way to have it's outfit automatically be Dante's selected one?

If there isn't one may I suggest weapon/style switching related things and costume related things be separate settings, I mainly want to use this as a "set it and forget it" kind of thing and having to manually change costumes for both Dante and the Doppelganger through the interface is a small bother.

**Comment by serpentiem** [comment]
Hmmm, I could add a character option to use the globally selected costume. As for Doppelganger, you can enable its devil form by holding the right thumb button and pressing the left shoulder button.
