### ISSUE TITLE
Dante inside walls(DMC1)

### ISSUE THREAD

**Issue by crashrocket** [serpentiem/ddmk#16]
Installed today. But having an issue in 1 where progression past M3 is nonexistent. Dante is stuck in a wall whenever he spawns in. Decided to use the Arcade mode feature with M2, Room 18 (should be the Nelo Angelo 1 fight) and you can see Dante moving inside the wall. The problem does obviously disappear when I delete the mod files.

**Comment by tusk420** [comment]
hey man, has this been fixed by any release by any chance? i know this is an old post but it's messing me up and i'm kinda lost

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If not, please open a new issue.
