### ISSUE TITLE
Bloody palace crash and mild save corruption issue (2.7 Mary Nightly 10 hotfix)

### ISSUE THREAD

**Issue by AshIndigo** [serpentiem/ddmk#160]
I have this issue with bloody palace where my game randomly crashes upon reaching a floor. Though the floor that crashes the game seems to be random, as different tries have resulted in the game crashing at different points. Don't have any sort of idea why this would be happening really. Though it does make me wish there was a bloody palace floor selector

My second issue is that without the actor module enabled/having the mod not installed at all, I will be unable to use my guns at all. Dante will start T-Posing and perform generally bugged up animations when I try to use my gun. The game states that I have Artemis and Spiral equipped but neither function at all. I also had this issue with my devil arms (Dante would use some sort of beowulf moveset) but I was able to fix it by simply switching my weapon to one I had equipped and then saving to "lock it in" persay. My game also crashes when I go to the equip section under customize so I can't switch my weapons there. 

The repair menu seems to also do nothing at least based on my tests, reset weapons and gun levels don't actually do what they say they do and I've tried multiple different menus/game states to try and make it work. Maybe I'm just somehow not using the button at the right time?

I have attached my dmc3.sav file. Save slot 5 has the issue with both my devil arms and guns, and save slot 6 is with my sword issue fixed.

This issue also seems to be localized to my Dante saves only. Vergil I had no issues with, Arcade mode and a fresh save also don't have these issues.

My installation is also fresh, I tried reinstalling DDMK and the game entirely to see if that would fix the issue and it did not.

If there is anything you need from me please let me know, thank you for the great mod though
[dmc3.zip](https://github.com/serpentiem/ddmk/files/5740494/dmc3.zip)

**Comment by serpentiem** [comment]
I'll add descriptions on how to use the Repair module correctly. As for the Bloody Palace floor selector, the Arcade module kinda has that one, but it's more of a stage selector. I'll look into it. For now try the latest nightly and check if that fixes the random crashes. If not, please open a new issue and attach your log files.
