### ISSUE TITLE
DMC3 crashes upon installing DDMK

### ISSUE THREAD

**Issue by JGration** [serpentiem/ddmk#161]
I've tried every release exactly as instructed on the wiki and even with videos but the result is still the same. I cannot play DMC3 with DDMK because it crashes to desktop on launch. Mine is the DMC HD Collection. Here is my log.
[Mary.txt](https://github.com/serpentiem/ddmk/files/5751164/Mary.txt)

**Comment by danielspanel** [comment]
Is your game cracked?

**Comment by JGration** [comment]
No, I bought DMC HD collection on steam recently.

**Comment by danielspanel** [comment]
Could you share a screenshot of your root folder?

**Comment by serpentiem** [comment]
Get the latest nightly and try again. From the logs it looks like something is blocking the window hook. Could be your antivirus or some app overlay. Closing this for now. If the problem persists just open a new issue.
