### ISSUE TITLE
[CLOSED] MOD NOT WORKING ON CRACKED GAME

### ISSUE THREAD

**Issue by danielspanel** [serpentiem/ddmk#162]
I get that this issue has a really easy fix "just buy the game" but some people (like me) cant afford to pay for one of their favorite game and i see that other people are having the same issue too. When i put the files (from v2.5 and before) in the HD collection root folder the launcher starts but when i select any of the games they just dont load. I have a "codex64.dll" file in my folder and im guessing the crack is made by codex (cuz i saw another issue with similar description and the person had attached a picture of his folder in which the codex64.dll was in). I dont expect anything from this post because there are many more things that are more important than this but just putting it out there in case it has an easy solution. Anyways here are my logs:
[Mary.txt](https://github.com/serpentiem/ddmk/files/5758085/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5758086/dinput8.txt)
[Eva.txt](https://github.com/serpentiem/ddmk/files/5758087/Eva.txt)
[Lucia.txt](https://github.com/serpentiem/ddmk/files/5758088/Lucia.txt)

**Comment by danielspanel** [comment]
Btw i am only copy pasting mary, eva, lucia and dinput8 to my folder is there anything else i need to do if the error is on my part.

**Comment by SteveCraft1** [comment]
Did you have installed the update too? Because the lastest versions need the update to work

**Comment by danielspanel** [comment]
What update? Are you talking about the newer files or is there something else im missing?

**Comment by SteveCraft1** [comment]
Just like i thought,CODEX crack have a update that you need to install It,otherwise none of ddmk versions gonna work on DMC HD Collection,If you don't install the update,all the games gonna keep crashing(ddmk don't use the launcher so It will not crash)

**Comment by danielspanel** [comment]
I downloaded the game again from their site (https://www.skidrowcodex.net/devil-may-cry-hd-collection-codex/) but that didnt seem to fix it. Is this the right "update"?

**Comment by SteveCraft1** [comment]
Here a link for the update installer(when you press on download button,If It open any browser instead of download,close It and press on download button again,keep doing that until your browser begins to download the rar file)
https://megaup.net/Lr5?pt=jnBoiFvlvi5%2FuXaH8pg6Covdu1CLL0fVYOdnkn6X3Jk%3D

**Comment by SteveCraft1** [comment]
What you installed from their website was only the game,not the update

**Comment by danielspanel** [comment]
Works like wonders thank you very much :D

**Comment by danielspanel** [comment]
A useful feature/setting would be to adjust the font/size of the text because my monitor is like 1280x1024 and i run the game on 1280x720 windowed and i cant very clearly read the different settings ;d

**Comment by SteveCraft1** [comment]
No problem,i Hope that you play the game without problem now
