### ISSUE TITLE
Game will not start after installing new release

### ISSUE THREAD

**Issue by Escavalien** [serpentiem/ddmk#163]
Hello, I got ddmk 2.6 beta working a while back. Decided to get the new 2.7 nightly, I installed it by doing these steps:

I deleted the ddmk files from the game's directory
Downloaded the new release
Extracted it to the directory
Launched the game (it doesn't actually launch, it just sorta crashes on startup)
Then I did the steps including xdelta and patch.bat and there's no change, it still crashes on startup and never gets me in game.

I am in fact using the official steam release. I've had this happen a few times now and I got it to work in 2.6 by uninstalling the entire game, and that's really goddamn convenient if I have to uninstall the entire game every time I want to update to a new version of ddmk. If I am doing something wrong please add thorough instructions on how to uninstall/update ddmk on the wiki as all I had to go off of were the install instructions over there.

**Comment by serpentiem** [comment]
I assume we are talking about 3 from the HD Collection. Usually when updating you only have to replace `dinput8.dll` and `Mary.dll`. Can you share your log files? You can find them in `logs` in the game's root directory.

**Comment by serpentiem** [comment]
Closing.
