### ISSUE TITLE
Please help cant get this to work keeps crashing when trying to launch dmc3

### ISSUE THREAD

**Issue by CloudChaser87** [serpentiem/ddmk#166]

**Comment by CloudChaser87** [comment]
i only get gdata.afs after trying to launch game with latest mary dll. it doesnt show up with 2.5 dlls

**Comment by CloudChaser87** [comment]
im reinstalling game will post screenshot of main directory after trying to install for 3rd time

**Comment by CloudChaser87** [comment]
i think i worked it out but i havent checked yet. i think its cause i was using the non mary dlls from 2.5 instead of 2.6 beta 2 hotfix.

**Comment by CloudChaser87** [comment]
figured it out my antivirus was stopping it from working

**Comment by serpentiem** [comment]
Have fun!
