### ISSUE TITLE
[Request] Access More Vergil Potential Moveset on M20

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#17]
Hi serpentiem,could you allow player access vergil moveset on mission 20 such as judgement end (similiar on dmc 4 / multiple judgement cut),purple sphere shield,trick backward and trick forward

Edit.
Enable use Force Edge on nelo angelo if possible

**Comment by lokilokiad** [comment]
like his defence ball as RG style & ultimate judgemnt cuts

**Comment by adamkenway007** [comment]
> like his defence ball as RG style & ultimate judgemnt cuts

yes similiar like that

**Comment by lokilokiad** [comment]
it may require writing the moveset for the animations it will look very cool

**Comment by darthnoward** [comment]
it'll be great to enable him to judgement 5 times in DT

**Comment by serpentiem** [comment]
Check the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15).
