### ISSUE TITLE
DMC1 softlock upon loading save file on chapter 3

### ISSUE THREAD

**Issue by oxyacetylene** [serpentiem/ddmk#171]
[Video of problem](https://www.youtube.com/watch?v=E3V0dPJZyhU)
[Second video of problem](https://www.youtube.com/watch?v=yQBA9zIUTE8)

Steps that I took to get to this point:

- Installed 2.7 Nightly on its own on accident
- Uninstalled that
- Installed 2.5
- Installed 2.6b2 hotfix on top of that
- Installed 2.7 January Nightly on top of that
- Installed the DMC3 patch
- Booted DMC1 with my one save file that's on chapter 3
- Dante is offscreen and the camera is not pointed at him
- After a while I am no longer able to press anything
- The teleporter button pops up a window that just says "yar!"???

**Comment by serpentiem** [comment]
Will investigate.

**Comment by serpentiem** [comment]
Merged with #184.
