### ISSUE TITLE
Ddmk 2.7 mary nightly 14.January crashing issues

### ISSUE THREAD

**Issue by Ronneberg468** [serpentiem/ddmk#172]
Unfortunaly the game still randomly crashes after aroun 30 to 45 minutes of playing.
[Mary.txt](https://github.com/serpentiem/ddmk/files/5833185/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/5833186/dinput8.txt)

**Comment by serpentiem** [comment]
Should be fixed in the [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly7).
