### ISSUE TITLE
Not an Issue I made pictures for radial menu

### ISSUE THREAD

**Issue by 69NEPHILIM69** [serpentiem/ddmk#173]
If someone interested - you can download it here and replace them with changing names of the files(if it changed after loading to here) in your Images mod folder in the game root folder and replace the original ones

Sorry if I can not place that here

![weapon_0013](https://user-images.githubusercontent.com/63955611/105470044-216e3b00-5caa-11eb-80fd-adbfb91dda59.png)
![weapon_0000_0000](https://user-images.githubusercontent.com/63955611/105470047-229f6800-5caa-11eb-9307-12b5b0947851.png)
![weapon_0000_0001](https://user-images.githubusercontent.com/63955611/105470048-229f6800-5caa-11eb-85de-3728e93c62f4.png)
![weapon_0000_0002](https://user-images.githubusercontent.com/63955611/105470049-229f6800-5caa-11eb-8c4b-33027d580f3c.png)
![weapon_0001](https://user-images.githubusercontent.com/63955611/105470050-2337fe80-5caa-11eb-90a3-d65665fe950e.png)
![weapon_0002](https://user-images.githubusercontent.com/63955611/105470052-2337fe80-5caa-11eb-9e68-14fb69865de6.png)
![weapon_0003](https://user-images.githubusercontent.com/63955611/105470053-23d09500-5caa-11eb-8c3b-238b9f1451b8.png)
![weapon_0004](https://user-images.githubusercontent.com/63955611/105470055-23d09500-5caa-11eb-82c2-b108438077a4.png)
![weapon_0005](https://user-images.githubusercontent.com/63955611/105470056-24692b80-5caa-11eb-9620-0054522347a1.png)
![weapon_0006](https://user-images.githubusercontent.com/63955611/105470059-24692b80-5caa-11eb-8561-40d320f273b8.png)
![weapon_0007](https://user-images.githubusercontent.com/63955611/105470060-24692b80-5caa-11eb-9288-d73db88aea54.png)
![weapon_0008](https://user-images.githubusercontent.com/63955611/105470062-2501c200-5caa-11eb-9f00-6337cdbf0b64.png)
![weapon_0009](https://user-images.githubusercontent.com/63955611/105470063-2501c200-5caa-11eb-8867-45f4177fd687.png)
![weapon_0011_0000](https://user-images.githubusercontent.com/63955611/105470065-259a5880-5caa-11eb-9667-72f2ae66bc8a.png)
![weapon_0011_0001](https://user-images.githubusercontent.com/63955611/105470067-259a5880-5caa-11eb-9384-4f00251d016c.png)
![weapon_0012_0000](https://user-images.githubusercontent.com/63955611/105470068-259a5880-5caa-11eb-917c-3232c61b64f0.png)
![weapon_0012_0001](https://user-images.githubusercontent.com/63955611/105470069-2632ef00-5caa-11eb-8864-07d05ba23772.png)

not the best but better than just words... Yeah?

why 3 pics of beowulf? becouse you need 3 copy of it 1 Dante 1 Vergil and 1 Nelo Angelo (Vergils corrup costume devil trigger)
why 2 Rebellion and force edge? it depends on stage of walkthrough (i think) and Dante costume (from the first game)

**Comment by 69NEPHILIM69** [comment]
not the best but better than just words... Yeah?

**Comment by 69NEPHILIM69** [comment]
why 3 pics of beowulf? becouse you need 3 copy of it 1 Dante 1 Vergil and 1 Nelo Angelo (Vergils corrup costume devil trigger)
why 2 Rebellion and force edge? it depends on stage of walkthrough and Dante costume (from the first game)

**Comment by SteveCraft1** [comment]
Thanks for the images

**Comment by DokiXsh1** [comment]
Thanks for the images

**Comment by serpentiem** [comment]
You had good intentions, but please don't post copyrighted images here.

**Comment by 69NEPHILIM69** [comment]
> You had good intentions, but please don't post copyrighted images here.

ok sorry if you get troubles
