### ISSUE TITLE
Crash happens... how do I fix it?

### ISSUE THREAD

**Issue by mulberry154** [serpentiem/ddmk#174]
Now I can't play hd collection dmc3... This new version ddmk worked for the first 15minutes and then something got wrong

I've deleted steam local files and installed it again to make things normal, but it comes with same files in the end.

Could you give me some answer to deal with this situation?

**Comment by serpentiem** [comment]
Try again with the [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly7). If the problem persists, open a new issue and share your log files.
