### ISSUE TITLE
Confusion about installation instructions

### ISSUE THREAD

**Issue by SSSiyan** [serpentiem/ddmk#175]
Do you still need to follow all the instructions over at https://github.com/serpentiem/ddmk/wiki/Installation-Instructions ?
I had only just noticed them and have just been dropping the dlls in

**Comment by alansamson** [comment]
Agreed. Imo, each update archive should have up-to-date readme

**Comment by dyoxon** [comment]
i followed the rabbithole down, so all of this is 100% alien to me, i can't even find the dlls....

**Comment by serpentiem** [comment]
I'll update them soon.
