### ISSUE TITLE
Crashes and enemy disappereance

### ISSUE THREAD

**Issue by Akhundelar** [serpentiem/ddmk#176]
Basically game crashes after about 1hour playing even with the latest update, plus in some battle sections enemies just disappearing. Dunno how to fix this

**Comment by alansamson** [comment]
Oh, so maybe this crash thing isn't exclusive to just Bloody Palace.

**Comment by serpentiem** [comment]
Should be fixed in the [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly7). If not, open a new issue and share your log files.
