### ISSUE TITLE
How to Activate Doppelganger in 2.6 beta 2?

### ISSUE THREAD

**Issue by Tsunemakano** [serpentiem/ddmk#177]
I have use ddmk 2.6 beta 2, i already activate doppelganger in menu but when I press right thimb and left thumb together, nothing happen. Do i have to do something first?

**Comment by SteveCraft1** [comment]
If you didn't passed mission 17,then It's not possible to select It yet,different from 2.7,2.6 don't force you to have end game stuff since beginning

**Comment by SteveCraft1** [comment]
Also,i recommend to hold one of the sticks and press the other,this way is easier to select it

**Comment by Tsunemakano** [comment]
> If you didn't passed mission 17,then It's not possible to select It yet,different from 2.7,2.6 don't force you to have end game stuff since beginn

I already

**Comment by Tsunemakano** [comment]
> If you didn't passed mission 17,then It's not possible to select It yet,different from 2.7,2.6 don't force you to have end game stuff since beginning

I already passed mission 17.

**Comment by SteveCraft1** [comment]
Your version is "2.6 beta 2" or "2.6 beta 2 hotfix",because If it's without hotfix,i don't remember being able to select doppelganger on that version

**Comment by Tsunemakano** [comment]
> Your version is "2.6 beta 2" or "2.6 beta 2 hotfix"?,because If it's without hotfix,i don't remember being able to select doppelganger on that version

Hotfix

**Comment by SteveCraft1** [comment]
Did you have style switcher activated?

**Comment by SteveCraft1** [comment]
Because If not,then It's not possible to access It,even If you activate the doppelganger option

**Comment by Tsunemakano** [comment]
> Because If not,then It's not possible to access It,even If you activate the doppelganger option

I am activated weapon switcher and style switcher, even doppelganger.

**Comment by SteveCraft1** [comment]
For some reason,you have force single actor/multiplayer activated?

**Comment by Tsunemakano** [comment]
I only have force single 

> For some reason,you have force single actor/multiplayer activated?

I only have force single actor because if i turn it off, the style meter will disappear.

**Comment by Tsunemakano** [comment]
> I only have force single
> 
> > For some reason,you have force single actor/multiplayer activated?
> 
> I only have force single actor because if i turn it off, the style meter will disappear.

Oh yeah I have to turn force single actor off first

**Comment by SteveCraft1** [comment]
Force single actor will always force the game to have only 1 player,on multiplayer and doppelganger,if you have force single actor activated,the ddmk Will never let you select doppelganger
Answer to your problem:deactivate the force single actor to use doppelganger.

The ddmk normally(without force single actor) recognize player 2/doppelganger as the player 1,that's why without FSA,you're unable to see style meter

**Comment by Tsunemakano** [comment]
> Force single actor will always force the game to have only 1 player,on multiplayer and doppelganger,if you have force single actor activated,the ddmk Will never let you select doppelganger
> Answer to your problem:deactivate the force single actor to use doppelganger.
> 
> The ddmk normally(without force single actor) recognize player 2/doppelganger as the player 1,that's why without FSA,you're unable to see style meter

So what should I do about style meter?

**Comment by SteveCraft1** [comment]
The game still recognize your style point(during combat)it's only that you're not gonna be able to see your Character use style meter,by other side,it's gonna be your doppelganger that gonna be using style meter If you don't use FSA

**Comment by Tsunemakano** [comment]
> The game still recognize your style point(during combat)it's only that you're not gonna be able to see the style meter working because of your Character,it's gonna be your doppelganger that gonna be using style meter If you don't use FSA

So I dont have to worry about that?

**Comment by SteveCraft1** [comment]
Basically,you need to sacrifice the style meter to have doppelganger

**Comment by Tsunemakano** [comment]
And also when I use doppelganger the dt form is not activate so i have to activate by myself?

**Comment by SteveCraft1** [comment]
> > The game still recognize your style point(during combat)it's only that you're not gonna be able to see the style meter working because of your Character,it's gonna be your doppelganger that gonna be using style meter If you don't use FSA
> 
> So I dont have to worry about that?

If it's anything good,while you're doing good combos,try to use taunt button to see If Dante gonna use some taunt that only work on bigger style point(like A,S,SS,SSS),on these,Dante can only use 2 taunt,the "sweet baby!" And"Let's start the party!"

**Comment by SteveCraft1** [comment]
> And also when I use doppelganger the dt form is not activate so i have to activate by myself?

I don't have answer for that because It make 1 year since last time i played on 2.6 beta 2 hotfix,you're Lucky that i still remembered why you was unable to select doppelganger

**Comment by Tsunemakano** [comment]
In n

> > And also when I use doppelganger the dt form is not activate so i have to activate by myself?
> 
> I don't have answer for that unfortunately,because It make 1 year since last time i played on 2.6 beta 2 hotfix,you're Lucky that i still remembered why you was unable to select doppelganger

That’s alright thank you anyway, i guess I have to activate dt form by myself.

**Comment by SteveCraft1** [comment]
No problem

**Comment by SteveCraft1** [comment]
Also i think that you can close now since we found the answer
