### ISSUE TITLE
UI is too small and how to activate style switcher

### ISSUE THREAD

**Issue by Voidzer** [serpentiem/ddmk#178]
So I am trying to get this to work and I've run into two problems. The first being that the UI is terribly small, and the second one is I don't know how to activate the style switcher. On the topic of the style switcher, is it usable on controller and if it is, what buttons switch the styles? Also if we could get the install guide updated so that it is more indepth that would be ideal since I had a heck of a time figuring it out.

**Comment by SteveCraft1** [comment]
It's 2.6 or 2.7?

**Comment by SteveCraft1** [comment]
If it's 2.7 then only Go on actor and enable the First block that appear

**Comment by DomoPANDAS** [comment]
"unfortunately Style Switcher and Weapon Switcher is now combined with Actor section"

This is is one of the very few gripes I have with this tool. All I was looking for was a way to swap Styles and Weapons akin to the Switch version, but it seems to come at the cost of overiding any selected costumes.

I mean the tool is fantastic for sure and I'm sure most people make use of all of the hard work being put into it but for me all the bells and whistles are are more of a minor hinderance than anything.

I just just want to boot up DMC3 and play it like normal, butvwith the addition of weapon/style switching. 

Honestly my ONLY other issue is how doppelganger works, it's cool that you can have a non-DT version but I wish the "default" one was DT'd instead, or better yet, if weapon/style switching were seperate from character/costume changes and your Doppleganger automatically changed to DT and back WITH you this thing would be utterly flawless imo.

**Comment by serpentiem** [comment]
I'll add a scaling option for the GUI. For style switching, enable the Actor module. By default you can then switch styles with the D-Pad.
