### ISSUE TITLE
Bloody Palace crash

### ISSUE THREAD

**Issue by alansamson** [serpentiem/ddmk#179]
Was playing Bloody palace with Vergil, actor was enabled, everything else was default iirc. Only forced files for Vergil. So, basically one of the stages was completely clear from the start and then usual 3 pads to proceed to the next stage. Next one simply brought me to desktop without any crash error or whatsoever.

Not sure if it was caused by ddmk, because I haven't played bloody palace before.

**Comment by alansamson** [comment]
Tested it again. Game crashed at level 840. Maybe it also depends on timer. Still no idea about cases with Dante, cause I suck at him. Maybe it's the thing as well for him.

**Comment by serpentiem** [comment]
Should be fixed in the [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly7). If not, please open a new issue and share your log files.
