### ISSUE TITLE
The latest version wasnt working. Downloaded the DDMK 0.998 version. How to update now?

### ISSUE THREAD

**Issue by nrohit92** [serpentiem/ddmk#181]
Hi. I did the whole method with the 2.7 version but for some reason the game would never launch. I found an old reddit post (https://www.reddit.com/r/DevilMayCry/comments/a3m8yk/ddmk_0998/) with the DDMK 0.998 version and the style switch works (with a few fps drops). Can you please tell me how to update this to the latest version. 

Also the 0.998 version doesnt allow me to click on "enable" for weapon switch . Please tell me how to update to the latest version and also get access to all the weapons at one go. (or atleast the option to have 3-4 weapons)

**Comment by nrohit92** [comment]
Ok. I got the weapon switch to work. But I am still unable to make the latest ddmk version to work. How to quickly update from 0.998 versio to the 2.7 version ? 

Also, what's the procedure to remove previous versions of the mod ?

**Comment by SteveCraft1** [comment]
This same thing happen with 2.5/2.6 to you?

**Comment by nrohit92** [comment]
I bought the HD collection on steam.

**Comment by SteveCraft1** [comment]
This problem only happen on 2.7 or It also happen on 2.5 and 2.6?

**Comment by nrohit92** [comment]
2.7 only. I would have to try the the 2.5 version once again, as I dont clearly remember. I also rememeber that one of the version (called betafix) also did not work

Which is the latest stable version you recommend?

**Comment by SteveCraft1** [comment]
If it's for multiplayer then 2.6 beta 2 hotfix,since this is the one that have most stuff working on multiplayer(as also It don't force Max level style since New game and allow 4 players on combat[unfortunately player 3 and 4 are unable to Lock their aim on the enemy {they are able to use Lock on but you need to still change their vision}]),the only problem is that mission 19 is unable to pass even without multiplayer and doppelganger activated.
Try the other versions of 2.7 to see If one of them gonna work(on my game the some of the beginning versions of 2.7 didn't worked but later versions of 2.7 have worked)

**Comment by SteveCraft1** [comment]
Yet If you looking to want to play mission 19 with ddmk activated then try 2.5 or 2.6 beta 2(without being hotfix) you will manage to play It If you don't use these options,"force single actor"(which make style meter recognize player 1 instead of player 2)"multiplayer". 2.7 version allow Coop on this mission(but last time i Checked,It crash on the área where you need to use samsara when you get there with the item on 2 players,forcing you to use Teleporter to Skip it,i'm not sure If this last version "14 february" have solved It,and i don't know If the last version have solved the issue of 3/4 players causing instant crash when begin any mission)

**Comment by nrohit92** [comment]
Bro, I don't care about multi-player at all. I only want a smooth style and weapon switcher. Please tell me if the 2.5 version is stable enough for that ?

**Comment by nrohit92** [comment]
I will disable the mod during mission 19 by renaming the dll files

**Comment by SteveCraft1** [comment]
> Bro, I don't care about multi-player at all. I only want a smooth style and weapon switcher. Please tell me if the 2.5 version is stable enough for that ? 
> 
> 

A simple answer for that is YES,check the information below to know How it's on 2.5

If the weapon switcher you want is switch style then no,but If you don't Care which type is then It's fine(the type of weapon switcher on 2.5 is similar to dmc4 and DMC5 weapon switcher),also style switcher is quite the same as dmc4(on 2.5) and to equip Quicksilver you need to unlock It First and press a style button 2 times to equip It,doppelganger is by pressing both thumb(R3 and L3 on PS).

**Comment by nrohit92** [comment]
Ok, I will download the 2.5 version in the night once I return. Thank you so much for sharing all this info. Really grateful for it. 

I am actually done with 90% of the game and currently I am on DMD Mission 10, so I felt this is the right time to practice style switcher. And by weapon switcher I meant that I wanted the option to equip only the weapons of my choice (for eg, I never equip artemis or shotgun and mostly prefer only 3 guns: E&I, SPiral, KA and also I never use Nevan so I dont want to equip it but I want all the other melee weapons)

**Comment by SteveCraft1** [comment]
I don't remember but i suppose that it's possible to choose How many and which weapons you gonna carry(on both fire arms and Devil arms) on 2.5 version

**Comment by nrohit92** [comment]
Hey bro. So I downloaded the 2.5 version mod and it works fine. However, I am facing the below issues 

1. Sometimes the game skips a compulsory battle or a boss fight after which it will eventually hangup
2. During the levels of 5000, the bloody palace started skipping the battles and would directly pop the fountains (which allow you to go to the next level of the palace). Eventually the game crashes after such levels. 
3. When I disable the mod (by renaming mary.dll) I am not able to equip 2 swords and 2 guns for dante and instead I am getting the options to only equip one sword and one gun (and few guns miraculously became level 1 again) 

are these problems persistent? Is there some settings I can modify to remove these glitches?

**Comment by SteveCraft1** [comment]
Try to test 2.6(2.6,2.6 beta 2 and 2.6 beta 2 hotfix)version,this was the one that i most played and i'm sure(on 2.6 beta 2 and hotfix version too) that these stuff don't happen(about the third issue,If you are using weapon switcher on a complete New Game,then the weapons might be bugged until you catch the weapons during missions)

**Comment by nrohit92** [comment]
Hey bro. Ok I will try the 2.6 version. 

Also, regarding the 3rd issue, I am not using weapon switcher in a new game. I am in fact not able to select weapons in the DMD run.

**Comment by nrohit92** [comment]
Can you please tell me how to update the mod? Just copy the mary.dll and dinput files? Or do i have to remove all the files (the xdelta and patch files) and reinstall again?

**Comment by nrohit92** [comment]
Just installed 2.6 beta 2 and it crashed in DMD M10.

**Comment by nrohit92** [comment]
I will try the hotfix in a while

**Comment by SteveCraft1** [comment]
> Can you please tell me how to update the mod? Just copy the mary.dll and dinput files? Or do i have to remove all the files (the xdelta and patch files) and reinstall again?

Sorry for not being able to answer before,i was sleeping,no, you don't need to re-install the xdelta and patch files,all you need to do is remove the version before and put the other version

**Comment by serpentiem** [comment]
I will update the install instructions soon. For now, grab the [Latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly7) and extract the contents of the archive to the DMC HDC root directory.

By default that's "C:\Program Files (x86)\Steam\steamapps\common\Devil May Cry HD Collection".

Overwrite "dinput8.dll" and "Mary.dll" if prompted.

If the problem persists, open a new issue and share your log files.
