### ISSUE TITLE
Vergil with Dante's voice

### ISSUE THREAD

**Issue by SuperfieldCU** [serpentiem/ddmk#182]
Latest nightly (Feb 14 2021) finally fixed the crash on Arkham when Vergil joins, so I could finish the game at long last. Decided to jump straight into Vergil's playthrough, only to find that Vergil had Dante's voice - attacks, taunts, etc. ~~His weapons still used their proper sounds... except for~~ the Summoned Swords, which were entirely silent. I disabled the actor option, changed the character count to 1, swapped character 1 (and its clone) to Vergil, but nothing changed.

**Comment by 69NEPHILIM69** [comment]
Did you use force files option in Actor menu? If not then try it

**Comment by SuperfieldCU** [comment]
Enabling the Actor setting, enabling the Force Files setting and changing the dropdown below that to Vergil and restarting the game does indeed restore his voice. However, it also gives Vergil his entire moveset, and I only just started the game. Turning the Actor setting off and restarting the game puts my character progress back to where it should be, but puts Dante's voice back onto Vergil.

**Comment by SuperfieldCU** [comment]
Also, I take back what I said before, when Vergil has Dante's voice, his weapon sounds are actually not right. If they whiff, they make no noise at all; if they hit, then they use Rebellion's sound effects.

With some experimentation of activating/deactivating the Actor option and quitting missions without fully restarting the game, I was able to eventually get the Actor option turned off (so as to not have Vergil's full moveset) with the proper voice and weapon sound effects. But restarting the game with the option off puts Dante's voice right back.

**Comment by alansamson** [comment]
As of now, you can't play with Vergil VO and weapons sfx without actor enabled.

**Comment by SuperfieldCU** [comment]
Okay, I found that if you start up a mission with Actor turned on, then turn it off during the mission, then quit and restart the mission (without closing the game), then Vergil will have the proper audio and you can keep your progress.

**Comment by serpentiem** [comment]
It's a known bug. I'm working on it. Merged with #167.
