### ISSUE TITLE
Request: Reorder Vergil's weapons

### ISSUE THREAD

**Issue by SuperfieldCU** [serpentiem/ddmk#183]
Across Vergil's playable appearances in DMC3:SE, DMC4:SE, and DMC5:SE, the default configuration of his weapon swapping hasn't been consistent. In 3 and 5, the cycle goes (when pressing right trigger) Yamato -> Beowulf -> Force Edge+Yamato. Makes sense, that's the order he gets/uses them in 3's story. But in 4, by default, it goes Yamato -> Force Edge+Yamato -> Beowulf for some reason. Problem is: I've never put much time into Vergil in 3, but a ton into 4, and got used to that version of his weapon swap. Fortunately, you can rebind it using the Options menu in all three games... except that, in 3, the control configuration is shared between Dante and Vergil.

It'd be nice to be able to switch around the order with the mod (like you can with Dante) so that I don't have to swap the controls back and forth every time I change characters.

**Comment by serpentiem** [comment]
That's easy to do. Will implement.
