### ISSUE TITLE
Arbitrary Weapon Switcher Image Layering

### ISSUE THREAD

**Issue by wolfchev** [serpentiem/ddmk#187]
Could the layering order be changed from (background -> weapon -> highlight) to (background -> highlight -> weapon)?
or a way to select the order, whichever option makes more sense

Example of what I mean:
https://cdn.discordapp.com/attachments/457112165082726400/813054786626650152/unknown.png

I'd like the red part to be below the weapons

**Comment by serpentiem** [comment]
Shouldn't be too hard to implement. I wanted to research how ImGui handles focus anyway.
