### ISSUE TITLE
dmc 3 wont start when theres dinput8.dll from ddmk on root folder

### ISSUE THREAD

**Issue by 00bruh** [serpentiem/ddmk#189]
title is self explanatory already but yeah the game wont start but by removing dinput8.dll i cant use ddmk idk if anyone got this issue or not i typed this cause i cant find any solution online.

**Comment by serpentiem** [comment]
Share your log files.

**Comment by 00bruh** [comment]
> Share your log files.

im really sorry i dont know where to find them

**Comment by serpentiem** [comment]
They are in the `logs` directory inside your DMC HDC root directory.

By default that is `C:\Program Files (x86)\Steam\steamapps\common\Devil May Cry HD Collection\logs`.

You should be able to just drag and drop the files here.

**Comment by SteveCraft1** [comment]
Go to your game's folder and you will find a folder named logs,pick the dinput8 and Mary txt files since these are the ones for DMC3 ddmk

**Comment by JazzDingus** [comment]
[dinput8.txt](https://github.com/serpentiem/ddmk/files/6047419/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6047420/Mary.txt)

I think I'm having a similar issue. I can't get the game to start unless I delete dinput8.dll OR Mary.dll, but then ddmk won't work. I put my logs on.

**Comment by serpentiem** [comment]
> [dinput8.txt](https://github.com/serpentiem/ddmk/files/6047419/dinput8.txt)
> [Mary.txt](https://github.com/serpentiem/ddmk/files/6047420/Mary.txt)
> 
> I think I'm having a similar issue. I can't get the game to start unless I delete dinput8.dll OR Mary.dll, but then ddmk won't work. I put my logs on.

Going by your log the system cache cannot be initialized. Do you happen to have extracted the game files before?

**Comment by JazzDingus** [comment]
I tried extracting the ddmk files before but it seems to be the same problem, perhaps I'm doing it wrong? Or do you mean to extract another file

**Comment by serpentiem** [comment]
Nah, I was just wondering if you messed with the file `dmc3-0.nbz`. Judging by your message I don't think you did though. I'll check the cache initialization function again and look for potential problems.

**Comment by 00bruh** [comment]
sorry been busy with school i forgot to respond here are my logs thank you very much

[Mary.txt](https://github.com/serpentiem/ddmk/files/6057593/Mary.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/6057594/dinput8.txt)
[Eva.txt](https://github.com/serpentiem/ddmk/files/6057595/Eva.txt)
[Lucia.txt](https://github.com/serpentiem/ddmk/files/6057596/Lucia.txt)

**Comment by TheSnazzySean** [comment]
I am also having this issue Lol.
[dinput8.txt](https://github.com/serpentiem/ddmk/files/6059932/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6059933/Mary.txt)

**Comment by HugoBr013** [comment]
Me too
[dinput8.txt](https://github.com/serpentiem/ddmk/files/6071997/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6071998/Mary.txt)

**Comment by HugoBr013** [comment]
But my logs are very small, I don't know why

**Comment by deva4eva** [comment]
Same issue here, if dinput or mary.dll is present, the game won't launch. If I remove either, the game start but without the mod.


[dinput8.txt](https://github.com/serpentiem/ddmk/files/6128944/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6128945/Mary.txt)

**Comment by SteveCraft1** [comment]
For everyone with this problem,check if there's a folder named Gdata.afs inside data/dmc3 folder,if not,then extract it from the NBZ file that is there,this issue of not opening for me was because there wasn't a folder named Gdata.afs
![dmc3 14_03_2021 10_07_46](https://user-images.githubusercontent.com/73554591/111069758-4bbfc600-84ad-11eb-994a-1871bd914b97.png)

This is how it needs to be on dmc3 folder,if it's exactly like that and the issue is still happening,then i don't know what is the problem exactly

**Comment by chaosPDRN** [comment]
I am still having this problem, even after extracting Gdata.afs. I looked in the folder before the extract and it only had one file in it but I could run the game.

**Comment by serpentiem** [comment]
Try again with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If the problem persists, please open a new issue.
