### ISSUE TITLE
Devil trigger gauge stuck?

### ISSUE THREAD

**Issue by GastricBoar** [serpentiem/ddmk#191]
Fiddled a bit with the teleporter, and noticed my vitality gauge and dt gauge were reset to first game level. Tried restarting the game and it seems to have fixed the vitality gauge problem, but my devil trigger gauge is still stuck to three ticks, how can i solve this?

**Comment by serpentiem** [comment]
These are two things that at first sight don't look like they have anything in common, like: "I used the elevator and now I have a flat tire." Can you tell me a bit more about how you fiddled with the teleporter?

**Comment by GastricBoar** [comment]
> These are two things that at first sight don't look like they have anything in common, like: "I used the elevator and now I have a flat tire." Can you tell me a bit more about how you fiddled with the teleporter?

Sorry, was a little too vague there! I was trying to use the teleport function for the first time, just typing random numbers in the teleport field. Anyways, i typed a number that apparently didn't correspond to anything on the teleporter, and just got a black screen (could still hear background music tho) with no option of turning back other than closing the game manually. Restarted the game and my vitality and dt gauges were reset to first mission level. Fixed the vitality gauge by just selecting another mission from the menu, but my dt gauge was still stuck to 3 ticks. So after a couple tries, i thought i'd enable the arcade mode tool, manually give myself back the missing ticks using the two modifiers, then disabling it. Somehow it worked!

**Comment by serpentiem** [comment]
Very peculiar, but I'm glad to hear it worked out for you! Closing this issue.
