### ISSUE TITLE
Vergil actor crash

### ISSUE THREAD

**Issue by alansamson** [serpentiem/ddmk#192]
Looks like game still crashes even with latest update. Crashes occur around 1 hour mark when playing with Vergil actor enabled. Both bloody palace and story mode.

**Comment by Ronneberg468** [comment]
When playing story mode instead of selecting the mission continue option quit to the main menu and load the next mission from there. With this little trick the game didnt crash for me hope this helps.

**Comment by alansamson** [comment]
> When playing story mode instead of selecting the mission continue option quit to the main menu and load the next mission from there. With this little trick the game didnt crash for me and i could complete the game from start to finish without issues. Hope this helps.

I know it's been two weeks almost, lol, but it still doesn't fix the issue for bloody palace

**Comment by serpentiem** [comment]
There are still some leaks which I can't quite pinpoint. I'll ask my testers to do a bloody palace playthrough. I hope to get some insight from their data.

**Comment by alansamson** [comment]
After recent update, was able to play normally for about 40 minutes in Bloody Palace. Earlier, it would crash even after 30 minutes of playing. Maybe issue got solved, but I will need more testing when I have time.

**Comment by serpentiem** [comment]
I was able to finish Bloody Palace; Will close for now.
