### ISSUE TITLE
weapons and styles level 

### ISSUE THREAD

**Issue by cross1993** [serpentiem/ddmk#194]
when enabling the mod,all styles and weapons go up to the highest level with all moves unlocked and the only way to get them back to their original level is disactivating it,is there a way to get them back to their original level while having the mod enabled at the same time.

**Comment by Kazero21** [comment]
This has been answered before https://github.com/serpentiem/ddmk/issues/190#issuecomment-786903011

If you want to start in a new fresh walkthrough, I suggest you to play with DDMK 2.6 beta 2.
I don't remember having an issue with it besides M19 boss fight.

**Comment by cross1993** [comment]
> This has been answered before [#190 (comment)](https://github.com/serpentiem/ddmk/issues/190#issuecomment-786903011)
> 
> If you want to start in a new fresh walkthrough, I suggest you to play with DDMK 2.6 beta 2.
> I don't remember having an issue with it besides M19 boss fight.

it looks like the entire problem got solved by downgrading DDMK 2.6 beta 2, and i didn't even need to start a new walkthrough,i'm able to play with the style switcher with all the styles and weapons being on their original level,thanks.

**Comment by serpentiem** [comment]
Closing.
