### ISSUE TITLE
Ctrl+D not bringing up the menu for DMC3

### ISSUE THREAD

**Issue by DancingInTheDust** [serpentiem/ddmk#195]
Maybe I'm just being dumb but I followed all the steps on the wiki for installation, and whenever I press Ctrl+D no menu pops up, all that happens is my cursor gets moved on the main menu

**Comment by SteveCraft1** [comment]
Check the data folder of your game,inside of the folder dmc3,If there is a "Gdata.afs" then It's some other problem,If not then extract the nbz file on the same folder as the nbz file is,this can or not solve your issue

**Comment by SteveCraft1** [comment]
Also,check If your game created a logs folder to see If it's having some different issue

**Comment by SteveCraft1** [comment]
![Screenshot_20210314-135715.png](https://user-images.githubusercontent.com/73554591/111076932-365a9400-84cd-11eb-8c39-a52aa5c8f291.png)
This is How the dmc3 folder needs to be for ddmk to work

**Comment by DancingInTheDust** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/80639490/111077511-562e8f80-84ae-11eb-84b6-b250227e80ad.png)
![Screenshot_7](https://user-images.githubusercontent.com/80639490/111077512-56c72600-84ae-11eb-86fb-48a6bc914b25.png)

This is what my root directory and data folders look like

**Comment by SteveCraft1** [comment]
So your game is CODEX version?

**Comment by SteveCraft1** [comment]
Because If yes,then the problem might be that you haven't installed the CODEX update

**Comment by SteveCraft1** [comment]
For CODEX version,you also need to install the update too to make It work

**Comment by DancingInTheDust** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/80639490/111077588-b0c7eb80-84ae-11eb-9b0e-7e652e60c88c.png)

My data folder looks like this, and no logs folder was created in the root directory

**Comment by DancingInTheDust** [comment]
> 
> 
> So your game is CODEX version?

Do you know where i could find that update, and how to install it?

**Comment by DancingInTheDust** [comment]
Sorry for all the edits and deletions, genuinely

**Comment by SteveCraft1** [comment]
Then the problem is exactly that,you don't have the updated version of the game,you gonna need to find the CODEX update and install It on your game

**Comment by DancingInTheDust** [comment]
http://www.ovagamespc.com/devil-may-cry-hd-collection-update-1-codex.html

Would this be that update?

**Comment by DancingInTheDust** [comment]
Sorry if linking this broke any rules, I am very new here

**Comment by SteveCraft1** [comment]
Yup,If it's 500 MB or close to that then yes this is the update

**Comment by DancingInTheDust** [comment]
I appreciate the help, I'll let you know if this solves it

**Comment by SteveCraft1** [comment]
Alright,i Hope that this was your problem

**Comment by DancingInTheDust** [comment]
> 
> 
> Alright,i Hope that this was your problem

This did fix my issue, thank you for all the support

**Comment by SteveCraft1** [comment]
No problem
