### ISSUE TITLE
[Feature Request] Disable Camera Events, Cutscenes feature proposal.

### ISSUE THREAD

**Issue by GitHubro5** [serpentiem/ddmk#197]
Hello.

I am playing DMC4SE with DDMK2.5.

It would be more useful if upcoming DDMK (for HD Collection, 4SE, 5SE) has following features.

1. Disable Cutscene or Event Scene movies
For example, videos that appear before player start a mission or after end a mission.
However, I am not sure that feature implementation will be possible when it comes to real-time Cutscene events such as a Elevator event moving up and down with Orihalcon Fragment in DMC3SE Mission 7.

2. Disable Camera Events
For example, such as a event in which the player's camera point is directed to the portal (in the Bloody Palace) and a red/white hand auroras being broken after dealing with enemies in the area. (Also red auroras that occurs before forced combat in certain areas.)

Using these functions, the player does not have to press the skip button every time.

**Comment by serpentiem** [comment]
I added your request to #233. However, skipping in-game cutscenes is not feasible.
