### ISSUE TITLE
Dmc3 keeps crashing on me

### ISSUE THREAD

**Issue by AceDecimation** [serpentiem/ddmk#198]
I finished the game for the very first time with the latest version of ddmk, and it became crashy

It crashes upon multiple restarts, And crashes when I load saves even news ones I made when I reopen it, is there a way I could fix this problem? I tried deleting the game and reinstalling, same with the mod itself, I have no other mod install so saying that it might be a bug from another mod isn't really a possibility, Thank you in advanced

**Comment by serpentiem** [comment]
Interesting! When does it crash exactly? The moment you load a save?

**Comment by AceDecimation** [comment]
No, the first cutscene will play then the continue onto the "mission start" screen, When I press it the music will play for a second while the screen is black then proceeds to crash, I know for a fact that it isn't my pc since I tested it on another one and came with the same results, It also crashes when I restart a mission multiple times, Even in the middle of mission 3, If you'd like i can email you a screen recording to show it

Also as I stated, This problem only occurred when I first finished the game

**Comment by serpentiem** [comment]
> Also as I stated, This problem only occurred when I first finished the game

That's the interesting part. Can you please share your save file and the log files after the crash happens?

**Comment by AceDecimation** [comment]
> > Also as I stated, This problem only occurred when I first finished the game
> 
> That's the interesting part. Can you please share your save file and the log files after the crash happens?

I can, but can you direct me to where I can get the Files? cant seem to find them on my own

**Comment by SteveCraft1** [comment]
On your game directory, there's a folder named "logs" pick the dinput and Mary logs that are inside the folder

**Comment by AceDecimation** [comment]
> On your game directory, there's a folder named "logs" pick the dinput and Mary log

Thanks

**Comment by SteveCraft1** [comment]
I Just don't know where the save file is

**Comment by serpentiem** [comment]
You can find the save file in `C:\Program Files (x86)\Steam\userdata\__YOUR_STEAM_ID__\631510\remote`.

**Comment by serpentiem** [comment]
The `.sav` files in the `remote` directory.

**Comment by AceDecimation** [comment]
there isn't one

**Comment by serpentiem** [comment]
There are no files in the `remote` directory?

You're looking for:

* `options.sav`
* `dmc3.sav`

Maybe you got the steam id wrong. `C:\Program Files (x86)\Steam\userdata` contains multiple directories.

You can also try to search manually with Explorer.

**Comment by AceDecimation** [comment]
Ok I see them but they won't send due to the file type not being supported

I was confused earlier due to seeing the half-life logo on them

**Comment by AceDecimation** [comment]
![Screenshot (53)](https://user-images.githubusercontent.com/82496438/115426789-6cf59e00-a233-11eb-9a4a-a8471919d7d5.png)

**Comment by serpentiem** [comment]
Create a zip archive. Default Windows can do this. Select the files -> right click -> Send to -> Compressed (zipped) folder.

**Comment by AceDecimation** [comment]
[Uploading dmc3.zip…]()

**Comment by AceDecimation** [comment]
[dmc3.zip](https://github.com/serpentiem/ddmk/files/6344931/dmc3.zip)

**Comment by serpentiem** [comment]
Great! I'll take a look later.

**Comment by AceDecimation** [comment]
Thanks for the help ^^

**Comment by serpentiem** [comment]
I found the problem. You saved as Vergil in Dante's campaign; This way Vergil's weapon ids ended up in Dante's session data. Now every time the game tries to load Dante's weapons it has the wrong ids and crashes. I know what's causing this and will have a fix ready soon. Thanks for bringing this to my attention!

**Comment by AceDecimation** [comment]
Appreciate it!

**Comment by serpentiem** [comment]
I released [the update](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly9). Follow the instructions and you should be good to go.

**Comment by AceDecimation** [comment]
thank you!

**Comment by serpentiem** [comment]
I'd like to reproduce this. Which missions did you play and did you do something unique?

**Comment by AceDecimation** [comment]
well, it just happened now with mission 20(normal), it also happened on mission 1 and 2 previously, I discovered it since I was farming orbs back then

**Comment by serpentiem** [comment]
Can you record a video of it? If so, please make sure the Main Overlay is enabled and Region Data is checked.

![overlay](https://user-images.githubusercontent.com/38213025/115959247-92242e00-a50b-11eb-932c-a6985879d5f3.png)

**Comment by AceDecimation** [comment]
Do you have an email where I can send them? the video seems to be too big even when compressed

**Comment by serpentiem** [comment]
Try youtube, google drive or streamable.

**Comment by AceDecimation** [comment]
[logs.zip](https://github.com/serpentiem/ddmk/files/6369984/logs.zip)
[configs.zip](https://github.com/serpentiem/ddmk/files/6369986/configs.zip)

https://www.youtube.com/watch?v=mKrlhTbcljI&t=4s&ab_channel=aceDeci

**Comment by serpentiem** [comment]
Thanks, I got the files. You can delete the video now.

**Comment by serpentiem** [comment]
Yup, can reproduce ;D You're good at this. I'll take a look under the hood later...

**Comment by AceDecimation** [comment]
gee thanks, gl with your work btw

**Comment by serpentiem** [comment]
Try the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly10).

**Comment by AceDecimation** [comment]
Works great!, Tested it by retrying mission 1 a little over 10 times, And it didn't crash, Not even once

Thanks for fixing the bugs, Hope to support you in the future

**Comment by serpentiem** [comment]
Glad it works now!
