### ISSUE TITLE
GData.afs Does Not Generate (DMC HD Collection) [Did it work for DMC2?]

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#199]
Edit: Based on post below I was able to get the folder to generate running the latest nightly release vs. stable; but don't know if the patch was a success.

Also in DMC2 when I open the gui (DMC2) I get this for all the menu options:[https://i.imgur.com/GWaDNe4.png]( https://i.imgur.com/GWaDNe4.png)

Is the mod doing anything for DMC2, or did I not install it properly?

============================================

So I've been following these instructions to install DDMK: [https://github.com/serpentiem/ddmk/wiki/Installation-Instructions](https://github.com/serpentiem/ddmk/wiki/Installation-Instructions)

I've done everything up to Lauch DMC3 at least once, so I've launched it via steam and done 2 missions and saved; but the GData.afs folder does not appear. Here is what the folder structure looks for the game:
![LmG8ZcW](https://user-images.githubusercontent.com/7017110/115477996-255f1a00-a213-11eb-9aa2-6e746ac7e012.png)

The "afs" folder just has a single "sound" folder, so there are no pak files to patch there.

When I press ctrl+d the menu opens and shows the different mods; but I'm unable to do the patching part.

Please help me figure this out, thank you!

**Comment by marat569** [comment]
So I swapped from the latest release to the nightly release, and the folder generated.

When I ran patch.bat as admin, this is the output I got; so is everything good? [https://pastebin.com/s6RYDnN2](https://pastebin.com/s6RYDnN2)

**Comment by SteveCraft1** [comment]
DMC2 only have a FPS limiter and something that i forget,basically it's useless to have DDMK installed It unless that your game is running too fast

**Comment by marat569** [comment]
> DMC2 only have a FPS limiter and something that i forget,basically it's useless to have DDMK installed It unless that your game is running too fast

FPS limits are always good in games that rely on precision combos, considering many of them give you input issues after a certain FPS.

My question is well Ctrl+d in DMC2 gives me no options; so is the FPS limiter just on and the GUI not yet implimited?

Also what about the pastebin I posted, the results from the patch:  [https://pastebin.com/s6RYDnN2](https://pastebin.com/s6RYDnN2)

**Comment by SteveCraft1** [comment]
Did you have extracted all the files from xdelta3 and patch inside Gdata.afs?

**Comment by marat569** [comment]
> Did you have extracted all the files from xdelta3 and patch inside Gdata.afs before running?

Yep extracted everything from both the archives, then opened cmd as admin, followed by running patch.bat; the output is in the pastebin

**Comment by SteveCraft1** [comment]
![Devil May Cry HD Collection 21_04_2021 01_55_06](https://user-images.githubusercontent.com/73554591/115498871-b00c3d00-a244-11eb-9ff1-6008b716afa5.png)
What version of DDMK you have to not only have System option?

**Comment by SteveCraft1** [comment]
when you runned the patch.bat,did it have disappeared from Gdata.afs?

**Comment by marat569** [comment]
> when you runned the patch.bat,did it have disappeared from Gdata.afs?

yep

**Comment by SteveCraft1** [comment]
demo_pl000_00_3.pac was created after that or it already existed inside Gdata.afs?

**Comment by marat569** [comment]
> demo_pl000_00_3.pac was created after that or it already existed inside Gdata.afs?

so: demo_pl0000_00_3.pac was never edited (created around 8pm today when I installed the nightly build)

Here is more terminal output as admin time time (normal user has the same results) -- the file does not get touched and patch throws an error asking for a -f flag

[https://i.imgur.com/MDaAOeX.png](https://i.imgur.com/MDaAOeX.png)

**Comment by SteveCraft1** [comment]
from what i remember on 2.6 version,demo_pl000_00_3.pac is a file for quick drive,i just don't found anything that need demo_pl000_00_3.pac in version 2.7(nightly),also Xdelta3 and Patch.bat is for DMC3,it's also not necessary to use it to play any DMC  from HD Collection with DDMK

**Comment by marat569** [comment]
btw incase it's important, I'm running "DDMK 2.7 Mary Nightly 18 April 2021"

Extracted all the .dll files into S:\steam\steamapps\common\Devil May Cry HD Collection

Did a mission or two of both DMC3 and DMC2 on clean saves for the directory to be generated (Gdata.afs)

Went to apply the patch found in the guide and get that error thrown. Also DMC2 has no GUI in either 2.6 or 2.7 (ctrl+d opens the option menu, but it just says like gui_system etc, like in an image above)

I invested so much time into this, I'd like to see it through if you're willing to help!

**Comment by marat569** [comment]
so here is a small update: I downgraded to the latest version of 2.6 (beta2 hotfix)

good news: DMC2 has the frame limiter now
bad news: DMC3 patcher is still throwing the same error/doing the same thing :c 

Honestly if it's just patching files, can you just zip up your folder? My discord is Marat#0001

**Comment by SteveCraft1** [comment]
Do you can press System option? Because it's suppossed to be the only option in DMC2 DDMK

**Comment by marat569** [comment]
> Do you can press System option? Because it's suppossed to be the only option in DMC2 DDMK

Now with 2.6 there is only one option; system with the frame limiter. in 2.7 and 2.5 I had iirc 4-5 categories that where empty.

Even though DMC2 is set, if you don't mind I'd love getting DMC3 working

**Comment by SteveCraft1** [comment]
what is the problem that DMC3 have?

**Comment by marat569** [comment]
> what is the problem that DMC3 have?

the patcher just refuses to do anything.

**Comment by SteveCraft1** [comment]
i managed to make patch.bat work

**Comment by SteveCraft1** [comment]
just run it without administrator permission

**Comment by SteveCraft1** [comment]
after that the patch and xdelta will disappear and demo_pl000_00_3.pac will be created

**Comment by marat569** [comment]
> just run it without administrator permission

I've done both, but I will delete my current demo_pl000_00_3.pac the game created and try it out to see what the patcher makes

**Comment by SteveCraft1** [comment]
about the patcher,it was never necessary to use it to make DMC3 work,the necessary was only GData.afs in dmc3 folder(which you can extract the folder from dmc3.nbz file) and Mary.dll and dinput8.dll in the game directory(where dmc3.exe is)

**Comment by SteveCraft1** [comment]
the instalation instructions in wiki is quite old and never mention so clear about what patcher do and if it's really necessary to use it

**Comment by marat569** [comment]
> about the patcher,it was never necessary to use it to make DMC3 work,the necessary was only GData.afs in dmc3 folder(which you can extract the folder from dmc3.nbz file) and Mary.dll and dinput8.dll in the game directory(where dmc3.exe is)

so this whole time I thought we where patching demo_pl000_00_3.pac; not creating it.

I deleted my old demo_pl000_00_3.pac, and re-ran the patcher and it well created a new one; so case closed I guess!

It seems the newer version (nightly) just generated it without the patch.

Thank you so much! And I guess I can close this issue now!

**Comment by SteveCraft1** [comment]
no problem,i hope that you have a lot of fun playing DMC3 with DDMK
