### ISSUE TITLE
Feature Request: Ebony and Ivory cancel enemy Knockback

### ISSUE THREAD

**Issue by Zaphero1** [serpentiem/ddmk#200]
This is something that people have been implementing outside via cheat engine. (File saved as a .txt file to upload but was a .CT file)
[KnockbackCancelHDC.txt](https://github.com/serpentiem/ddmk/files/6396057/KnockbackCancelHDC.txt)

And it's really neat, allowing you to keep up combos better after higher knockback attacks if you can just jump cancel the attack and shoot in time. It'd be really cool to see it implemented into DDMK if it can be!

For an example nelo47angelo uses this for their videos.
https://www.youtube.com/watch?v=VygvOWBwBrI

**Comment by serpentiem** [comment]
Insane gameplay. Added to #233.
