### ISSUE TITLE
I think I broke the game 

### ISSUE THREAD

**Issue by Tsunemakano** [serpentiem/ddmk#201]
I don't know what happen with my game even I install or uninstall the DDMK 2.6 beta 2. When I was loading the save that I play Dante, I try to select the stage then the 20 stage that I already play are gone down to stage 12 instead, when I try to play it the game crash. This also happen when I go to customize the weapon, the weapon section are turn messed up then the game crash. Anyone know what's happen? and is there anyway to fix them?

**Comment by serpentiem** [comment]
Try the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If the problem persists, please open a new issue.
