### ISSUE TITLE
[DMC2] Suggestions to make this mod a DMC2 Staple!

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#203]
So there is a popular video out there, "How REAL MEN play DMC2" -- [https://www.youtube.com/watch?v=jiroi9GAcqU](https://www.youtube.com/watch?v=jiroi9GAcqU)

Basically it's him opening cheat engine and enabling these 3 cheats:

```
Swap Guns While Attacking

Bad Dpad Amulet Switching

Player Only Turbo (recommended value of 1.4)
```

With those on, the game really does feel much better; especially for sword play. 

Since you already got DDKP injected into DMC2, why not also make it the definitive DMC2 mod as well as 3! The cheat table is public, 

I'll even attach it here so you can browse the code if need be. 

[siyan_dmc2_2.zip](https://github.com/serpentiem/ddmk/files/6402606/siyan_dmc2_2.zip)

(Had to zip the .ct since github did not allow uploading files with the .ct extension)

Thank you!

**Comment by serpentiem** [comment]
Merged into #233.
