### ISSUE TITLE
Need clarity on spawning enemies and the arcade option for bloody palace

### ISSUE THREAD

**Issue by nrohit92** [serpentiem/ddmk#204]
Hi, I am using the February version of the DDMK style switcher mod (Ver 2.7) and I have few queries regarding some of the functionalities. 

1) How to spawn DT'ed enemies in an area? (Does the variant option under enemy give us the option) 

2) Under the arcade option, we have the option to directly go to any of the flloors in the bloody palace. But when I directly go to the 10th floor, it does not spawn the tougher DT'ed enemies and instead spawns normal enemies (that too of lower difficulty). Moreover, the floor is shown as 100 (not 9000). Anyway to directly get to floor 9000 through the mod?

3) Does the mod have the legendary dark knight mode ? Is there any way to increase the enemy count in an area?

**Comment by serpentiem** [comment]
1. An instant berserk option is not available.
2. I added the ability to set the Bloody Palace level in Arcade mode to #233.
3. No, but you can auto-spawn up to 30 additional enemies with the Enemy module. Should be enough ;D
