### ISSUE TITLE
[ DMC1 ] Mission cutscenes fail to load, causing missions to be unplayable

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#206]
Edit3: I see this is a known bug, sorry for the spam. But the other issues did not have logs attached, so maybe this will help!

Would it be possible to just have Eva.dll be blank until it's fixed, so I can keep DDMK installed for 3 and not have to mess around when I want to play 1/2?

Running: ddmk_2.6_beta2 + ddmk_2.7_mary_nightly_26_april_2021

Logs:
 dinput8.txt: [https://pastebin.com/u9qSRL7B](https://pastebin.com/u9qSRL7B)

Eva.txt [https://pastebin.com/xjKJ9epm](https://pastebin.com/xjKJ9epm)

So this happened before in mission 3, and now mission 10. When I start the mission, the cutscene does not start and the player is in a weird position.

Here is an example picture of what happens; you can see dante running in the water [https://i.imgur.com/GcEgdqo.jpg](https://i.imgur.com/GcEgdqo.jpg)

This makes playing DMC1 with DDMK unplayable; causing me to constantly rename dinput8.dll when I want to swap games.

Just figured I'd post this issue. Thank you!

Edit: For the sake of testing, again renamed dinput8.dll to dinput8.dll_off -- and the mission starts properly with a few seconds of Dante running up the side of a cliff

Edit2: Tried using all the .dlls from DDMK 2.5 (Latest/Stable) -- Same issue

**Comment by jesuscc1993** [comment]
I'm experiencing the same issue; I had to disable the mod in order to be able to start mission 3.

**Comment by marat569** [comment]
> I'm experiencing the same issue; I had to disable the mod in order to be able to start mission 3.

Just delete/rename Eva.dll and you don't have to disable the mod for DMC2/3 and can play 1 just fine!

**Comment by serpentiem** [comment]
Try again with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15).
