### ISSUE TITLE
[ DMC3 - Suggestion ] Style Change Ques

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#207]
So I'm falling more and more in love with this mod by the day.

I don't know how hard it would be to implement, but based on the code the base framework seems to be there.

The suggestion would be to add some sort of prompt system to know when you change styles.

Here are two options I've thought of:

1) Audio prompts. Good ole trick/sword/gun/trick/sword/gun from DMC4/5 -- you can probably rip the audio bits from those games aswell

2) Visual prompts. One of my favorite DMC5 mods has this cool style display above the character when you swap, so that could be done as well. Here is the mod's page for a better idea: Video: [https://streamable.com/9b1b3o](https://streamable.com/9b1b3o) -- Nexus Page: [https://www.nexusmods.com/devilmaycry5/mods/701](https://www.nexusmods.com/devilmaycry5/mods/701)

I know you probably have a lot to work on, but if you're ever bored and want to add a cool feature; here is one!

Thanks again!

**Comment by serpentiem** [comment]
Merged into #233.
