### ISSUE TITLE
[ BUG DMC3 ] DDMK themed shop at idol stole 2 purple orbs

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#208]
Mary.dll log:  [https://pastebin.com/77SAk39P](https://pastebin.com/77SAk39P)

Version: DDMK 2.7 Mary Nightly 26 April 2021

So what happened is I went up to the goddess idol (shop) mid mission, bought 2 purple orbs -- but Dante's number of DT did not update. 

I went to the real shop in-between missions, and it said I own 2 purple orbs. I buy one from the real shop, and my max DT is increased only by one, while I apparently "own" 3 orbs. (2 DDMK shop, 1 real shop)

Is there any way to fix my character, and if so please share!

**Comment by marat569** [comment]
Update: I replayed up to the mission I was on; so no need to fix anything on my end.

But please either disable the shop, or add a way to change the player's maximum HP and DT bar (not just the value, but the container visuals)

**Comment by Zhnigo** [comment]
Can confirm, I've got the same problem.

**Comment by marat569** [comment]
Yea just buy orbs from the "official" shop between missions. Do not use the gold statues for now

**Comment by SteveCraft1** [comment]
> Update: I replayed up to the mission I was on; so no need to fix anything on my end.
> 
> But please either disable the shop, or add a way to change the player's maximum HP and DT bar (not just the value, but the container visuals)

There is actually one way but it's probably not one you gonna like it(especially if you want to keep your original stuff),use arcade mode and specify how much of health and Devil Trigger you want

**Comment by marat569** [comment]
> > Update: I replayed up to the mission I was on; so no need to fix anything on my end.
> > But please either disable the shop, or add a way to change the player's maximum HP and DT bar (not just the value, but the container visuals)
> 
> There is actually one way but it's probably not one you gonna like it(especially if you want to keep your original stuff),use arcade mode and specify how much of health and Devil Trigger you want

I tried with the bugged save long ago, didn't really work (or I didn't set it right)

Either way I long since started a new save file; and only bought orbs in-between missions where it's safe. 

Still good info for others with bugged save files.

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If not, please open a new issue.
