### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by TheYellowArchitect** [serpentiem/ddmk#209]
I want to download the latest nightly version https://github.com/serpentiem/ddmk/releases/tag/2.7nightly11
But 970 kb seems weird. Mary.dll is only 913 KB, and I am not sure if I downloaded the correct file.

I am a newbie on DmC3 btw, but I want to try it out with this mod, as it makes the game more than a shitty port
Any help is appreciated :)

**Comment by TheYellowArchitect** [comment]
I found the installation instructions on the github wiki
I used it on DmC3 special edition on Steam, ctrl+D doesn't open the menu. I even used the old style switcher, but ctrl+D doesn't do anything

I used this on DmC HD Collection [FitGirl] and it crashes the game.
@serpentiem I thank you very much for making this, and improving what I'm sure will be an amazing game, but could you post the latest installation instructions for all versions? Preferably on the README.md, because I see you are working on this for years, yet, it's so hard to use it, and so, that work gets wasted feelsbadman (because most people don't even have github, and even less will open an issue when they fail to install it)

**Comment by SteveCraft1** [comment]
Put the Dll files on the same directory as DMC3.exe is(you need HD Collection for that[if you're playing a pirate version,you gonna need to download a update too to make it not crash])

**Comment by SteveCraft1** [comment]
Check on data/dmc3 if there's a GData.afs folder,it needs to be there to make it work,if no GData.afs folder appear,extract the dmc3-0.nbz file because it's where GData.afs folder is,you need to extract it inside dmc3 folder

**Comment by ChronoCX** [comment]
What update do i need to make it not crash? I have the game pirated, and every time I boot up dmc3 it crashes

**Comment by SteveCraft1** [comment]
I don't know what Pirate version you have but the only update Pirate version i found was CODEX version https://drive.google.com/file/d/1V1kjge5a1-Aw4O28IrR6laZN0gRhMF3F/view?usp=drivesdk
