### ISSUE TITLE
[ CRITICAL BUG - DMC3] Game crashes dying to Cerberus (M3 + M18)

### ISSUE THREAD

**Issue by marat569** [serpentiem/ddmk#210]
Version: DDMK 2.7 Mary Nightly 26 April 2021

dinput8.txt: [https://pastebin.com/0dGDwFBn](https://pastebin.com/0dGDwFBn)

mary.txt [https://pastebin.com/JgyrQwCt](https://pastebin.com/JgyrQwCt)

How to replicate the bug: Just start mission 3 or 18, and die to Cerberus. Game should just quit/crash out, no error or anything.

Every time I tried to replicate it, it would always crash. So feel free to just load up DMC3, start mission 3 or 18, and die to Cerberus. Every death will result in an abrupt crash. 

So far it seems only Cerberus causes a crash when you die to him.

I'll upload my save file incase that helps with anything. I also have VODs of all the crashes from my playthrough if that helps with anything.

Save: 
[Save bkp 052421 for github.zip](https://github.com/serpentiem/ddmk/files/6530583/Save.bkp.052421.for.github.zip)

Update: Tried to replicate this on  Mission 3, Easy and Hard; no crash -- seems to be tied to normal

Update 2: Crashed on M3 hard dying to cerb, this time the attack he used was the ice bean out of his his mouth when he was near death.

Please look into this, thank you!

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If not, please open a new issue.
