### ISSUE TITLE
Questions + Limiting mod to exclusively adding style and weapon switching?

### ISSUE THREAD

**Issue by Proutbedaine** [serpentiem/ddmk#213]
I have some questions that I've been trying to look around as much as I can to find answers but I just can't so I'd love it if anyone or Serp himself could answer ^^". 

So it's my first time installing this mod (using it with DMC3 HD with the latest release on your GitHub from the 26th) and trying it out and I right away noticed that as soon as I enabled the Actor Module that it unlocked every move from both styles and weapons? Is that normal?

Also I tried the Repair section and reset values for both options but it seems that it only reset the guns wtv I did? The guns went all down to lvl1 and the weapons had the same moves purchased as I had in my current playthrough so far. (I just finished mission 18). Does the other weapon reset supposed to do something else? And if so, what exactly? 😮

I did a backup of my saves and etc so no worries there. But yeah essentially I kept thinking about the Switch version that added the weapon switch feature and style switch feature and I REALLY wanted to have it on PC. But that's it, I don't wanna change anything else. I still would really love to progressively unlock everything like you normally would (by buying the upgrades/actions with orbs and unlocking style levels) and only have weapons and style switching (mayyybe would keep Air Hike added for Nevan hahaha). And without the added moves also (like Air Stinger for exemple or the Quick Drive with the stick to the left ir wtv). Is there any way to do that? If so, then really sorry about that I really tried to figure it out by myself ^^". And if not right now; would it be a possibility to add a way to do that? I just hope that if you do want to look into it that it won't be too much trouble éwè. You've already obviously worked so hard on everything and you did amazing work regarding what's possible so far. I'm thoroughly impressed! 

Also what is the difference between Linear and Arbitrary weapon selection or etc? I switched between both and switched weapons spots in the list and etc, and didn't seem to change anything wether I held the trigger, or the Back button, or went through the whole selection o.o

Also, can't remember if Ebony&Ivory + Shotgun charging was a thing outside of Gunslinger Style or not ewe". Like, should you be able to use it normally if you weren't in Gunslinger mode?

Also, smoll question, why are those release called "Mary Nightly"? o.o I'm just really curious of the meaning behind the "Nightly" part, where as the reason behind Mary is obvious since it's update to only DMC3 features from that dll.

Thanks in advance for reading all of that and working so hard on making one of the best games of all time even better for all of us ><. I just wish I had the financial means to support you on Patreon right now because you deserve it so much ;w;

**Comment by SteveCraft1** [comment]
About actor module,i think that it's to prevent glitches and bugs,so It always force It to level 3 styles
i don't know about weapon reset because i never wanted to play from New game again
weapon switcher from switch style is already possible,it's in actor module,it's called arbitrary,only player 1 can use it,(on Dante section,you can use core abillity to force Air hike for all weapons)
Air stinger can be deactivated by setting 0 on dante's section,i don't know If removing Quick drive is possible
Linear is like DMC4 and 5 weapon switcher,Arbitrary is from switch version,you need to hold the button and use your right stick to choose the weapons
E&I,Shotgun charging out of gunslinger is from DDMK itself
i think that nightly is a name for releases that aren't considered fully stable(check releases and you will see that the lastest is 2.5),i might be wrong though

**Comment by Proutbedaine** [comment]
> About actor module,i think that it's to prevent glitches and bugs,so It always force It to level 3 styles
Aw oki. So I presume there is no way to rectify that on my own right now and I also presume it'd be a lot of trouble to make all the weapon switching and style switching work without affecting any upgrade progressions :T. I wonder what Serp has to say about this because it'd be awesome for those that only want to be able to have all the switching features and nothing else like me. But I understand if it's too much trouble and/or really not a priority/of interest to him. éwè

> i don't know about weapon reset because I never wanted to play from New game again
Ye that was just something I noticed and thought maybe it'd revert things back and solve the issue I had with the mod but I get that haha. It was a less important question anyway. The reason I wanna keep progression intact is that I don't wanna feel like I'm cheating (The only feature I may use that isn't in any version is the Air Hike with Nevan through enabling it as a Core Ability because using Nevan without it is a pain. Dunno what they thought by not making it available for it. Maybe just because it has Air Raid when in Devil Form? But that's still so limiting lol) and also even if I played og DMC3:DA on PS2 (I suffered as a kid, don't know how I did it on Normal back then on my first playthrough ever lmao) and played the DMC HD initially on 360 and now just finished my first playthrough on PC of the DMC3SE from HDC. And throughout all of that I never did unlock everything and every move and styles, so I want to at least do it legit once in my lifetime you know ^^". But I'll wait for a solution that'll allow me to Switch weapons and Styles only, first.

> weapon switcher from switch style is already possible,it's in actor module,it's called arbitrary,only player 1 can use it,(on Dante section,you can use core abillity to force Air hike for all weapons)
Yeye I know all of that and made it work :0

> Air stinger can be deactivated by setting 0 on dante's section,i don't know If removing Quick drive is possible
Yup I figured that one out too! And poop, I hoped we could. Not only it's not there originally but also it's not that hard to hit it by accident so it can become inconvenient ^^".

> Linear is like DMC4 and 5 weapon switcher,Arbitrary is from switch version,you need to hold the button and use your right stick to choose the weapons
Ohhh oki yeah I figured it'd be like that but it wouldn't work at all. How do you make it work normally? Do I have to activate something else than just putting it in Arbitrary mode? Also noticed there was an image folder that came with the update that's clearly for that as placeholders for people to put in their own art or etc (for obvious reasons). Where do I have to put that folder? The root folder? Also do you know where I could get the proper images to replace them? :0

> E&I,Shotgun charging out of gunslinger is from DDMK itself
Ah oki i thought so haha. Bummer, I imagine we can't deactivate that too then huh? :T

> i think that nightly is a name for releases that aren't considered fully stable(check releases and you will see that the lastest is 2.5),i might be wrong though
Ah oki yeah that's what made the most sense to me too but I was just very curious if it was something else hehe.
Is there any versions that would work in the way that I want it too or closer to it that any of you guys know of? That doesn't have features that I mentioned that I don't want or etc?

**Comment by SteveCraft1** [comment]
i remembered now,you need to go to Textures and on Targets(there's 2)you put the resolution you're playing with and it will resize it to the size your resolution is at moment

**Comment by SteveCraft1** [comment]
there's 2.6 which don't force Styles level or any weapon(if you don't use weapon switcher at all) to endgame level,just know that Mission 19's second boss phase will crash the game no matter how much you try. it's the best you can have to be able to use style switcher with the levels you have at moment without forcing it to level 3.

**Comment by Proutbedaine** [comment]
> i remembered now,you need to go to Textures and on Targets(there's 2)you put the resolution you're playing with and it will resize it to the size your resolution is at moment

Ah that is good to know, thanks! But what about the image folder? Do I put it in the root directory of the game where we also put the initial dll? Or somewhere else?

>there's 2.6 which don't force Styles level or any weapon(if you don't use weapon switcher at all) to endgame level,just know that Mission 19's second boss phase will crash the game no matter how much you try. it's the best you can have to be able to use style switcher with the levels you have at moment without forcing it to level 3.

Oh oki that's interesting. So I sadly wouldn't have the weapon switching features but I would have the style switching feature without them being forced to max levels if I understand correctly. That could be a good option in the meantime, I'd at least have that. And would just have to deactivate it when I get to mission 19 only (thanks for the heads up hahaha). And now I wonder if the experience you get form using a style will only go to the one selected in the menu of the shops/etc or if it will actually consider the current style used at all times when you switch them haha.

**Comment by SteveCraft1** [comment]
What i meant is that weapon switcher exist,but It will force weapons that you didn't unlocked yet If you don't change It,the exp will Go to the style you're using at momento you kill the enemy with style switcher enable
Ex:you choosed swordmaster on mission menu,but If you kill a enemy with trickster selected,the exp will Go directly to trickster instead,the folder need to be in same place as the Dll files for the mod to use It for arbitrary

**Comment by Proutbedaine** [comment]
> What i meant is that weapon switcher exist,but It will force weapons that you didn't unlocked yet If you don't change It,the exp will Go to the style you're using at momento you kill the enemy with style switcher enable
> Ex:you choosed swordmaster on mission menu,but If you kill a enemy with trickster selected,the exp will Go directly to trickster instead,the folder need to be in same place as the Dll files for the mod to use It for arbitrary

Oh great! So 2.6 does have weapon switcher in it but you're just warning me about the fact that I'll have access to all  the weapons right away even if I didn't unlock them yet if I understand correctly? If so, it's not an issue since like I said I finished a playthrough and found everything so that's good. 

But will it unlock every buyable actions/upgrades for every weapons from the shop or will they stay as they were and I'll still be able to unlock them myself normally?

And perfect, I love that the exp goes to the style you are currently using which makes total sense but I figured there might be a case where the pointer to where the exp is attributed stays on the last style selected in the menus and that wasn't reworked to make more sense as it does already anyway. So yeah that's perfect haha :)

Welp since PSO2 is in maintenance this is a perfect time to go test out that build and see if it works exactly the way I want it too! ^^

**Comment by Proutbedaine** [comment]
I just tested it out and it is NEARLY perfect for what I want out of it! :D
Thank you so much for giving me the info on this and obviously to Serpentiem for working so hard on these.

The only things that bothers me is:
- that the UI of the mod menus aren't adapted to my screen well. I use a 55" 4k TV and the UI size is good BUT to interact with it in any way I have to guess where my "actual" cursor is because where I point with my cursor does not point at the same place within the UI :T. But it is manageable though, just annoying and a bit more time consuming to navigate xD. 
- That the devil form doesn't update according to the weapon and you have to choose one that's always going to show up during the mission.
- Sadly in that version it doesn't seem to have the arbitrary selection with the radial menu, but it's a sacrifice I don't mind making for now. 
- Also Mission 19, as I have been informed, still crashes the game at it's second part of the fight which is also a sacrifice that doesn't bother me too much. 

Side note: First time I tried it out I went in mission 18 cuz it has a nice area to test out moves and stuff and as soon as the stage started I walked a bit then held the lock-on button to show my health bar and see my style change as I was going to try them out and see if everything worked properly and as soon as I pressed up on the D-pad the game froze and crashed (CTD) xD. But after that when I booted it up again and did the same thing it worked perfectly fine.

But yeah it's almost perfect other than that! Everything is actually still modular in that one! Nothing is forced on you at all if you activate the Dante module. And I can just turn on Style and Weapon switching (no character switching), Air Hike as a core ability so that Nevan can use it too, Auto-skip cutscenes and that's it!!! No maxed out styles or any weapon actions unlocked without you having unlocked them yourself. No new moves added and Character Switching forced on all the time as soon as you activate the whole actor module. I love it! 

@serpentiem thank you so SO much again for making all of this possible. If it's not too much of an headache and/or if it's something you wouldn't mind working on making possibly one day; having the option to only enable those things individually or disable the things you don't want when activating the Actor Module in the latest version would be spectacular. But I 100% understand if you are not interested and/or if it'd be too much work and etc.

**Comment by Proutbedaine** [comment]
Oh! I have a question. 

Is there any way known to play any of those games in Native 4K or even 2K (which is even better for me since my TV can do 120fps but exclusively in 2K for some reason and not even in 1080p lol)?

And if yes, then if I play the game in 120 fps, will it break the game in some ways? And if so, in what ways? Is it actually able to play in 120fps at all?

**Comment by SteveCraft1** [comment]
i don't know because my laptop can't handle more than 800 x 600 resolution

**Comment by Proutbedaine** [comment]
Oh oki :o

**Comment by Proutbedaine** [comment]
@serpentiem Just saw that the new moves are optional now! That's awesome! Thank you for going in a direction where we have more options! I don't know if my posts influenced your decision or not but I'm just glad to see that honestly :)

**Comment by Proutbedaine** [comment]
Here's my personal list of things that should be optional (but don't get me wrong, I am in no way feeling entitled to them whatsoever! Just suggestions!):

- Make it optional to have styles maxed out of not when you activate the actor module (to get style switching)
- Make it optional to have all moves unlocked for all the devil arms when you activate the actor module (to get weapon switching)
- Make it optional that Ebony & Ivory and the Shotgun shot charging is available outside of gunslinger mode.

By making those optional, if I'm not forgetting anything, should make it possible for us to simply be exactly on par with the Switch version of the game (basically just having the style and weapon switching features) without having any advantages over it if we so choose to have that kind of experience! ^^

Or of course, simply make our experience closer to exactly wtv we want out of the mod! x)

Let me know what you think @serpentiem and if anyone else would be interested in having those options too! 
Would it be too much work? Is it feasible? Are you interested at all in implementing it in the first place? :0
I'd just love your opinion on it pls c:

**Comment by serpentiem** [comment]
I don't have the resources to read all that so I'll read your first and last comment and then answer your questions.

> I'm thoroughly impressed!

Thank you!

> and I right away noticed that as soon as I enabled the Actor Module that it unlocked every move from both styles and weapons? Is that normal?

That's normal. It's required to set the expertise to max, otherwise characters will unexpectedly lose access to moves. I thoroughly thought about everything that is required to fix this and it's not feasible. It's a fuckton of work and will have nontrivial repercussions. This question pops up every now and then. I'll make sure to add it to the wiki.

> Does the other weapon reset supposed to do something else? And if so, what exactly?

It resets your selected weapons to the default ones.

> Also what is the difference between Linear and Arbitrary weapon selection or etc?

Linear is the default, where you use the triggers to switch weapons and by holding back while switching you go back instead of forward. Arbitrary allows you to select weapons with the sticks.

> Also, can't remember if Ebony&Ivory + Shotgun charging was a thing outside of Gunslinger Style or not ewe".

It's not.

> Also, smoll question, why are those release called "Mary Nightly"?

They're my nightly builds. Even if weeks are between releases, it's basically just the accumulation of the nightly builds.

> Thanks in advance for reading all of that and working so hard on making one of the best games of all time even better for all of us

You're welcome!

I think the above also mostly answers your last comment except for making Charged Shot outside Gunslinger optional. I like the current design and will not make it optional.

Cheers!
