### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SteveCraft1** [serpentiem/ddmk#214]
1. Maybe in the Future there's gonna be something that show the other players's health like number or even the health bar? It would be nice to not guess How much each player have

2. Any chance that on Future,Arkham second Boss phase can be played on multiplayer again?

**Comment by serpentiem** [comment]
> 1. Maybe in the Future there's gonna be something that show the other players's health like number or even the health bar? It would be nice to not guess How much each player have

Added in [the latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15), but you already know that ;D

> 2. Any chance that on Future,Arkham second Boss phase can be played on multiplayer again?

Unlikely. It's quite problematic.
