### ISSUE TITLE
Will Devil May Cry 3 work in style switching if its crack?

### ISSUE THREAD

**Issue by johnrey172** [serpentiem/ddmk#215]
And if i delete my mary and dinput8 it will work.

[dinput8.txt](https://github.com/serpentiem/ddmk/files/6758125/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6758126/Mary.txt)

**Comment by SteveCraft1** [comment]
here's a couple questions
Did you downloaded a codex update and updated your DMC Hd Collection?
data/dmc3 need to have a folder named GData.afs,if you already updated and the folder don't exist,extract dmc3-0.nbz file in there
these are normally the problems that most people get so i hope yours is one of them

**Comment by johnrey172** [comment]
No i dont have an update i just install it on firgirl repack..


I saw a youtube. that he extract copy a file from dmc3-0.nbz he extracted (( pl000.pac to pl000_00_31.pac )) and create a folder name MOT and put it there. still didnt work though..



Question:
Do i need the update? 
if so
ill just download the update first then ill do what you said and update you later..

Is there anyway to put style switcher without any update?

I'll put some pictures just in case it might help


![image](https://user-images.githubusercontent.com/86873199/124358809-8dd76800-dc54-11eb-8438-6947eb17a3d6.png)

![image](https://user-images.githubusercontent.com/86873199/124358840-b7908f00-dc54-11eb-828d-0c594f61e074.png)


![image](https://user-images.githubusercontent.com/86873199/124358814-9891fd00-dc54-11eb-9029-14af4f6d7369.png)

**Comment by SteveCraft1** [comment]
MOT Folder? it seems that you're watching a pretty old tutorial for a old version because it's not necessary to create a MOT Folder
also i could notice that you're using a older version of DDMK(maybe 2.5/26 or older),because the lastest version have a images folder and it's also dated on 30/6/2021,try running the game without the update,if it still crash then download the update

**Comment by johnrey172** [comment]
It still crash.... ok ok ill update it ill be back maybe 3 or 4 days depending on my internet

**Comment by johnrey172** [comment]
thanks for nothing

**Comment by johnrey172** [comment]
WoW!!! Boi it worked thanks for the help. i dont know if it work for fitgirl because i deleted it and i just download DMC HDC again but in codex.. i've been struggling for 1 year then give up then try again after 1 year  finally found the solution thanks to you :D

for anyone wondering where i download dmc its here below:

https://gamepciso.net/devil-may-cry-hd-collection-download-free/

ill try to make youtube for this cause ALL OF THEM didnt work

if anyone is reading this and still dont get it like boommer like me... ill just give you a step by step


1. Download and install DMC HD Collection above or any other site 
2. Download Mod here ↓↓↓ ... pick (ddmk_2.6_beta2_hotfix.zip) 

https://github.com/serpentiem/ddmk/releases/tag/2.6-Beta2

i just give the old Mod cause it worked for me.. i didnt test the latest cause i dont know if it will crash but if you want the latest MOD click here ↓

https://github.com/serpentiem/ddmk/releases/

3. now follow these steps ↓
https://github.com/serpentiem/ddmk/wiki/Installation-Instructions

if you press xdelta3 it will go to another site and ask for password the password will be given at the right end
example:  (Enter this password 1de49056)  put this 1de49056

If you didnt found the GData.afs after you open the game just extract the dmc3-0 in
Devil May Cry HD Collection\data\dmc3

![image](https://user-images.githubusercontent.com/86873199/124477299-76c08380-ddd6-11eb-94a8-f6cc46f1d6ca.png)

now your good to go

just press ( Control + D )

**Comment by SteveCraft1** [comment]
xdelta3's real use was to create a file to allow you to use Quick drive move,it's only useful for 2.6 and 2.5 versions since 2.7 don't need It anymore,this way you teached is the same for 2.7 version too(except xdelta3)

**Comment by SteveCraft1** [comment]
you're welcome

**Comment by johnrey172** [comment]
yahh!! Thank you so much forgot to close this issue. i just saw this notif on gmail i rarely use... again thanks :)
