### ISSUE TITLE
Possibility of further customizing style switching buttons

### ISSUE THREAD

**Issue by RobertoCastro446** [serpentiem/ddmk#218]
First of all, thank you very much for the awesome mod you've created, your work is truly incredible and has greatly improved the game. There's one somewhat recent change to the mod that has been bugging me though, and I think it would be great to be able to have more options in that regard. I'm talking about the input for switching to the Doppelganger and Quicksilver styles. Based on what I heard one of those used to be assigned to L3 + R3 (the other one I'm not sure), but now they were changed so that every style is changed with the arrows, with the possibility of assigning 2 different styles to the same arrow, with the secondary one being activated if the first one was already selected, similar to how it works in the Switch version. Usually I'd consider that preferable to the old input method, but I also use Steam Input to remap a lot of stuff in this game and I even managed to make it so that I can change to a style and use it with a single button press. Saddly though the current setup where two of the arrows have to change to two different styles in order to have them all available doesn't really work well with this config, as I have one of the arrows + the b button set to the same button for each of the styles, meaning that whenever I use a style action the corresponding style's arrow is pressed again even though it's already selected. What that means is that if I have for example Trickster on the up arrow and Quicksilver also on the same arrow (as that arrow's secondary style) I'll end up switching between the two styles when I only really want to use one of them. I realize that's probably a niche issue, since I believe most people wouldn't bother trying to configure the controller the way I did with Steam, but if possible I'd really apreciate it if you could also make the old style of input available for style switching, where pressing two buttons at the same time was used for the extra styles. Even if most won't have the same issue as I have I believe it would still be cool to have more options like that, specially for those that may already have gotten used to the old style switching input. Either way, thanks again for your amazing work. What you are doing here is truly remarkable.

**Comment by serpentiem** [comment]
Denied. I will not change the style switch controller. Your setup will still mostly work if you set both slots to the same style.
