### ISSUE TITLE
Dmc Hd collection ddmk 

### ISSUE THREAD

**Issue by VergilDarkSouls** [serpentiem/ddmk#221]
Hello, I have issue when I play as vergil with dante swords, vergil sounds like dante and I loaded a vergil save pls help.

**Comment by SteveCraft1** [comment]
Can you specify which Character are you using? This Vergil with Dante sword means that you're using "Force Files" to change Dante to have Vergil's model?
If yes,then It's not a issue,force files just change dante's model to Vergil,It won't change the sounds for Vergil too

**Comment by VergilDarkSouls** [comment]
> This Vergil with Dante sword means that you're using "Force Files" to change Dante to have Vergil's model?
> If yes,then It's not a issue,force files just change dante's model to Vergil,It won't change the sounds for Vergil too

Oh ok understood. So what do i have to do to have vergil sound fx with dante's sword?

**Comment by SteveCraft1** [comment]
i checked the DDMK Menu and it don't seem to have any way to change actors's sounds

**Comment by VergilDarkSouls** [comment]
> i checked the DDMK Menu and it don't seem to have any way to change actors's sounds

hm ok i guess i will have to ask serpentiem. If not I will play it as it is thanks.

**Comment by SteveCraft1** [comment]
you're welcome

**Comment by serpentiem** [comment]
> So what do i have to do to have vergil sound fx with dante's sword?

You'd have to replace Dante's sound files with Vergil's. That's a job more suited for the mod forums. Closing.
