### ISSUE TITLE
Mission 11 bug

### ISSUE THREAD

**Issue by DSHugo** [serpentiem/ddmk#222]
During the beginning of mission 11, during the DT portion, the style switcher and character switching is disabled for some reason.

**Comment by SteveCraft1** [comment]
I suppose that you just wrote the mission wrong since the DT forced portion is on mission 12 but forget that.
on Serpentiem's before the lastest version have already said about this

> The Actor module achieved surgical precision and can be toggled between game scenes. So it turns itself off during > problematic parts of the game now.

> Currently these are:

> Mission 12
> As long as Haywire Neo Generator is active.
> Mission 18
> Boss select room
> Mission 19
> Arkham battle part 2
> Mission 20
> Credits

So it's not a bug,but if you're having this problem indeed on mission 11 on somewhere,then it's a bug.

**Comment by serpentiem** [comment]
I'll also assume you meant mission 12 and yes that is intended.
