### ISSUE TITLE
Where to download lucia.dll and Eva.dll

### ISSUE THREAD

**Issue by xdeann** [serpentiem/ddmk#223]
I am setting up ddmk for the first time and the instructions say i need to copy Mary, Lucia, Eva, and dinput8.dll, but when i install the latest release it only has Mary.dll and dinput8.dll?

**Comment by SteveCraft1** [comment]
Lucia and Eva dll is DDMK for DMC1 and DMC2,the last version of them is on DDMK 2.5,Just know that they aren't updated like Mary.dll(DMC3) so you'll find bugs easily
