### ISSUE TITLE
Feature list in wiki outdated and not present enough 

### ISSUE THREAD

**Issue by berserkingyadis** [serpentiem/ddmk#224]
I feel like the awesome features of this project are not presented visibly enough. The  [wiki ](https://github.com/serpentiem/ddmk/wiki/List-of-features)entry for the "features" only has DMC3 but there are dlls supplied for alot more of the games. I had to through a few [releases ](https://github.com/serpentiem/ddmk/releases) to find out what is modded for DMC4 for example. After then downloading the release zip there is no readme/changelog/feature list in there either.

Can you update the wiki or (even better) give a quick overview over the features of this awesome project in the [Readme](https://github.com/serpentiem/ddmk/blob/master/README.md)? Its the first thing people see and would improve the first impression and understanding. Installation instructions should be there too IMO. Players should not have go exploring to find the wiki for that.

Of course the player can download the latest release to learn by doing but I feel the above mentioned barrier is conquered by not much that work and will prove itself in the future by providing a way better presentation.

**Comment by serpentiem** [comment]
I agree and someone's already helping me with the wiki. I just started updating Kyrie; Once I'm done with that I'll update the readme as well.

**Comment by berserkingyadis** [comment]
Thank you for looking into it.

**Comment by Kazero21** [comment]
[Wiki](https://github.com/serpentiem/ddmk/wiki/Features) and [readme](https://github.com/serpentiem/ddmk/blob/master/README.md) are updated now.

**Comment by berserkingyadis** [comment]
Thank you! 🙏 This will lower the barrier of entry alot! 😄
