### ISSUE TITLE
Health is restoured everytime i changes rooms in DMC3

### ISSUE THREAD

**Issue by DixieNormus18** [serpentiem/ddmk#226]
Everytime i enable actor i get full health whenever i change rooms in both missions and in bloody palace i dont know if i can turn it off or if it's a issue with the mod.
Is there a way to turn it off?

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If not, please open a new issue.
