### ISSUE TITLE
Dmc3 style points bug

### ISSUE THREAD

**Issue by AceDecimation** [serpentiem/ddmk#227]
My stylish points at the end of the mission do not go up with the newest version
 
![124578898-379b3c80-de81-11eb-8be4-8e443227dafa](https://user-images.githubusercontent.com/82496438/129901427-6f9b1f0b-c6aa-4408-b20f-3454b39def97.png)

 
AceDecimation commented on Jul 6
after playing with an older version of ddmk, I can confirm they don't have the same bug

It's the same version, I was playing with before the latest update which is DDMK 2.7 Mary Nightly 25 April 2021

Edit: i have not tried it on any other level apart from the first one considering its the shortest and easiest

**Comment by SquidEyedV** [comment]
I have the same problem, it appears in all missions and seems to go away when you toggle the "Enable", in the "Actor" section, off

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15). If not, please open a new issue.

**Comment by AceDecimation** [comment]
Its fixed, Thanks :)
