### ISSUE TITLE
[Feature Request] Ability to keep Display Frequency in the last set value on DMC4SE.

### ISSUE THREAD

**Issue by GitHubro5** [serpentiem/ddmk#229]
Hello.

In DMC4SE, even if a player specifies a Display Frequency value above 60Hz in PC Settings, when the game is turned back on after the game ends, although the value refers to a previously set maximum value, there is a problem that actually applies at 60Hz.
This issue occurs in full screen mode with V-Sync ON in game or NVCP.

Therefore, if the player wants to play above 60FPS, each time he turn on the game, he must select a different value in PC Settings and then select the desired value.
The last selected value will then take effect until he turn off the game off.

Otherwise, to avoid this, the player must set the game in Windows mode or Windows (Borderless) mode.

In future versions, I hope that DDMK has the ability to fix this.

**Comment by serpentiem** [comment]
Added to #233.
