### ISSUE TITLE
[Bug] Some game speed mismatch problems caused by main speed/frame rate value adjustment. and large FPS drop issue for "Actor" function.

### ISSUE THREAD

**Issue by GitHubro5** [serpentiem/ddmk#231]
Hello.
I am using DDMK 2.7 Mary Nightly 30 June 2021 (2031c95).

After turning off V-Sync, the DMC3SE itself speeds up when the game frame rate is set above 60 Hz.
Therefore, the player must lower the Speed>Main value.

Now, for example, suppose I set the following values with DDMK.

Main Speed: 0.5
Frame Rate: 120.00 Hz
V-Sync: Force Off
In-Game Turbo: Off* (why***)

Everything feels normal, like playing in 60 Hz.
However, there are some problems here even though the game is consistently 120 FPS output.

As an example, play mission 20 in Heaven or Hell difficulty.
Count 5 seconds in your head and defeat Vergil.
Then, the clear time that appears on the resulting screen will be approximately 10 seconds.

Another problem can be seen, for example, in mission 18.
Another problem is that the speed of the camera following the player's character on the chessboard on mission 18 and the camera movement speed, which is controlled by the analog stick on the right side, is also doubled.
In addition, the time it takes for enemies to activate Devil Trigger is halved.

The two problems related to the camera speed above do not occur in all missions.

(* Turn turbo mode on has a bug that speeds up abnormally under certain circumstances**, so turn turbo mode off to maintain normal speed for high FPS.)
(** For example, when the player first enter Love Planet in mission 3, there is a place where three Hell Sloths come out at the same time and attack player after the cut scene.)
(*** In turbo mode, the main value will be ignored so the turbo value should be adjusted instead of the main value, but it will not function normally under all current circumstances.)

The last problem is that the FPS drops a lot when using the "Actor" function.

For example, in my case, 170-180 FPS is obtained when the function is disabled in mission 2.
However, when activated, 110-120 FPS comes out.

**Comment by serpentiem** [comment]
What you experience is normal. The game was programmed around 60 FPS. Many things are hardcoded and don't care about the global speed rates. As for the fps drops: I don't experience them myself. With `Actor function` I assume you mean when the Actor module is enabled. Of course that requires additional performance, because a lot more is going on when it's enabled.

**Comment by GitHubro5** [comment]
Thank you for your answer.

The Actor Module you mentioned is correct.

I'm sorry about the speed problem.
Personally, I'm playing with high Hz because of its smoothness, but I think it'll be solved later if I'm using a monitor that supports G-Sync-related technology.

It doesn't exist yet, but I'll try it there later when the Hz adjustment function is added in DMC4SE DDMK.
Of course, I know that DMC4SE supports more than 120 FPS, but I don't know the exact limit.

**Comment by serpentiem** [comment]
Closing.
