### ISSUE TITLE
Issues and requests regarding DDMK 2.7 Eva Mary Nightly 31 August 2021.

### ISSUE THREAD

**Issue by frog4510** [serpentiem/ddmk#232]
You can no longer change characters, weapons, styles, etc. in the staff roll, which was possible in the previous version.
I don't want to have to redo the settings from scratch for every new version.
I apologize for my unnatural English. I am using translation software.

**Comment by serpentiem** [comment]
> You can no longer change characters, weapons, styles, etc. in the staff roll, which was possible in the previous version.

Yes, the Actor module is disabled for problematic parts now.

> I don't want to have to redo the settings from scratch for every new version.

In my opinion, clicking a few buttons is a small price to pay for improvements.

> I apologize for my unnatural English. I am using translation software.

Don't, it doesn't sound unnatural. Great software!

**Comment by frog4510** [comment]
I'm a little disappointed, but glad to hear back from you.
Thank you very much!

**Comment by serpentiem** [comment]
You're welcome. Closing.
