### ISSUE TITLE
Style Level/XP Not Increasing

### ISSUE THREAD

**Issue by Deathmun** [serpentiem/ddmk#236]
On the latest build, it appears as though non-maxed styles dont gain any XP.

**Comment by serpentiem** [comment]
[Latest release](https://github.com/serpentiem/ddmk/releases/tag/2.5) or [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15)?

**Comment by Deathmun** [comment]
Latest nightly (DDMK 2.7).

**Comment by serpentiem** [comment]
Try again with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly22).
