### ISSUE TITLE
How do I perform Quick Drive in DMC 3?

### ISSUE THREAD

**Issue by GlitchBorealis** [serpentiem/ddmk#237]
How do I perform Quick Drive in DMC 3?

**Comment by SteveCraft1** [comment]
When you have It activated and is using swordmaster,hold style button and press attack button 2 times and you'll do it

**Comment by GlitchBorealis** [comment]
Thanks a lot! Where I can find sort of instruction for DDMK?

**Comment by SteveCraft1** [comment]
I'm not sure If wiki was updated so part of some things you'll find in the releases's description while others in DDMK on the ? thing and others you gonna have to test It yourself

**Comment by SteveCraft1** [comment]
Also in overlays section,you can activate New moves to see How you do It in the game

**Comment by GlitchBorealis** [comment]
Strange, but holding B and pressing Y, Y doesn't work. But when I do Lock-On + Left + Y it works.

**Comment by SteveCraft1** [comment]
Lock on left y is New Drive,also are you with swordmaster and pressing y 2 times fast?

**Comment by GlitchBorealis** [comment]
Im pressing Y as fast as I can while holding B with Swordmaster, yes

**Comment by SteveCraft1** [comment]
did you activated it?

**Comment by GlitchBorealis** [comment]
"Requires pl000_00_3.pac from the Demo" what the Demo?

**Comment by SteveCraft1** [comment]
this thing was for 2.5 and 2.6,Quick Drive is now normally accessible without it

**Comment by SteveCraft1** [comment]
> "Requires pl000_00_3.pac from the Demo" what the Demo?

did it was in the DDMK itself?

**Comment by SteveCraft1** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/73554591/132995979-2a0a5a58-c8b7-4a45-b0a2-f93f24e11310.gif)

**Comment by GlitchBorealis** [comment]
"Requires pl000_00_3.pac from the Demo to work. Extract it with AFSExplorer and save it as demo_pl000_00_3.pac in data\dmc3\GData.afs of your Devil May Cry HD Collection root directory."

What kind of Demo is there written about?

**Comment by SteveCraft1** [comment]
It's to get Quick drive in DDMK 2.5 and 2.6,but 2.7 already have Quick drive on It,it's not needed to have this file after the own DDMK not needing It anymore

**Comment by SteveCraft1** [comment]
#199 me and another person already covered It all about it

**Comment by GlitchBorealis** [comment]
Well, I don't know why, but I can't do Quick Drive. The option is activated.
![изображение](https://user-images.githubusercontent.com/34347564/132997520-6744a4a1-4123-4100-944d-38b9e07104b1.png)

**Comment by SteveCraft1** [comment]
Do you have Actor enabled?

**Comment by GlitchBorealis** [comment]
Yes

**Comment by SteveCraft1** [comment]
It's weird that you're not being able to use quick drive,try Spamming Attack button while Holding Style Button in swordmaster

**Comment by GlitchBorealis** [comment]
That's what I'm doing. 

Before installing 2.7 I installed 2.5 with patch as it was written in the instruction https://github.com/serpentiem/ddmk/wiki/Installation-Instructions

**Comment by SteveCraft1** [comment]
i tried here some ways and the only difference i saw when trying to use QuickDrive was that it simply replaces Combo A's second hit with it

I'm sorry but i don't know what to do anymore to help you

**Comment by GlitchBorealis** [comment]
Well, that's strange, Thanks anyway.
