### ISSUE TITLE
DMC5 Vergil Boss Mods

### ISSUE THREAD

**Issue by NowImMotivated93** [serpentiem/ddmk#238]
Friend can you make some Vergil Boss Mods for playable Vergil for example?

1. Vergil Boss afterimages inside Judgement Cut End.

2. JC trail on the ground.

3. Vergil Boss version Parry Counter-Attack for close attacks,Stab or Grab Attack for Boss Dante with Yamato Stinger only and 
    Yamato walking deflect or block for long range attacks Boss version.

4. And last SDT Jump then Dive Bomb in the Air like Boss Vergil.

If its not too hard for you I would ask you to do this for the DMC community because no one still knows how to make this. 
And yes https://www.nexusmods.com/devilmaycry5/mods/thisweek/?BH=0 visit this site where you can see a lot of Mods.
Well maybe you will become the Legend who managed to make these Boss Mods who knows 😁

**Comment by Kazero21** [comment]
Serp stated before that he is not interested in modding dmc5.

You can use Infernal Warks to suggest your dmc5 mods ideas. There might be someone interested there to do them.

Also, it is better to not open a new issue for a request, you can use [this](https://github.com/serpentiem/ddmk/issues/233) to write your requests.
