### ISSUE TITLE
Devil May Cry 1 crashes loading mission 4, 5 and 6

### ISSUE THREAD

**Issue by ssjtrey** [serpentiem/ddmk#239]
Devil May cry 1 crashes when starting missions 4, 5 and 6. Others work without any problems. By toggling mission select option multiple times the mission can be started, but the next one is gonna crash anyway

**Comment by serpentiem** [comment]
[From the wiki](https://github.com/serpentiem/ddmk/wiki/Features#mission-select):

`Keep in mind that, unlike later entries in the series, your progress is not automatically adjusted for the selected mission. So depending on your overall progress the game may behave unexpectedly. Some areas may not be accessible, earlier items may still be available later in the game, etc.`

Closing.
