### ISSUE TITLE
DMC3 crash on Mission 12

### ISSUE THREAD

**Issue by Cobalnite** [serpentiem/ddmk#240]
Everytime I start Mission 12, either the mods deactivate and the game crashes in the middle of the level; or the game proceeds as normal, but the DT HP drain effect is still active after the checkpoint where it's removed.

**Comment by Kumakare** [comment]
same here except the guns are completely broken when i use the guns dante will T-Pose and i only have access to cerberus and rebellion

**Comment by Kazero21** [comment]
Just tested it out with the [latest Nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly19), and I was able to finish the whole mission without a crash.

> Everytime I start Mission 12, either the mods deactivate and the game crashes in the middle of the level; or the game proceeds as normal, but the DT HP drain effect is still active after the checkpoint where it's removed.

The actor system is deactivated in certain parts of the game to prevent crashes. For mission 12, it should get normal after the checkpoint (make sure to go to any other room after the cutscene to have the actor system active again).

Other than that is not normal.

> same here except the guns are completely broken when i use the guns dante will T-Pose and i only have access to cerberus and rebellion

Most likely a problem with your save file.

**Comment by MoriyaFaith** [comment]
From what I can tell, it seems to be an issue with what happens when the Actor System is turned off. When you Start a save file with the actor mode on, it seems that the game completely fucks up your weapons. On my end, it turned up a glitched version of Spiral and Artimis that don't work, and make Dante T-Pose. Not to mention, in earlier missions, I remember my assigned firearms being Melee weapons, which might have to do with it.

**Comment by serpentiem** [comment]
Try again with the [latest release](https://github.com/serpentiem/ddmk/releases/tag/2.7Release).

If you still experience weapon-related issues be sure to reset your weapons.

To do so click on `Reset Weapons` in the `Repair` section while in the mission select menu.

Remember to save your game.
