### ISSUE TITLE
Can't seem to pick Vergil for the campaign or bloody palace. 

### ISSUE THREAD

**Issue by TheIdealBaron** [serpentiem/ddmk#246]
When playing on a Vergil file and pick campaign or BP, the cutscenes are still Vergil's, but I end up playing as Dante.

**Comment by Kazero21** [comment]
You need to choose him in the Actor module too if it was enabled
Check [Wiki](https://github.com/serpentiem/ddmk/wiki/Features#devil-may-cry-3) for more info
