### ISSUE TITLE
DMC4SE isn't starting with DDMK installed.

### ISSUE THREAD

**Issue by walkingtalkingexistentialcrisis** [serpentiem/ddmk#247]
See title. I know that there's already a thread with a solution to this, even if it's still Open, but when I attempt to add DDMK  2.7 Nightly from 28th of October to DMC4SE, it just doesn't work, I know it's gotta be something with DDMK, because when I remove DDMK, it works perfectly fine. Help please?

**Comment by SteveCraft1** [comment]
try checking the log dinput8.txt file,if it says warning:no match then try changing the DMC4SE exe file to DMC4.exe

**Comment by walkingtalkingexistentialcrisis** [comment]
> try checking the log dinput8.txt file,if it says warning:no match then try changing the DMC4SE exe file to DMC4.exe

I'll try that when I'm next on my computer (I just hopped off for the night for reference) and let you know how it goes. Thanks man!

**Comment by walkingtalkingexistentialcrisis** [comment]
> try checking the log dinput8.txt file,if it says warning:no match then try changing the DMC4SE exe file to DMC4.exe

This is all it says:
![image](https://user-images.githubusercontent.com/83911894/139613935-f145b38f-af08-4d42-a172-f74c680c6bea.png)

**Comment by walkingtalkingexistentialcrisis** [comment]
I looked in the Kyrie text file, and it said this. Maybe that has something to do with it?
![image](https://user-images.githubusercontent.com/83911894/139614272-a92c9808-391e-4d2a-8640-585823b4dd26.png)

**Comment by SteveCraft1** [comment]
It seems that its getting a error related to steam,unfortunately the only one who know what this error means is serpentiem so we gonna have to wait

**Comment by walkingtalkingexistentialcrisis** [comment]
Damn. Ah well, hopefully he'll either figure it out soon, or see this soon so he'll be able to figure it out sooner or something.

**Comment by Raze9102** [comment]
I tried to 'downgrade' using the files the dev gave us using delta and the downgrade files, but i got an error message about "steaminternal_createinterface" not being found in the EXE of the game. Any help would be appreciated
[dinput8.txt](https://github.com/serpentiem/ddmk/files/7771171/dinput8.txt)
[Kyrie.txt](https://github.com/serpentiem/ddmk/files/7771172/Kyrie.txt)
.

**Comment by serpentiem** [comment]
Verify the integrity of your game files in Steam, re-read [the installation instructions](https://github.com/serpentiem/ddmk#installation) and try again.

**Comment by walkingtalkingexistentialcrisis** [comment]
Thanks very much friend! Currently reinstalling DMC4SE to see if your fix works (also tbh, I was using some old instructions on web archive because I couldn't find any instructions on the page at all, so perhaps you should list that the instructions are in that readme somewhere (the instructions I was originally using (web.archive.org/web/20210104221407/https://github.com/serpentium/ddmk/wiki/Installation-Instructions))).

**Comment by walkingtalkingexistentialcrisis** [comment]
> Verify the integrity of your game files in Steam, re-read [the installation instructions](https://github.com/serpentiem/ddmk#installation) and try again.

Did it, still doesn't work.

**Comment by walkingtalkingexistentialcrisis** [comment]
this is what the bottom of the Kyrie log says, and it appears to be the only thing that's failed in the process from what I can make of it

![Screenshot 2022-01-24 232943](https://user-images.githubusercontent.com/83911894/150787220-9679cf35-3875-4eaf-bdb1-c0587581ce82.png)

**Comment by walkingtalkingexistentialcrisis** [comment]
uninstalled and reinstalled, and re setup ddmk, still not working

**Comment by walkingtalkingexistentialcrisis** [comment]
Tried to open it from the exe file in the folder, this is what came up @serpentiem 

![Screenshot 2022-01-25 065627](https://user-images.githubusercontent.com/83911894/150859399-57e249b8-f54f-4457-b40a-a8d5771fe798.png)
