### ISSUE TITLE
DMC 1: devil trigger not working outside of Super Dante - ddmk nightly 2.7

### ISSUE THREAD

**Issue by phazefox** [serpentiem/ddmk#249]
Hello, new to using ddmk but i noticed a strange bug after some very specific circumstances. after finishing a dante must die run with Sparda DT enabled on super dante i started my other save file with Sparda/legendary-dark-knight and noticed that when i activated DT it immediately deactivated itself. i then went on to test on my normal Dante save file and confirmed it too had the issue. However returning to super Dante he could still use DT normally.

now i must add, i have played on all 3 characters with Sparda DT enabled before and they all worked fine, the issue seems to have started after finishing the final mission with Super Dante, but even then it's not so simple.
I didn't just finish the game normally, what i did was, after finishing the last mission, and saving, putting the super Dante file on the prologue, i used the mission select function to replay the last mission, as i had noticed an interesting glitch(feature?) where you could continue using Sparda (with DT enabled) during it so long as you didn't change weapons, and wanted to see if i could get the game to start with Dante wielding Sparda. i finished mission 23 with Sparda still equipped, which proceeded to show in all the in-engine cutscenes during it, and saved the game. When the game moved onto the prologue the first anomaly happened, instead of starting normally the game loaded into what i can only assume was Dante's office with the camera zoomed outside of it, meaning i couldn't see anything but a floating room, but i could control Dante inside of it and jump around, though iirc not anything else. I then force-closed the game as it didn't let me open the menus, and restarted with the mission select now disabled. The game loaded successfully into the prologue and things seemed to work normally, Dante did indeed start the game wielding Sparda and i was satisfied, so i left it at that for the night. This was a couple days ago

Now earlier today i intended to start a run with Sparda wielding DT enabled Sparda, and that's when the aforementioned DT deactivating itself anomaly happened. After confirming only Super Dante could use DT i first tried to use the mission select and then the arcade mode to force the game into loading into a state where DT worked, using the arcade mode to first load the prologue and then mission 17 with maxed health, maxed DT, sparda weapon in sparda form and shotgun. i do not know why i thought this would work but it didn't.

Afterwards i tried checking what'd happen if i uninstalled the mod, i removed Eva.dll and dinput8.dll from the HD collection folder and ran the game, it now worked normally, both Dante and Sparda could use DT and Super Dante simply started the game with Alastor instead of Sparda, also working normally. i then reinstalled the mod using a fresh copy of Eva.dll and dinput8.dll but i guess the config was saved somewhere else 'cus it started the game by triggering the arcade mode i hadn't disabled before. i then disabled arcade mode and confirmed the issue was back.

After this i first verified the game's files on steam to get a fresh install, though i noticed that unlike other games it didn't wipe all extraneous files from the directory, so i proceeded to uninstall, wipe and reinstall on an empty directory. I then checked my save files which seemed to be as i had left them, and then reinstalled the mod, once more with fresh Eva.dll and dinput8.dll files. The issue seems to be fixed now (and super Dante still starts the game with Sparda), though i did get one crash after checking the super dante file, using Sparda DT in the prologue, resetting from the menu and starting up the legendary dark knight file. but i repeated the process and the crash didn't happen. i have however not checked beyond the prologue on the cliffs for further anomalies, and i suppose i should report if anything strange happens further down the line.

As for the other settings on the mod during the anomaly.

actor:
force edge fixes enabled
sparda fixes enabled
air hike core ability
infinite round trip
round trip return controller on B (default)
charge controller on X (default)

system:
hide mouse cursor enabled
window force focus enabled (though i play on fullscreen)

i also had previously used the melee weapon select to try and see how getting a Sparda and Ifrit set-up could work, i only tried this on the same day i got super dante to start the game with Sparda and disabled it then. i didn't have the melee weapon switcher enabled at any point during the run i noticed the issue on nor at any moment afterwards.

Sorry for the overly long post, maybe i'm going overboard for something i seem to have managed to fix already, but i got really paranoid about my files perhaps being corrupted, which they don't seem to be, so i ended up writing all this. thanks for putting up with my rambling and i hope all this info is useful somehow.

**Comment by phazefox** [comment]
right, i forgot. i kinda just realized i had DT deactivating itself before, during the sparda DT enabled super dante dante must die run. While fighting nelo angelo trying to use the bangle of time had the same effect, it immediately deactivated itself, but without the bangle DT could be used normally. At the time i thought this was a feature of the nelo angelo 3 boss fight but now i'm not sure, i hadn't tried using the bangle on it before. mentioning just in case

**Comment by phazefox** [comment]
i have just now finished the game with the legendary dark knight on hard, also with the DT enabled sparda. this time the game progressed normally to the prologue with sparda still equiped, so i presume what caused the weird spawn before was the mission select.
more relevant to the tile though, only now i have noticed that the same issue of DT being unavailable outside of super dante happens when you load into a save file with infinite magic points already enabled on the trainer. i am fairly certain i didn't have it on when i first encountered the issue but can't help but wonder if i just missed it being on and it was that all along. the issue disappears if you just wait until already loaded into the game to activate infinite magic.

**Comment by serpentiem** [comment]
OK, I read all that.

Seems like you were able to resolve the issue.

I'll file it under `interaction of extensive gameplay mods caused strange circumstances`.

Closing.
