### ISSUE TITLE
Is is possible to make the Doppelganger copy all of Dante's actions simultaneously so we don't have to use a button?

### ISSUE THREAD

**Issue by DomoPANDAS** [serpentiem/ddmk#250]
I think it'd be nice if the Doppelganger DT'd and swapped weapons and styles the same time Dante did instead of having to repeat every action twice while holding R3 which is a pain mid-combo.

**Comment by Kazero21** [comment]
Use this [issue](https://github.com/serpentiem/ddmk/issues/233) to write your requests.
