### ISSUE TITLE
DMC3: Collected blorbs fail to save and permanently disappear

### ISSUE THREAD

**Issue by Spritzkrieg** [serpentiem/ddmk#251]
(DMC3, latest nightly, 11/13)

Sometimes collected blorbs fail to save, and are also permanently “deleted” from the map. So the blorb fragments disappear, but the character doesn’t keep their extra vitality. The vitality will update inside the mission where a blorb is collected, but after loading another mission (even when progress is saved), it will be reset.

Noticed this while collecting all the blorbs. At first, I thought this problem would only trigger once — I tried collecting all the blorbs twice before, and both times I only fell short by one blorb (4 fragments), even when I referenced a guide to make sure I wasn’t missing anything. But while testing this out to make sure I wasn’t just an idiot, I managed to “perform” this glitch twice: 8 blorb fragments collected, no vitality gained, and all of the fragments permanently gone.

Worth noting that this didn’t happen with secret missions, despite the multiple times I completed them all. Didn’t happen with the blorbs in the shop, either: just the fragments collected in the overworld. I’d rather not embarrass myself by theorizing about it, so assuming that this issue isn’t a convenient fix, I suggest an option to manually change the vitality stats / collected number of fragments, however that might work.

Not a huge issue — I could just simulate a full healthbar by earning one single bar, then setting my received damage to 0.5 — but that’s that. The completionist in me is bothered by the incomplete HUD…

Thank you :)

EDIT: Blorbs SUCCEED in saving if done through the mission clear screen. This is only necessary when completing a whole blorb with 4 fragments. So my completionist instincts are satisfied.

**Comment by serpentiem** [comment]
Try again with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly22).
