### ISSUE TITLE
DMC4SE: No matter how high Base Frame Rate is set, the game itself runs only up to 120 FPS.

### ISSUE THREAD

**Issue by GitHubro5** [serpentiem/ddmk#252]
Hello.

New versions have the ability to fix the FPS value to a specific custom value in Graphics section.

But after a few tests, I realized that the game itself runs only up to 120 FPS.

According to this link,
https://www.pcgamingwiki.com/wiki/Devil_May_Cry_4:_Special_Edition#Video
DMC4SE may be designed to work at 120 FPS or higher.

If possible, It would be nicer having an ability to override this FPS limit in future updates.

**Comment by serpentiem** [comment]
Try the following:

In pc settings set the frame rate to 60 fps max and disable vsync.

In the System section of ddmk set Base Frame Rate to 60, Target Frame Rate to whatever you want and V-Sync to Force Off.

**Comment by GitHubro5** [comment]
I did it according to your instructions.

As a result, the speed of the game has become very fast, so I can't play normally.

Here are some of the results I found.
All test is done with 60, 120Hz in PC Settings, disabled V-Sync.

1. If I set the Base Frame Rate value smaller than the Target Frame Rate value, the game speed will be faster. As a result, the frame is displayed higher than 120.
The larger the difference between the two values, the faster the game runs.
Therefore, the game cannot be played normally.
(tested with Base Frame Rate: 60, Target Frame Rate: 144)

2. As the Base Frame Rate value approaches the Target Frame Rate value, the game runs closer to the normal speed.
But it's still faster than normal.
(tested with Base Frame Rate: 130, Target Frame Rate: 144)

3. In order for the game to run at a normal speed, the two values must be the same.
However, in this case, no matter how high I set the two values, the game still runs at maximum 120.
(tested with Base Frame Rate: 165, Target Frame Rate: 165)

I think PC Gaming Wiki's information might be wrong.

In the vanilla version, the DMC4 Hook has a similar ability that allows the game to run at a normal speed of 120 frames or more.

**Comment by serpentiem** [comment]
The game's faster, because it runs at a higher frame rate. You have to adjust the speed as well. Try these settings, they work fine on my end.

![settings](https://user-images.githubusercontent.com/38213025/150659681-c5849b27-d830-4166-b728-8b9df229b630.png)

**Comment by GitHubro5** [comment]
I tried setting it up just like your picture.
As a result, it works well.
Thank you.

However, in my case, the game FPS exceeds the set Target Frame Rate 144.
In other words, the FPS doesn't stop at 144.
Is this normal?
