### ISSUE TITLE
Installing DDMK does not work

### ISSUE THREAD

**Issue by flyingflame7** [serpentiem/ddmk#253]
I've tried to install the most recent nightly build, the latest build, random builds from the list, everything. Nothing so far has had the mod install in any way. I've been installing the files on the main page as well (quick drive and xdelta). Also, with the 2.5 build, the folder where those files go won't generate. Anyone know what could be happening?

**Comment by SteveCraft1** [comment]
did you tried extracting dmc3-0.nbz? if DDMK don't do by itself then you need to do it or DDMK won't work ever,you can use winrar to extract it 
![image](https://user-images.githubusercontent.com/73554591/148410311-8561f45b-c203-40ef-b389-85f01067eddb.png)
it'll stay like this

**Comment by flyingflame7** [comment]
> did you tried extracting dmc3-0.nbz? if DDMK don't do by itself then you need to do it or DDMK won't work ever,you can use winrar to extract it ![image](https://user-images.githubusercontent.com/73554591/148410311-8561f45b-c203-40ef-b389-85f01067eddb.png) it'll stay like this, you only need to do it on DMC3

I've done this now and the folder is there now, with some files that definitely weren't there before, (and I've extracted the specified quick drive and xdelta files) but it still isn't working unfortunately. Super lost right now to be honest lol.

**Comment by SteveCraft1** [comment]
Is it steam or pirated?

**Comment by SteveCraft1** [comment]
Also unless that you want to play on 2.5/2.6/lower, theres no reason to install quick drive

**Comment by flyingflame7** [comment]
> Is it steam or pirated?

I have a steam copy of HD collection

> Also unless that you want to play on 2.5/2.6/lower, theres no reason to install quick drive

oh I see, it wasn't made super clear what exactly quick drive was and couldn't find any information on it, so I assumed I might as well install it

**Comment by SteveCraft1** [comment]
How the problem happens? DDMK don't appear when trying to Access it,game crash with ddmk installed or game already crashed before installing?

**Comment by flyingflame7** [comment]
> How the problem happens? DDMK don't appear when trying to Access it,game crash with ddmk installed or game already crashed before installing?

DDMK does not appear when the game launches

**Comment by SteveCraft1** [comment]
Try checking on the logs to see what is the error

**Comment by flyingflame7** [comment]
> Try checking on the logs to see what is the error

there are only 2 logs in the folder, one for dinput8 and one for Mary

dinput8:
12:29:56.864 Session started.
12:29:56.864 Init
12:29:56.865 Load

Mary:
12:29:56.867 Session started.
12:29:56.867 Memory_Init
12:29:56.868 22524 dmc3.exe 7FF7CB5A0000
12:29:56.868 HighAlloc
12:29:56.868 Begin search. 7FF7CB5A0000 7FF84B59FFFF
12:29:56.868 7FF7CC34C000 7FF7CC34C000 52E664000 10000
12:29:56.868 4000
12:29:56.868 7FF7CC350000 7FF7CC350000 52E660000 10000
12:29:56.868 Match found.
12:29:56.869 Allocation was successful. 7FF7CC350000 1000
12:29:56.889 Config_Init
12:29:56.889 Cosmetics_Color_AdjustConfig
12:29:56.889 LoadConfig
12:29:56.889 Hooks_Init
12:29:56.889 System_Actor_Init
12:29:56.889 System_Actor_Toggle 0
12:29:56.890 System_Animation_Init
12:29:56.890 System_Cache_Init
12:29:56.890 System_Camera_ToggleInvertX 0
12:29:56.890 System_Event_Init
12:29:56.890 System_File_Init
12:29:56.891 System_Input_Init
12:29:56.891 System_Media_Init
12:29:56.891 System_Media_ToggleSkipIntro 0
12:29:56.891 System_Media_ToggleSkipCutscenes 0
12:29:56.891 System_Weapon_Init
12:29:56.891 System_Weapon_Toggle 0
12:29:56.891 System_Window_ToggleForceFocus 1
12:29:56.891 Game_Arcade_Toggle
12:29:56.891 Game_Attack_Init
12:29:56.891 Game_Dante_Init
12:29:56.892 Game_Dante_Rebellion_ToggleInfiniteSwordPierce 0
12:29:56.892 Game_Dante_EbonyIvory_ToggleFoursomeTime 0
12:29:56.892 Game_Dante_EbonyIvory_ToggleInfiniteRainStorm 0
12:29:56.892 Game_Dante_Artemis_ToggleSwap 0
12:29:56.892 Game_Dante_Artemis_ToggleInstant 0
12:29:56.892 Game_Dante_AirHike_ToggleCoreAbility 0
12:29:56.892 Game_Dante_CrazyCombo_SetLevelMultiplier
12:29:56.892 Game_Dante_WeaponSwitchTimeout_MeleeToggle 12
12:29:56.892 Game_Dante_WeaponSwitchTimeout_RangedToggle 12
12:29:56.893 Game_Mobility_Init
12:29:56.893 Game_Mobility_Toggle 0
12:29:56.893 Game_Other_Init
12:29:56.893 HighAlloc
12:29:56.893 Begin search. 7FF7CB5A0000 7FF84B59FFFF
12:29:56.893 7FF7CC34C000 7FF7CC34C000 4000 10000
12:29:56.893 4000
12:29:56.894 7FF7D0350000 7FF7D0350000 52A660000 10000
12:29:56.894 Match found.
12:29:56.894 Allocation was successful. 7FF7D0350000 1000
12:29:56.894 Game_Other_Toggle
12:29:56.894 Game_Other_Reset
12:29:56.895 Game_ResetMotionState_Init
12:29:56.895 Game_Speed_Init
12:29:56.895 HighAlloc
12:29:56.895 Begin search. 7FF7CB5A0000 7FF84B59FFFF
12:29:56.895 7FF7CC34C000 7FF7CC34C000 4000 10000
12:29:56.895 4000
12:29:56.896 7FF7D0351000 7FF7D0351000 52A65F000 10000
12:29:56.896 F000
12:29:56.896 7FF7D0360000 7FF7D0360000 52A650000 10000
12:29:56.896 Match found.
12:29:56.896 Allocation was successful. 7FF7D0360000 1000
12:29:56.896 Game_Speed_Toggle 0
12:29:56.896 Game_Speed_Reset
12:29:56.897 Game_Style_Init
12:29:56.897 Game_Style_Doppelganger_ToggleUseEXVersion 0
12:29:56.897 Game_StyleSwitcher_Init
12:29:56.897 Game_StyleSwitcher_Toggle 0
12:29:56.897 Game_Training_ToggleInfiniteHitPoints 0
12:29:56.897 Game_Training_ToggleInfiniteMagicPoints 0
12:29:56.897 Game_Training_ToggleDisableTimer 0
12:29:56.897 Game_Vergil_Init
12:29:56.898 Game_Vergil_ForceEdge_ToggleInfiniteRoundTrip 0
12:29:56.898 Game_Vergil_SummonedSwords_ToggleChronoSwords 0
12:29:56.898 Game_Vergil_WeaponSwitchTimeout_MeleeToggle 8
12:29:56.898 Game_WeaponSwitcher_Init
12:29:56.898 Game_WeaponSwitcher_Toggle 0
12:29:56.898 ResetDevilModel
12:29:56.898 Cosmetics_Color_Init
12:29:56.898 Cosmetics_Color_Toggle 0
12:29:56.898 Cosmetics_Color_ResetRGB
12:29:56.899 Cosmetics_Dante_Init
12:29:56.899 Cosmetics_Dante_ToggleHideBeowulf 0
12:29:56.899 Cosmetics_Dante_Beowulf_LiveUpdate
12:29:56.899 Cosmetics_Other_Init
12:29:56.899 Cosmetics_Other_ToggleNoDevilForm 0
12:29:56.899 Cosmetics_Vergil_ToggleHideBeowulf 0
12:29:56.899 Cosmetics_Weapon_Init
12:29:56.899 Cosmetics_Weapon_ToggleInstantModelUpdate 0
12:29:56.899 Cosmetics_Dante_Beowulf_LiveUpdate
12:29:56.992 ImGui_DirectInput8_Init
12:29:57.025 User_Hook_CreateWindowExW 0 CBA65590 CBA65518 90000000 0 0 1920 1080 0 0 CB5A0000 0
12:29:57.057 User_Hook_WindowProc
12:29:57.208 D3D11_Hook_CreateDeviceAndSwapChain 0 1 0 0 620A6FFC80 1 7 620A6FFC00 7FF7CC1AB428 7FF7CC1AB418 7FF7CC18B3E8 7FF7CC1AB420
12:29:57.391 System_Window_UpdateSize 1920 1080
12:29:57.391 CreateRenderTarget
12:29:57.445 DirectInput8_CreateMouseThread
12:29:57.445 DirectInput8_UpdateMouseThread
12:29:57.980 DXGI_Hook_Present 20540134890 1 0
12:30:34.007 SetTrack afs/sound/Kaze_01.adx
12:30:36.483 SetTrack afs/sound/Option.adx
12:30:39.682 SetTrack afs/sound/Kaze_01.adx
12:31:08.788 SetTrack afs/sound/M_start.adx
12:31:12.122 SetRoom
12:31:13.393 StageLoadComplete
12:31:13.393 Actor_StageLoadComplete
12:31:13.394 SetTrack afs/sound/Kaze_01.adx

Nothing seems to be an error in these logs aside from how short dinput8 is, though there aren't logs for Eva or Lucia

**Comment by SteveCraft1** [comment]
So this means that ddmk is in fact running fine,if it weren't running dinput.txt log would say stuff like "failed to load' or something,but from these logs your ddmk is running completely fine

**Comment by SteveCraft1** [comment]
Try holding CTRL and press D to see if it gonna open the ddmk menu

**Comment by flyingflame7** [comment]
> Try holding CTRL and press D to see if it gonna open the ddmk menu

Well, that worked xD

not sure how much of this was me just not knowing how the mod works, but at least it's going now, ty very much for the help

**Comment by SteveCraft1** [comment]
You're welcome,keep in mind that to make doppelganger work in multiplayer,serpentiem needed to create a actor system so with actor module enabled to not have other types of errors it  maximize all styles and skills for the characters since beginning(except health bar and Devil Trigger)

**Comment by SteveCraft1** [comment]
Forget what i said about exp,he brough it back on 6 january release

**Comment by SteveCraft1** [comment]
Eva.dll and Lucia.dll are ddmk for dmc1 and dmc2 so until you play these games,there won't be Lucia and Eva logs

**Comment by serpentiem** [comment]
Closing.
