### ISSUE TITLE
DMC3: Blue/Purple orbs not being accurately reflected

### ISSUE THREAD

**Issue by Archcadia** [serpentiem/ddmk#255]
This issue occured using the newest nightly (6/1/2022)

So thanks to the new shop menu system in place this build introduced, any red orbs that were spent on Blue/Purple orbs to increase health and DT respectively, those upgrades are not accurately reflected. I should mention I did buy a purple orb prior to mission 8, however I also bought 3 blue orbs and while the health has gained 3 sections, this is thanks to the orb fragments found in secret missions/missions.

I should also mention that I started a completely new save thanks to the style levelling that this build introduced, and that this was not an issue in prior builds.

Edit: I forgot to mention purchasing skills worked completely fine

**Comment by serpentiem** [comment]
Confirmed. Will investigate.

**Comment by SteveCraft1** [comment]
i don't know if it will work for you but i discovered that using the shop before starting a mission don't give buyed orbs but using the statues during missions will give both purple orb and blue orbs

**Comment by Archcadia** [comment]
I tried that and that didn't seem to work either. Started fresh again and bought a blorb using the divinity staute before cerberus and health did not increase

**Comment by SteveCraft1** [comment]
Weird,for me it only work when i try buying it in a divinity statue
https://user-images.githubusercontent.com/73554591/148692044-f7be714a-a292-4c20-9302-ea6f84c093e0.mp4
I think this problem is just like Nero's devil trigger,it's different for each user

**Comment by serpentiem** [comment]
Should be fixed in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly22).

The situation is a bit hairy though. You have 2 options. Either start a new game and overwrite the old save or send me your save file and I'll fix it.

**Comment by serpentiem** [comment]
I could in theory also add a new repair option.

**Comment by Archcadia** [comment]
Started a new game, wasn't that far in anyway. Bought a blorb in the pre-mission menu and upon starting the mission I did have an extra segment of health.
