### ISSUE TITLE
Game doesn't launch after installing the mod 

### ISSUE THREAD

**Issue by DLCContent** [serpentiem/ddmk#256]
Hi! How do you fix the issue where the game doesn't launch with marry.dll in the root dictionary. I checked the logs and my first problem was the data file for dmc3 where I was missing the GData.afs.  I extracted the dmc3-0.nbz and followed the Install-instructions and the game still won't launch. And as of now, my logs look a bit smaller than they were
[dinput8.txt](https://github.com/serpentiem/ddmk/files/7838003/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/7838004/Mary.txt)
Does anyone know how to fix this? Maybe you know what I'm doing wrong?@serpentiem 
also, I'm playing it on the pirated version with a codex from https://www.skidrowcodex.net/devil-may-cry-hd-collection-codex/comment-page-1/ so I'm not sure if it's the correct version. and another thing I want to mention. the new quick drive file am I supposed to rename the "diff_pl000-00_03"? because that's what I did and applied the patch and it still didn't work. i tried almost every troubleshoot I could find but none of them seem to work.

**Comment by SteveCraft1** [comment]
First,Quick Drive files are for versions older than 2.7.
Second,DMC HD Collection had a update on steam so if you can't update it then it will always crash with DDMK

**Comment by serpentiem** [comment]
No support for pirated versions here.
