### ISSUE TITLE
DMC4SE cannot use ddmk

### ISSUE THREAD

**Issue by AgnusDei2021** [serpentiem/ddmk#258]
Is it possible to add support for the latest version of DMC4SE on Steam, DMC3 can be opened normally but DMC4 will exit.

**Comment by walkingtalkingexistentialcrisis** [comment]
I'm having the same issue. It either refuses to open or immediately crashes upon opening.

**Comment by serpentiem** [comment]
Verify the integrity of your game files in Steam, re-read [the installation instructions](https://github.com/serpentiem/ddmk#installation) and try again.
