### ISSUE TITLE
4SE: Character switch button leaves me unable to act using a gamepad when playing as the second character

### ISSUE THREAD

**Issue by SSSiyan** [serpentiem/ddmk#260]
Keyboard controls continue to work perfectly. Gamepad camera controls work but that is all (reset camera works but I can't switch back without hitting the keyboard bind). Windows control panel shows only one controller, being "Controller (XBOX 360 For Windows)".

**Comment by serpentiem** [comment]
You need a second gamepad. In fact every character requires a gamepad for it to work. If the gamepad is not present some structs are not initialized and some indices cannot be set. That's why you can't switch. You can easily create token gamepads with vjoy and x360ce.

**Comment by SSSiyan** [comment]
Works beautifully, thank you!
![image](https://user-images.githubusercontent.com/58395132/150705189-71a1219c-5a80-40ad-a59f-3b9d022eaeb1.png)
