### ISSUE TITLE
backup settings?

### ISSUE THREAD

**Issue by nr1995** [serpentiem/ddmk#261]
I've spent about an hour tweaking DDMK to just the way I like.
Is there any config file or something I could easily e-mail to myself
so I don't have to go through it again?
Thanks.

**Comment by SteveCraft1** [comment]
By what i know,it saves the config after you quit the game,if it don't save then try with administrator permission

**Comment by Kazero21** [comment]
Yes, it is a file called _configs_, you can find it in your game directory.
Archive it somewhere safe and use it whenever you want.

**Comment by nr1995** [comment]
> 

You mean it's in a **folder** called “configs”, right?
And the file itself is in that folder, and called something like, “Mary.json”, right?

**Comment by SteveCraft1** [comment]
Yes,it changed from .bin to .json
