### ISSUE TITLE
normal start, enhanced later

### ISSUE THREAD

**Issue by nr1995** [serpentiem/ddmk#262]
How would I configure DDMK so that
I start exactly the way I would in vanilla, with Rebellion + Ebony & Ivory only,
but then naturally expand my arsenal
as I go through the game and get new weapons.
The only difference being I'm able to hold a max of 3 melee/ranged instead of two?

So far I only know how to start the game with three melee/ranged weapons,
holding 6 in total, instead of only 2, like I would have in vanilla Mission 1.

**Comment by SteveCraft1** [comment]
On actor module,you can find the melee and ranged weapons on dante as character,you can choose to have 1-5 simultaneously and since actor module have earned surgical precision,you can changes during gameplay and the changes will work on next loading that happens(including cutscenes)

**Comment by Kazero21** [comment]
Closing

**Comment by nr1995** [comment]
> On actor module,you can find the melee and ranged weapons on dante as character,you can choose to have 1-5 simultaneously and since actor module have earned surgical precision,you can changes during gameplay and the changes will work on next loading that happens(including cutscenes)

So if I'm using the actor module,
the game itself can't change my weapons any more?
Only DDMK can?
Meaning I have to dive into the config every time I pick up a weapon/gun?

**Comment by SteveCraft1** [comment]
Basically you either play the game by normal settings(which thanks for the problematic parts you will be forced to it) or by ddmk settings(actor module enabled),ddmk even have its own exp system so theres 2 exp system(normal and ddmk) on it,so if you can use weapons that you don't even have acquired yet if you select it on actor module

**Comment by nr1995** [comment]
> Basically you either play the game by normal settings(which thanks for the problematic parts you will be forced to it) or by ddmk settings(actor module enabled),ddmk even have its own exp system so theres 2 exp system(normal and ddmk) on it,so if you can use weapons that you don't even have acquired yet if you select it on actor module

I don't quite understand.
So you're saying if I want to start with Rebellion + Ebony & Ivory,
and I want to use the actor module,
I need open the DDMK menu and change my config every time I get a new weapon, right?

**Comment by SteveCraft1** [comment]
Yes,and since weapons take time to get,you won't be interrupted many times non-stop but since ddmk allow you to choose which weapon to equip it means that you can carry less than 5 weapons during gameplay if you don't like all weapons at once

**Comment by nr1995** [comment]
OK, got it.  Thanks.

**Comment by SteveCraft1** [comment]
You're welcome
