### ISSUE TITLE
UI Through Proton

### ISSUE THREAD

**Issue by Gilational** [serpentiem/ddmk#265]
Feel free to close if this would be too much more effort than it's worth.

I got the mod functioning through proton by adding
````
WINEDLLOVERRIDES="dinput8=n,b" %command%
````
into the launch options on steam, and adding the consola font into
````
(Steam directory)/steamapps/compatdata/631510/pfx/drive_c/windows/Fonts
````
to prevent a crash, with it provably working, being able to enable features in the config .json files generated, including enabling actor.
GData.afs was generated as well, though the menu doesn't appear when pressing Ctrl+D. It disabled in-game input and shows the cursor when hideMouseCursor in enabled.
At this point, I'm unsure how to fix this, if possible. May be an issue with ImGui, so nothing anyone can do here. 
If this can be fixed on the mod's end, then great, otherwise, I'd love for some ideas to try out, because I'm all out of them.

**Comment by Soapsuds** [comment]
Hey Gilational,

Thanks for the help in getting this running. In case you didn't see the latest update to proton-experimental added support for the HD collection. No more missing cut scenes! 

After following your steps provided (launch option and linking the font) the UI actually works just fine!
![20220302175809_1](https://user-images.githubusercontent.com/3620789/156475738-c52a859c-5421-4c68-812f-d02e53d332a5.jpg)

Please try switching to proton experimental and test again :)

**Comment by Gilational** [comment]
Closing as this has been fixed on Proton's end. Would be nice to see Linux instructions in the readme since it works great.
