### ISSUE TITLE
Unable to Use Summoned Swords when using Actor Module

### ISSUE THREAD

**Issue by JotaroPowered** [serpentiem/ddmk#267]
I can't use summoned swords as Vergil when enabling the actor module. Is there  a way to fix this or is it a new bug? I didn't have this issue in the past with older builds of this mod.

**Comment by K-MH21** [comment]
Just tested out with a fresh save and with the actor module enabled. It worked for me.

Is this issue present while playing in a new save?

**Comment by K-MH21** [comment]
closing.
