### ISSUE TITLE
DMC3 Quicksilver and modded moves. DT question

### ISSUE THREAD

**Issue by johnhakumen** [serpentiem/ddmk#270]
I cannot select quicksilver on Vergil (as Player 1) or on Player 2 at all unless it is the first style selected, and once I select a different style it doesn't let me come back to quicksilver. 

I believe my issue with modded moves is known already, but the directional inputs only come from Player 1. Player 2 cannot do Air Stinger, new Judgement Cut, etc unless Player 1 is already holding forward or left. 

In the past, as part of the Weapon Switcher it was possible to set a preferred cosmetic devil trigger form, like being able to have rebellion devil trigger regardless of what weapon you were using. Is it still possible to do this?

**Comment by K-MH21** [comment]
> I cannot select quicksilver on Vergil (as Player 1) or on Player 2 at all unless it is the first style selected, and once I select a different style it doesn't let me come back to quicksilver.

I believe that you have Vergil on character 2 (Player 1 second character).
You can't have quicksilver on any other character other than character 1 for player 1.
It is implemented this way to avoid crashing the game.
You can access quicksilver for Vergil by choosing him in character 1.

> I believe my issue with modded moves is known already, but the directional inputs only come from Player 1. Player 2 cannot do Air Stinger, new Judgement Cut, etc unless Player 1 is already holding forward or left.

Interesting
I will inform Serpentiem about it if he start to work on this again.

> In the past, as part of the Weapon Switcher it was possible to set a preferred cosmetic devil trigger form, like being able to have rebellion devil trigger regardless of what weapon you were using. Is it still possible to do this?

Not anymore.
