### ISSUE TITLE
DMC 4 Mods

### ISSUE THREAD

**Issue by Hector021** [serpentiem/ddmk#272]
Is it possible to add the basic Actor parts that you've made for DMC 3 now for DMC 4 Dante?? what I have in mind is:
- weapon switching, changing the order of the weapons and changing the amount  of them to 2 and 3 (possibly 4 with another idea I have)
- making Darkslayer bound to one of the styles pressed twice instead of all of them (like Quicksilver and Doppelganger) I hate it when I wanna double check if I'm on trickster or Swordmaster and instead Yamato comes out
- OR is it possible for Darkslayer to become one of the melee weapons we could switch to (that's where the 4 weapon slot idea comes in)
- adding Quicksilver as a style as well would be nice too but less of a priority

- some input change options for example Drive to be on hold melee instead of round trip
- Vergil Having his trick dodges in his human form
- Vergil doing some DT combos outside of DT (for example DT ground lunar phase has Rising Sun in the end, having that not bound to DT would be amazing) would be nice for Dante as well, he has it bound to Kick 13 input in DT only
- Vergil back to forward Drive and Kick 13 inputs instead of melee + trick input (like his DMC 5 inputs)
- if there is the possibility, multi perfect Judgement Cuts for Vergil just like in 5 (I know its possible to learn a glitch to do it in 4 but it's just not the same)

**Comment by K-MH21** [comment]
Use [this issue](https://github.com/serpentiem/ddmk/issues/233) to write your suggestions.
