### ISSUE TITLE
DMC 3 Style switcher only enable level1 ability for each style

### ISSUE THREAD

**Issue by gallenyao** [serpentiem/ddmk#273]
I enable the setting in actor to use style switcher for Dante, switching is not a problem but I can only use level1 ability for Tricker Swordmaster, Royalguard and Gunsliger. And the icon on the left top corner shows the same, only level1 not level3.

Wonder if anyone saw this or I just need more setup.

**Comment by gallenyao** [comment]
OK, nevermind, I enabled 'Absolute Unit' and the styles are all level 3 now :)

**Comment by SteveCraft1** [comment]
The reason of why its level 1 is because serpentiem have brought back the exp system in a file named "mary_exp".json
