### ISSUE TITLE
Missions 12 and 18

### ISSUE THREAD

**Issue by alexanderROFL** [serpentiem/ddmk#275]
In latest DDMK version for dmc3,mission 12 is totally broken. Unless something is wrong in some setting of mine,but all other missions in game work normally. Style switcher,character switcher,enemy spawner,all works,except on mission 12. I spawn without ability to use guns and if i lock on,animations repeat and i walk sort of in place,basically totally broken mission for some reason.
Edit: Something ultra weird happened in mission 18 now. Many monster graphics are gone and it makes gameplay harder,like chess kings charge AOE or Nevan spinning. But,i found way to get rid of both these issues,for m12 issue i had to use repair option from ddmk and for m12 and m18 i cant have actor enabled,basically must play without style switching. I dont know cause of this problem,i think saving game with dozen diffrent versions of ddmk throughtout the year meesed something up. So,will i have to play missions 12 and 18 the vanilla way or is there some other fix for this problem?

**Comment by Xelvania** [comment]
Mission 12 and 18 Phase 2 will require you to use default game mechanics, unfortunately.  The modder couldn't figure out a way to make the mod work during those parts in the game, so DDMK automatically turns itself off during those sections.  Mission 12 credits is the same way.

**Comment by K-MH21** [comment]
Closing.
