### ISSUE TITLE
Continue button disappears

### ISSUE THREAD

**Issue by Gorillaisdork** [serpentiem/ddmk#277]
In the latest DDMK version, the "CONTINUE" option disappears when starting a new playthrough with the absolute unit disabled, making it harder to enjoy brand new playthrough of DMC3. Is it fixable?

**Comment by SteveCraft1** [comment]
Did you choose yellow or Gold mode?

**Comment by Forgot7en** [comment]
You have to pick Gold mode to have infinite continues, otherwise you have to have Yellow orbs when you die to continue.

**Comment by K-MH21** [comment]
Closing.
