### ISSUE TITLE
Style switcher and weapon switcher bugged on certain missions while actor module is enabled

### ISSUE THREAD

**Issue by Xelvania** [serpentiem/ddmk#278]
Hello Serpentiem,

First off, I want to say how much I appreciate a mod like this.  It's incredible just how much the the dynamic of the gameplay transforms at the simple, but I'm sure complex in the creation of it, ability to change your styles on the fly; however, I did notice a few bugs while finishing up my first playthrough on normal difficulty.

 I do want to preface that every time this bug has occurred, the game acts like you have default game mechanisms again (e.g. the D-pad being a menu accessor again), but with the handicap of not being able to switch styles/weapons or use any of your styles for that matter.  In fact, during the entire duration of the bug, you're simply only able to use Rebellion and Ebony & Ivory with no upgrades.  So, with that being said, here are a few I've experienced with your latest DDMK release.

- Mission 18, the one with the boss gauntlet forcing you to re-kill all the bosses you've defeated so far, has a bug (at least I think it's a bug) where the style and weapon switcher simply don't work in the lobby/hub of the boss' room with the staircases. 
- Mission 19, during phase 2 of the Arkham boss fight alongside your brother Vergil.  I do realize that your styles are completely disabled during this phase, but the weapon switcher bug still applies here, and I'm pretty sure that's not an intended mechanic.
- Mission 20, during the credits where you fight alongside Lady.  I was sooooo looking forward to unlocking the secret ending only to come to the huge disappointment that the bug applies here too.  And as I'm sure you know, it's incredibly, if not impossible, difficult to kill 100 demons with just your Rebellion and Ebony & Ivory with no styles and no upgrades.  I'm sure you can guess how well that fight went.
- Mission 12, same thing during the infinite Devil Trigger section.  You get access back once you enter the room with the Jester fight.

There were one or two others if I recall correctly, but I simply can't remember.  Thankfully, I am doing multiple playthroughs, so I'll be able to grab that information for you in updates to this post.  Hopefully you're still active on here!

**Comment by SteveCraft1** [comment]
![DDMK.jpg](https://user-images.githubusercontent.com/73554591/159213595-f360dcbd-f03c-4fe2-bf15-2c30a2f4d6aa.jpg)

**Comment by SteveCraft1** [comment]
Also you don't have upgrades because actor system and the og system are different so you need to play atleast 2 times to have all things unlocked for both systems(or use a trainer to get infinite red orbs)

**Comment by Xelvania** [comment]
> Also you don't have upgrades because actor system and the og system are different so you need to play atleast 2 times to have all things unlocked for both systems(or use a trainer to get infinite red orbs)

I appreciate the reply!  It's a bummer that that's the case, but duly noted.

**Comment by K-MH21** [comment]
Closing.
