### ISSUE TITLE
The Status Bar disappears too fast when I switch style without being in battle. How to make it appear longer?

### ISSUE THREAD

**Issue by Ashitaka3391** [serpentiem/ddmk#279]
Hi serpentine,

First, many thanks because for your efforts for the DMC Game. Your mods make me feel like I will stick with this game longer because of the new inspirations it brings. For me, the experience it brings is almost perfect.

As mentioned in the title, I want to know whether have any way to make the status bar appear longer. 

Btw, the item purchase and sale window are quite convenient, but it doesn't look as intuitive as it used to be. Can you please bring back the original store item as a toggle option in ddmk?

**Comment by Forgot7en** [comment]
Hold the lock-on button to make the HUD reappear. How do you not know that?
