### ISSUE TITLE
Is there a option to get the old menu for the statues

### ISSUE THREAD

**Issue by Bufekni** [serpentiem/ddmk#282]
![image](https://user-images.githubusercontent.com/36089219/161391160-94f69d41-f674-4e14-a20f-37bc59fc0d74.png)
i wanted to ask if it's possible to get the old menu for upgrading weapons and using the statue instead of the menu on the screenshot

**Comment by 69NEPHILIM69** [comment]
and shop befor mission too please

**Comment by SteveCraft1** [comment]
This custom shop can only be accesed with actor enabled,so of you want the old shop,disable your actor system

**Comment by SteveCraft1** [comment]
Also if any of you reach mission 12
![DDMK.jpg](https://user-images.githubusercontent.com/73554591/161397723-0b265ebe-8ff7-43b1-b15e-ad74e7d7c321.jpg)

**Comment by K-MH21** [comment]
The new menu is used to avoid crashing the game.
