### ISSUE TITLE
Devil May Cry 4:SE crashes upon launch with DDMK installed

### ISSUE THREAD

**Issue by Xelvania** [serpentiem/ddmk#289]
As the title says, I can't boot up the game with this mod.  I have no other mods installed, and I have the latest DDMK version.  Any help would be greatly appreciated!

**Comment by Forgot7en** [comment]
You have to install the required stuff beforehand. Scroll down and follow the instructions for DMC4.
https://github.com/serpentiem/ddmk

**Comment by K-MH21** [comment]
Follow what Forgot7en said.
If still crashes, reopen this issue
