### ISSUE TITLE
DMC HD collection Crashes when i launch Dmc3

### ISSUE THREAD

**Issue by CantCode21** [serpentiem/ddmk#293]
My HD Collection's cracked, btw

[dinput8.txt](https://github.com/serpentiem/ddmk/files/8509705/dinput8.txt)
[Lucia.txt](https://github.com/serpentiem/ddmk/files/8509708/Lucia.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/8509709/Mary.txt)
w

**Comment by Forgot7en** [comment]
If it's cracked, it likely isn't the latest version of the game, which is incompatible with DDMK, I'm sure.

**Comment by K-MH21** [comment]
No support will be provided for cracked versions here.
