### ISSUE TITLE
DMC3: Pressing L3 to switch targets doesn't work sometimes

### ISSUE THREAD

**Issue by Forgot7en** [serpentiem/ddmk#296]
This can be quickly "fixed" by letting go of lockon but it's an annoying issue that really interferes with gameplay

**Comment by K-MH21** [comment]
Use the [Requests](https://github.com/serpentiem/ddmk/issues/233) issue to write your suggestions.

**Comment by Forgot7en** [comment]
What are you talking about, this isn't a request.

**Comment by K-MH21** [comment]
As far as I know, ddmk doesn't have anything to do with lock-on (except for Update Lock-Ons)

Reopen this issue with more explanation if that's a bug related to ddmk.
Otherwise write it on the requests page.
