### ISSUE TITLE
all dante's upgrades disappear when i turn on ddmk style/weapon switcher

### ISSUE THREAD

**Issue by Koheiq** [serpentiem/ddmk#297]
every time i turn on the style switcher & weapon switcher the game just "erase" dante's upgrades, even the costume that i select the game just put dante's default costume, but if i delete the ddmk archives then the game come back to normal

**Comment by Alia-Sun** [comment]
You need to enable the "Absolute Unit" tick box. It's odd, I know. I spent a while looking for the answer, and the meme text at the beginning threw me off in its description box. 

Either way, this enables everything again. Max upgrades, max style level, etc.

**Comment by K-MH21** [comment]
Turning on the actor module will load the upgrades from a save file that is created by DDMK.
You can have all the upgrades maxed out by enabling Absolute model.
Choosing the costume is done by either choosing it in DDMK menu or by enabling the "ignore" and choosing the costume you want in the game menu.

For more info about the actor module, read the [wiki](https://github.com/serpentiem/ddmk/wiki/Features#actor-1).
