### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by MapsAmps** [serpentiem/ddmk#305]
Hi. New to GitHub so apologies for any poor etiquette. This is likely not an issue with the mod but likely a user error. I am having various issues with the mod. Firstly, Mission 12 in DMC3 I have lost my custom settings in DDMK. My custom weapon options have reset (can't switch any weapons), style switcher inputs (DPad) have reset to the usual map, items, etc, options, and all styles have reset their levels back to level 1. Is there a way to force the original actor for Mission 12 since I'm assuming the game changes to another since you're in Devil Trigger mode for this mission. Also, not as consequential but moveset lists in the Style menu does not update to reflect leveling up styles and VERY inconsequential issue but achievements for leveling guns and other options in the customization menu do not seem to unlock. If you could let me know what I need to do since I don't think it's an issue with the mod but I've scanned through the DDMK interface and can't see anything to rectify these problems. If you could let me know what files as well I should drop here I'm happy to do that. Thanks very much.

**Comment by nosh62** [comment]
The game doesn't register what DDMK lets you do, such as having all weapons, moves, and styles leveled up, so it doesn't appear in the in-game's menu. You'd have to play the game without DDMK first and max out everything to be able to see it.

Also, for Mission 12 and others:
![bruh](https://user-images.githubusercontent.com/94879515/176345415-ac61e1fc-d848-4944-aa38-c6cc77c87a41.jpg)

**Comment by MapsAmps** [comment]
Thank you so much.

**Comment by nosh62** [comment]
No problem, mate. Also, you can close this issue now.
