### ISSUE TITLE
DMC3: All AI stuck in static block if available

### ISSUE THREAD

**Issue by GraalOtonami** [serpentiem/ddmk#307]
https://youtu.be/FRT5D78X6-s
See title, video above.
AI without the ability to block attack and move as normal.
All DDMK options are displayed in the video.

**Comment by nosh62** [comment]
My only advice is to try to uninstall and then reinstall DDMK again. But be sure to backup the files, principally the GData.afs one, since I **think** that's the one that holds the data on the progress you've made with style. Other than that, I don't know what to do.

**Comment by Fxhren** [comment]
I found this by accident the other day.

Once you load in into a level, go to your DDMK keybinds and look for the "Reload Level" feature. Set a keybind and press it. The enemies should be moving fine afterwards.

**Comment by K-MH21** [comment]
You have PVP fixes enabled, disable it and it should work for you.

if not, reopen this issue.
