### ISSUE TITLE
2.7 versions of DDMK don't want to install on pirated DMCHCD

### ISSUE THREAD

**Issue by jackie5602** [serpentiem/ddmk#316]
Installed a cracked version of DDMK, and the CODEX update as well, but none of the DDMK 2.7.X versions don't want to install at all. I'm currently on DDMK 2.6 beta 2. I tried installing all of them, but the patch doesn't want to work, none of the files in the dmc3/GData.asf don't disappear, not even diff_pl000_00_3.bin, nor apply_the patch.bat file or the XDelta files. The files were from the dmc3_quick_drive zip file from DDMK 2.7 Nightly 18 Oct 2021 release.

**Comment by nosh62** [comment]
Not something that can help you, but it's something to keep in mind: If any moderator sees this, it's getting terminated.
