### ISSUE TITLE
DMC3SE HD Crashes occasionally on Mission Start

### ISSUE THREAD

**Issue by SquishyGhost** [serpentiem/ddmk#321]
The game seems to work fine with the mod installed after a few missions, but it feels every 4-7 missions in a row it will crash on mission start, I've tried disabling cutscenes as I thought maybe cutscenes loading may occasionally cause issue but that hasn't fixed anything. 

Also for some reason on Mission 5 as Vergil I have the Essence of Intelligence item from the 3 Trials Mission despite it being Mission 5 and not Mission 6

**Comment by microsample** [comment]
Same problem. I think it crashes more often when you buy something (also, is there way to enable old buying menu for items?)
