### ISSUE TITLE
dmc3se crashing when closing welcome pop up

### ISSUE THREAD

**Issue by BobbysonJones** [serpentiem/ddmk#332]
When I close the welcome to ddmk  pop up on dmc3se  it crashes the game 
![Screenshot 2023-04-14 001912](https://user-images.githubusercontent.com/130739502/231972454-492606e0-4751-4e7d-9b7a-0e47cddac097.png)

**Comment by ProjectXsent** [comment]
Try installing the latest Microsoft Visual C++ Redistributable x64 and x86 and see if it works.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by BobbysonJones** [comment]
its fixed ,thanks
