### ISSUE TITLE
How do I set my preferred Devil Trigger?

### ISSUE THREAD

**Issue by PandaDude786** [serpentiem/ddmk#337]
I'd like to use the DMC3 Devil Triggers with the DMC1 outfit, I know it was possible for earlier versions of DDMK but I can't figure it out for this version. Please help.

**Comment by BobbysonJones** [comment]
use dmc3 skin with dmc3 devil trigger then use force file skin for skin without dmc3 devil trigger

**Comment by PandaDude786** [comment]
> use dmc3 skin with dmc3 devil trigger then use force file skin for skin without dmc3 devil trigger

Thank you, I can't believe it was that obvious!
