### ISSUE TITLE
No DDMK on Steam deck?

### ISSUE THREAD

**Issue by yurithroddtaco** [serpentiem/ddmk#343]
Me and my homie were trying everything we can to put DDMK on the steam deck for the past month now and we’re thinking to just buy a laptop that has windows on it, and we’ve been using Linux like all our lives so, PLEASE I DON’T WANT TO RESORT TO BUYING AN ENTIRELY NEW LAPTOP FOR THE MOD. So I’m asking if it’s possible to add DDMK to Linux, I would appreciate any reply and feedback.

**Comment by Malya03** [comment]
#301 

You just need a skill to use a Typical Linux distro, just enter to desktop mode on Steam Deck and do some commands to get it work

**Comment by yurithroddtaco** [comment]
@Malya03 too late already downloaded Windows on the steam deck and now it works plus alot of stuff that Linux couldn't do, thanks for the reply
