### ISSUE TITLE
please help me, ddmk can't be used on laptop?

### ISSUE THREAD

**Issue by TyrntS** [serpentiem/ddmk#344]
when I install ddmk a log appears saying:

22:40:57.245 Session started.
22:40:57.246 Init
22:40:57.248 DirectInput8Create D8B2299C
22:40:57.248 Loads
![IMG_20230617_184042](https://github.com/serpentiem/ddmk/assets/132115109/d4683704-dd68-48bb-a072-6e3aa2b1a3be)

22:40:57.249 dmc3.exe Mary. dll
22:40:57.950 LoadLibraryA failed. Mary dll 7E

Please help me if anyone knows how to fix this :)

I play DMC HDC Steam, not Repack or something like that.

**Comment by TyrntS** [comment]
can anyone help me with this problem? :)

**Comment by ProjectXsent** [comment]
Did you install the latest Visual C++ Redistributables?

**Comment by TyrntS** [comment]
> Apakah Anda menginstal Visual C++ Redistributables terbaru?

I changed to DDMK version 2.7 Mary Nightly June 30 2021 and it worked, I wanted to try the latest version but can't :)

**Comment by TyrntS** [comment]
Thank you for helping me
