### ISSUE TITLE
Investigate special events crashes

### ISSUE THREAD

**Issue by serpentiem** [serpentiem/ddmk#35]
Mission 19
- [ ] Arkham boss battle part 2

Mission 20
- [ ] Credits scene

**Comment by FanSeaJay** [comment]
I noticed that the game normally crashes a few seconds into the cutscene for vergil coming in plays, but if you enable no cutscenes, it gets to the screen explaining what vergil does and that pressing B will call him to your side, but once you dismiss this menu, it showed my camera focused on Vergil like I was playing him but in a very strange area like he was underneath the map. A second into this the game crashed.

**Comment by serpentiem** [comment]
Done.
