### ISSUE TITLE
Research playable Nero Angelo

### ISSUE THREAD

**Issue by serpentiem** [serpentiem/ddmk#47]
If at all feasible, will require a lot of work.

* Replacing or updating actor models, motions and animations.
This requires reverse engineering the model format to some extent. Update internal pointers at the minimum.
* Update some moves.
* Block most moves.
* Update bindings.

Some moves like his teleport may also not be feasible to include.

**Comment by Cheburrat0r** [comment]
I can help you with the model format if you want.

**Comment by serpentiem** [comment]
Sure, thanks!

**Comment by Cheburrat0r** [comment]
Sorry for such a late response.

### File header
The format is little endian, the file header is the first 16 bytes:

size | type | description 
---- | ----- | ------------
1 | unsigned byte | number of meshes
1 | unsigned byte | number bones
1 | unsigned byte | number of textures
1 | unsigned byte | unknown, only seen value of 1
4 | padding | 0xCC bytes, seems to be reserved
8 | unsigned int | bone struct absolute offset

### Mesh headers
Right after the file header come 24 bytes sized headers for each mesh:

size | type | description 
---- | ----- | ------------
2 | unsigned int | number of submeshes
2 | unsigned int | number of vertices in all submeshes 
4 | padding | 0xCC bytes, seems to be reserved
8 | unsigned int | absolute offset to submesh headers, only points to the first subheader, all the rest for this mesh come right after
8 | flags | presumably, last 4 bytes might not be part of it

### Submesh headers
Then come submesh headers of 56 bytes:

size | type | description 
---- | ----- | ------------
2 | unsigned int | number of vertices
2 | unsigned int | texture index, references the first pack of textures (presumably) that goes after the model in an archive like pld, pws, pwd, emd
4 | padding | 0xCC bytes, seems to be reserved
8 | unsigned int | absolute offset to vertex positions
8 | unsigned int | absolute offset to normals
8 | unsigned int | absolute offset to texture coordinates
8 | unsigned int | absolute offset to bone indices
8 | unsigned int | absolute offset to bone weights
8 | unknown | i've only seen these to be 0

### Mesh data
Mesh data is stored contiguously per each mesh, not in combined buffers for positions of all the meshes and so on. First comes positions buffer, then normals buffer, tex coords, bone indices, bone weights, each of these buffers are padded with nulls to align to 16 bytes. Face data is implicit triangle strips with element restart flag being encoded into bone weights.

### Vertex positions
Positions are stored as 3 standard floats per vertex.

### Normals
Exactly the same as positions.

### Texture coordinates
2-byte unsigned int per component, 4 bytes in total per vertex;
U is divided by 4096.0 to get a float;
V is divided by 4096.0 and then subtracted from 1.

### Bone indices
4 unsigned bytes, first byte is unknown, only seen it to be either 0 or 1 in dmc1 and 2 and always 0 in 3, the rest are divided by 4 (idk what else might be encoded there if there's an additional byte and they didn't just use plain bytes for indices  ¯\\\_(ツ)_/¯ ).

### Bone weights
2 bytes per vertex, all 3 weights and the element restart flag are encoded using the same 2 bytes;
first weight is anded with 0x1F and then divided by 31.0;
second weight is right-shifted by 5, anded with 0x1F and divided by 31.0;
third weight is right-shifted by 10, anded with 0x1F and divided by 31.0;
element restart flag is right-shifted by 15 then anded with 1.

### Bone struct header
The very last struct, 16 byte header

size | type | description 
---- | ----- | ------------
4 | unsigned int | hierarchy address, relative offset from the start of the struct
4 | unsigned int | unknown bytes address, relative offset from the start of the struct
4 | unsigned int | bones address, relative offset from the start of the struct
4 | unsigned int | usually counts the same as the number of bones, but 0 on stuff like coats that has physics (not sure if there's anything besides coats in 1)

### Hierarchy
Signed byte per bone, lists parent bone index, -1 for no parent.

### Unknown bytes
A byte per bone.

### Bones
Bones are stored as translation relative to the parent, 4 floats per bone, first 3 are components of the translation vector and the last one is it's length.

DMC 2 format is almost exactly the same, except the reserved 0xCC bytes are now used for something and bones come before hierarchy and the unknown bytes. DMC 3 is a little different and has more stuff.

**Comment by serpentiem** [comment]
Merged into #233.
