### ISSUE TITLE
Allow change devil trigger appearance while DDMK cycle weapon on

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#54]
devil trigger appearance can't change while ddmk weapon changer on, it's bug of feature?

**Comment by serpentiem** [comment]
Neither, but it's intended.

Updating the actor model resets the actor's state. This results in freezes, locks, teleports, etc.

[As seen here.](https://imgur.com/Su5LW5M)

Of course this is unacceptable and that's why you have to set the devil model manually.
