### ISSUE TITLE
Research Boss Vergil

### ISSUE THREAD

**Issue by serpentiem** [serpentiem/ddmk#56]
Including:

- [ ] Motions
- [ ] Animations
- [ ] Stinger Range
- [ ] Royalguard / Parry / Deflect
- [ ] Effects
- [ ] Taunts (Sounds)
- [ ] Defensive Spheres - Should be used instead of Ultimate for Royalguard.

**Comment by liftedcl0ud** [comment]
I am interested to know how this is done lol

**Comment by serpentiem** [comment]
Done.
