### ISSUE TITLE
Playable BoB with Hairdown => Vergil Mission 7 appearance

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#59]
ok.i know vergil and BoB was same person,but could you make little change please?
bob deserve to get vergil costume with hairdown because he's only use yamato (based reference Vergil Mission 7)

Extra.
I Suggest make him use yamato,summoned sword,and Darkslayer only of course
No Force Edge and No Beowulf
Implement his bos moveset (for yamato and darkslayer) 
vergil with yamato only devil arm makes him being true darkslayer similiar as dmc 5 vergil :)

**Comment by serpentiem** [comment]
Dante's hair for Vergil is probably already available as a mod. As for the Bob changes: Declined.
