### ISSUE TITLE
Allow use Gunslinger style in midair Kalina Ann (grapple) and Spiral (sniper)

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#60]
Dante three Guns => Ebony Ivory,Shotgun and artemis can shoot anemy in midair.but Kalina Ann and Spiral can't?it's unfair :(
could you modify some it's move kalinna ann (grapple hook) and spiral (sniper move) for use it on midair

jump three time's + kalinna ann grapple hook(midair) => slice anemy with rebellion (midair) =>  spiral sniper move(midair)

that's sound cool right?

**Comment by serpentiem** [comment]
> that's sound cool right?

It does, but it requires new animations and that's not feasible. Denied.
