### ISSUE TITLE
feel the power of ARG - automatic Royal Guard mode!

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#61]
i've found old reference mods from

https://www.tapatalk.com/groups/infernalworks/feel-the-power-of-arg-automatic-royal-guard-mode-t3433.html

https://www.tapatalk.com/groups/infernalworks/dmc-4-arg-automatic-royal-guard-mod-t3364.html

it's show how to use royalguard style easier without taking a damage and maybe holding it

DMC3 Mod - Automatic Royal Guard & Automatic Royal Release

http://www.youtube.com/watch?v=LghOlWRZPPQ

DMC4 Mod - Automatic Royal Guard & Automatic Royal Release

https://www.youtube.com/watch?v=PuVr5dceFRE

**Comment by serpentiem** [comment]
That doesn't sound great. Will not implement.
