### ISSUE TITLE
Mission 5 Crash

### ISSUE THREAD

**Issue by efagerberg** [serpentiem/ddmk#62]
Hey thanks for making the mod.

I have noticed on mission 5 I consistently crash when having style switcher on.

I get up to the secret mission area, where I automatically succeed due to no enemies spawning. Then I go up the elevator where again no enemies. And finally the game crashes in the next area.

[Mary.txt](https://github.com/serpentiem/ddmk/files/3337220/Mary.txt)

**Comment by serpentiem** [comment]
Should be fixed by now.
