### ISSUE TITLE
Unable to use high level SwordMaster skills

### ISSUE THREAD

**Issue by Beyond-simplechain** [serpentiem/ddmk#63]
1. choose Trickster style, then start the mission or go through the door
2. change to SwordMaster style, i have the highest style level, but i can't use `RB`+`↑`+`B` or `RB`+`↓`+`B`

**Comment by adamkenway007** [comment]
that's weird i don't have problem with high level SwordMaster skills?which floor / stage are you use?
i am play devil may cry hd collection especially dmc 3 almost every days

**Comment by Beyond-eosspark** [comment]
> i am play devil may cry hd collection especially dmc 3 almost every days

any floor / stage following these steps. it only happens in release 2.3

**Comment by PageyJiggyWiggy** [comment]
Same issue with me...strange...

**Comment by GonnaGetcupcake** [comment]
same issue. Style moves depends what style is choosed in mission menu. If I choose Swordmaster then it`s style moves will work, but not Gunslinger.

**Comment by serpentiem** [comment]
Should be fixed by now.
