### ISSUE TITLE
CTD after roughly 40 minutes of play

### ISSUE THREAD

**Issue by Pounding-Quarters** [serpentiem/ddmk#66]
This happens in both missions and bloody palace. I have Style switcher, Weapon switcher, infinite rainstorm, air hike core ability, and crazy combo multiplier at 2 activated. Another more minor glitch I encountered was that the vanilla weapon select screen had bugged to where it would only allow me to select 1 sword and 1 gun at a time. Not sure if these are things that can replicated and fixed but i thought it best to report what I've come across. 
[Mary.txt](https://github.com/serpentiem/ddmk/files/3390224/Mary.txt)

**Comment by serpentiem** [comment]
Should be fixed by now.
