### ISSUE TITLE
Add custom weapon Agni & Rudra to dmc4se

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#71]
D = https://www.tapatalk.com/groups/infernalworks/agni-rudra-v0-8-rodan-the-infinite-one-t2963.html

I'm remember when play dmc4se with agni and rudra with this mod.very cool ,but this mod only allow dante release one of his devil arms  to obtain agni and rudra and it's moveset instead use 4 devil arm he only just had 3 devil arm by removing one of his original devil arm

could you make one more new identifier for devil arm and make dante get 4 devil arm(yamato not count) but probably new 4th devil arm need new devil arm  icon when switching

Edit: some move such running while attacking using agni & rudra (jet stream).because it's wasn't included with this mod.so you may add more improvement

**Comment by serpentiem** [comment]
Denied.
