### ISSUE TITLE
Must Style difficulty

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#72]
This mode is unique in the fact that player cannot damage enemies unless Style Rank is S or higher.
- [ ] Add must style difficulty for hardcore fans

**Comment by SSSiyan** [comment]
"DevilMayCry4SpecialEdition.exe"+22DDE0 writes HP, and you can filter out the player by comparing edi+34 to 20,000 (maximum HP (apparently this isn't an issue on saves that don't have 20k hp?)) . Not sure how this would play with multiple player characters at the same time. DevilMayCry4SpecialEdition.exe+1B0B8A writes 5 (S) to the style meter. In dmc5 my must style mode was made from a damage dealt script that just did cmp [stylemeter],5 jl return

**Comment by serpentiem** [comment]
Available in the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly15).
