### ISSUE TITLE
Style switcher and weapon reset option bugs

### ISSUE THREAD

**Issue by Pounding-Quarters** [serpentiem/ddmk#73]
While using style switcher only level 1 inputs will be available for some styles, I don't know why and can't post my log as I'm now currently away from my computer. Also, the reset equipment debug option only resets devil arms and I can still only select 1 gun and 2 devil arms.

**Comment by adamkenway007** [comment]
identical issue with,you've already reported by yourself
https://github.com/serpentiem/ddmk/issues/66

**Comment by Cheburrat0r** [comment]
I had an issue with only lvl1 sword master moves available for some weapons, which was solved by cycling through weapons.

**Comment by PageyJiggyWiggy** [comment]
I'm having the exact same issue. It's so strange.

**Comment by serpentiem** [comment]
Should be fixed by now.
