### ISSUE TITLE
Add New Skill to DMC4se

### ISSUE THREAD

**Issue by beyondev** [serpentiem/ddmk#74]
reference New Skill Modifier by dlupx

[new skill.CT.zip](https://github.com/serpentiem/ddmk/files/3484628/new.skill.CT.zip)

**Comment by adamkenway007** [comment]
> reference New Skill Modifier by dlupx
> 
> [new skill.CT.zip](https://github.com/serpentiem/ddmk/files/3484628/new.skill.CT.zip)

What a kind of skill is that? Is summoned sword for date included?

**Comment by Beyond-simplechain** [comment]
> > reference New Skill Modifier by dlupx
> > [new skill.CT.zip](https://github.com/serpentiem/ddmk/files/3484628/new.skill.CT.zip)
> 
> What a kind of skill is that? Is summoned sword for dante included?
quick sliver style, judgment cut can cut 3 times like dmc3, and vergil rising sun without DT limit...

**Comment by adamkenway007** [comment]
> 
> 
> > > reference New Skill Modifier by dlupx
> > > [new skill.CT.zip](https://github.com/serpentiem/ddmk/files/3484628/new.skill.CT.zip)
> > 
> > 
> > What a kind of skill is that? Is summoned sword for dante included?
> 
> quick sliver style, judgment cut can cut 3 times like dmc3, and vergil rising sun without DT limit...

Ah,great.but also unfortunately there is no summoned sword for dante

**Comment by serpentiem** [comment]
Denied.
