### ISSUE TITLE
Q:Offline Co-Op Split Screen Support?

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#75]
Will this mod support splitscreen for offline co-op okay online co-op is great but will offline co-op included with split screen?.um i just think if offline co op implemented in this game we don't need watch 2 enemy targetting or any extend zoom out camera to fully watch our player gameplay.split it seperately offline co-op probably good idea

**Comment by adamkenway007** [comment]
> Will this mod support splitscreen for offline co-op okay online co-op is great but will offline co-op included with split screen?.um i just think if offline co op implemented in this game we don't need watch 2 enemy targetting or any extend zoom out camera to fully watch our player gameplay.split it seperately offline co-op probably good idea

https://www.youtube.com/watch?v=9-a7m0eAtC8

This is new Concept on co-op gameplay with seperate health bar,split screen & boss enemies health bar in middle of screen

probably work on dmc 1 - 4

**Comment by serpentiem** [comment]
Split screen is not feasible and the camera tracking all actors is already in #233. Closing.
