### ISSUE TITLE
2.1;2.3;2.5 make DMC3 crash 

### ISSUE THREAD

**Issue by martinn2001** [serpentiem/ddmk#76]
Here's the logs from 2.5

[logs.zip](https://github.com/serpentiem/ddmk/files/3547352/logs.zip)
Edit: forgot to specify that it makes enemies and bosses not spawn usually a room or 2 before it crashes.I also tested it with 2.0 and 0.998 and it does the same.

**Comment by FunkyDarkKnight** [comment]
Can confirm this happens with 2.5, though I only had one proper crash I still get the same symtoms you described regarding enemy spawns and am often forced to restart. A few bugs I had ([logs for the last crash in this list](https://drive.google.com/open?id=1JaZ_LFepiZg7Fb9AIJ4Q4jkQlsABs56n)):

- Mission 4: the cutscene before the Gigapede boss didn't play and it didn't spawn it either, forcing me to Alt+F4.

- Mission 5: When leaving the first room with the blood-goyles and going to the staircase with the multiple Pride enemies, I noticed this time around only one had spawned. As soon as I tried to leave the room with the door at the bottom of the stairs, it crashed.

- Mission 5: After entering the door immediately after defeating Agni & Rudra I was taken immediately to the post-level rank screen without any transitions or music. The rank screen had just the background image with no actual stats. It seemed to have frozen though the program wasn't reported as unresponsive.

**Comment by Dekr0** [comment]
I have experienced crash with DDMK from version 2.1 to version 2.5 (except the very older version of DDMK) . I tested that the game was running without any problem if I did not install DDMK (version 2.1, 2.3 and 2.5). The reason of DDMK causing game crash is not very clear and the crash seems to occur randomly. Here is the log file
[logs.zip](https://github.com/serpentiem/ddmk/files/3986944/logs.zip).

**Comment by serpentiem** [comment]
Should be fixed by now.
