### ISSUE TITLE
DMC1 mission 3 literally unplayable.

### ISSUE THREAD

**Issue by tweash** [serpentiem/ddmk#79]
Every time I get to mission 3 on DMC1, I am greeted with a shot of the castle interior which isnt even a part of mission 3. This potentially happens with other missions as well, as I mission selected mission 4 and the same thing happened. I can also still move around and swing alastor, but am no where on screen. 

https://i.imgur.com/RzRxM94.jpg

Removing the mod and this mission loads fine. I only really use ddmk for DMC3, so if I can get rid of it for DMC1 entirely then thats fine too.

**Comment by fileo919** [comment]
Same problem for me, when I tried to do something else other than attacks, nothing started to work.

**Comment by serpentiem** [comment]
Merged with #184.
