### ISSUE TITLE
Restart App! after enabling multiplayer

### ISSUE THREAD

**Issue by srema99** [serpentiem/ddmk#80]
Arcade mode works, as well as the training mode, but on my system enabling multiplayer makes pic related message pop up. Does not spawn another actor. Can't see this issue anywhere on the internet, even after browsing trainer-related, or DMC related forums for that matter.
![dmc](https://user-images.githubusercontent.com/55931831/65823271-653a6700-e253-11e9-8a75-aef42a2a8a85.png)

EDIT: This also happens when I enable the "Replace Allocation Functions" option in the Systems tab.

**Comment by Cheburrat0r** [comment]
What isn't clear here? Restart the game.

**Comment by srema99** [comment]
The error pops up regardless :(

**Comment by srema99** [comment]
This happens on both my laptop which is running windows 10, and computer which runs win 7.

Well, turns out I have a problem installing. Running downgrade.bat flashes a black command prompt which says Access Denied, xdelta3: file open failed: read: new_DevilMayCry4SpecialEdition.exe : the system could not find the file specified.

Also, The files don't all delete themselves, as they usually do. In neither cases does it work and Restart App! shows on the screen. I can't open the .bin files but I assume it's some sort of copyright protection?

**Comment by srema99** [comment]
I solved it. Turned out to be pretty dumb. I don't know why, maybe it has something to do with read-only properties or w/e.

First, I moved the Devil May Cry 4 Special Edition from it's original location in Program Files (x86),
then, moved it into C:\
Afterwards, start the DDMK trainer and enable Multiplayer. When the "Restart App!" message flashes, turn the game off, start it again, and you can spawn another actor without any problems.
