### ISSUE TITLE
Some Quality of life Features

### ISSUE THREAD

**Issue by Apeboy21** [serpentiem/ddmk#81]
Hello, This mod is amazing and ive had alot of fun with it. But i needed to download one other trainer to fully enjoy co op. I found a trainer online that allows you to freeze the camera in one place. pair this with the camera controls your trainer already has and this makes Bloody Palace 10x more enjoyable because all players are able to move correctly without player 1's camera moving. the only issue with this is the camera does not work for bosses because bosses force the player into a sort of lock on camera mode.  It would be amazing if you could include features like this with the camera and possibly improve on the idea to make it also work with bosses. the co op aspect of this is amazing and with some changes it could be even better! thanks for taking the time if you read this and thanks for the amazing trainer!!

**Comment by adamkenway007** [comment]
> Hello, This mod is amazing and ive had alot of fun with it. But i needed to download one other trainer to fully enjoy co op. I found a trainer online that allows you to freeze the camera in one place. pair this with the camera controls your trainer already has and this makes Bloody Palace 10x more enjoyable because all players are able to move correctly without player 1's camera moving. the only issue with this is the camera does not work for bosses because bosses force the player into a sort of lock on camera mode. It would be amazing if you could include features like this with the camera and possibly improve on the idea to make it also work with bosses. the co op aspect of this is amazing and with some changes it could be even better! thanks for taking the time if you read this and thanks for the amazing trainer!!

umm, freeze/lock camera,how about  seperate screen / split screen 
https://github.com/serpentiem/ddmk/issues/75#issue-481902849
does it sound better for you?

**Comment by Apeboy21** [comment]
> > Hello, This mod is amazing and ive had alot of fun with it. But i needed to download one other trainer to fully enjoy co op. I found a trainer online that allows you to freeze the camera in one place. pair this with the camera controls your trainer already has and this makes Bloody Palace 10x more enjoyable because all players are able to move correctly without player 1's camera moving. the only issue with this is the camera does not work for bosses because bosses force the player into a sort of lock on camera mode. It would be amazing if you could include features like this with the camera and possibly improve on the idea to make it also work with bosses. the co op aspect of this is amazing and with some changes it could be even better! thanks for taking the time if you read this and thanks for the amazing trainer!!
> 
> umm, freeze/lock camera,how about seperate screen / split screen.
> he's already make co-op camera,but co-op for only one screen looked messy.
> [#75 (comment)](https://github.com/serpentiem/ddmk/issues/75#issue-481902849)
> does it sound better for you?

Honestly splitscreen would be amazing but it might not even be possible. and splitscreen would need to work for 4 different players unless its exclusive to 2 player. i feel like my suggestion would be easier to implement but splitscreen would make the campaign about 20x better to play in co op.

**Comment by adamkenway007** [comment]
> > > Hello, This mod is amazing and ive had alot of fun with it. But i needed to download one other trainer to fully enjoy co op. I found a trainer online that allows you to freeze the camera in one place. pair this with the camera controls your trainer already has and this makes Bloody Palace 10x more enjoyable because all players are able to move correctly without player 1's camera moving. the only issue with this is the camera does not work for bosses because bosses force the player into a sort of lock on camera mode. It would be amazing if you could include features like this with the camera and possibly improve on the idea to make it also work with bosses. the co op aspect of this is amazing and with some changes it could be even better! thanks for taking the time if you read this and thanks for the amazing trainer!!
> > 
> > 
> > umm, freeze/lock camera,how about seperate screen / split screen.
> > he's already make co-op camera,but co-op for only one screen looked messy.
> > [#75 (comment)](https://github.com/serpentiem/ddmk/issues/75#issue-481902849)
> > does it sound better for you?
> 
> Honestly splitscreen would be amazing but it might not even be possible. and splitscreen would need to work for 4 different players unless its exclusive to 2 player. i feel like my suggestion would be easier to implement but splitscreen would make the campaign about 20x better to play in co op.

Probably work like this

https://www.youtube.com/watch?v=9-a7m0eAtC8

**Comment by serpentiem** [comment]
Merged into #233.
