### ISSUE TITLE
Playable Bolverk (DMC 2)

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#83]
hello serpentiem

i know this is might be unusual request asking demon boss being playable character
but he is Bolverk,a demon knight with his servant Freki & Geri(which is awesome boss fight characterization nearly similiar like nelo angelo),he has run,control Freki & Geri,teleport,and some attack animation mostly.
how about make him be playable boss character and lend him another character moves like dante/lucia jump & fly + some arius powers (Magical energy manipulation,Barriers)

make devil may cry 2 great again
cheers :-)

**Comment by serpentiem** [comment]
Declined.
