### ISSUE TITLE
Million Stab

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#84]
is possible add million stab move from dmc 3 & 4 to dmc 1 & 2,
Devil May Cry 2 = as far i know only owned by Bolverk (Boss Type)
Devil May Cry 1 = ???

**Comment by serpentiem** [comment]
DMC1 already has it. I have no idea about DMC2, but in theory you'd have to add and update the required resources (models, textures, animations, controllers) at the correct moment. I'm not sure if I'm willing to put that much work into DMC2.

**Comment by adamkenway007** [comment]
> DMC1 already has it. I have no idea about DMC2, but in theory you'd have to add and update the required resources (models, textures, animations, controllers) at the correct moment. I'm not sure if I'm willing to put that much work into DMC2.

Okay,i'm check again and yes DMC1 has million stab inside,and sadl
