### ISSUE TITLE
How to use mouse buttons? DMC3

### ISSUE THREAD

**Issue by Escavalien** [serpentiem/ddmk#85]
I thought mouse was supported but I can't use any mouse buttons? If I try to set them up ingame they're not detected. There is no ini to edit unlike the style switcher mod, and there is no option in the menus. I'm completely confused?

**Comment by adamkenway007** [comment]
> I thought mouse was supported but I can't use any mouse buttons? If I try to set them up ingame they're not detected. There is no ini to edit unlike the style switcher mod, and there is no option in the menus. I'm completely confused?

There aren't camera function on devil may cry HD Collection,
And only yes,mouse only can be use on launcher.exe and not more

**Comment by serpentiem** [comment]
Key bindings are saved in `C:\Program Files (x86)\Steam\userdata\__YOUR_STEAM_ID__\631510\remote\options.sav`. You can open the file with a text editor and change the relevant values.

There's virtually no difference between buttons and keys, so in theory you should be able to simply update the value. With that being said, I have no idea what option is what and which value is which.

If I were you I'd simply change the desired bindings to some keys further away and then use an external app to map them to the mouse buttons.

GlovePIE can do this.

Cheers

**Comment by serpentiem** [comment]
Closing.
