### ISSUE TITLE
FPS uncap?

### ISSUE THREAD

**Issue by nr1995** [serpentiem/ddmk#87]
Hey, sorry to post this here,
but one of my favourite features of Style Switcher was the ability to uncap FPS,
and something I've found I unfortunately can't live without.
I was just wondering,
for DMC3 HD, will this feature ever be added?

**Comment by serpentiem** [comment]
Added in [da763c5](https://github.com/serpentiem/ddmk/commit/da763c5dfcdc290ca5533149cc87fddc6a64e97e). Happy new year!

**Comment by nr1995** [comment]
Wow cool.
Happy new decade!
