### ISSUE TITLE
How to temporarily disable mod to prevent DMC3 Arkham crash?

### ISSUE THREAD

**Issue by FanSeaJay** [serpentiem/ddmk#90]
Title

**Comment by FanSeaJay** [comment]
Also I like how there is an option to skip to that exact part where it crashes when you load up mission 19.

**Comment by fronczek7f** [comment]
same problem

**Comment by serpentiem** [comment]
Just rename `Mary.dll`.

**Comment by serpentiem** [comment]
Obsolete.
