### ISSUE TITLE
Question About Doppelganger

### ISSUE THREAD

**Issue by adamkenway007** [serpentiem/ddmk#92]
umm yeah,devil may cry story start from dmc3 it's has most style than another devil may cry franchise.then i look back from dmc 1,i just familiar with plasma demon https://devilmaycry.fandom.com/wiki/Plasma
which could transform look as dante and copy dante moves.it's possible to insert doppelganger style to dmc 1.i know you also work with quicksilver style on dmc 1 (bangle of time).dmc 1 need style system atleast

**Comment by serpentiem** [comment]
Interesting.

**Comment by serpentiem** [comment]
Merged into #233.
