### ISSUE TITLE
Style meter missing in 2.6 beta and weapon switching greyed out (dmc3)

### ISSUE THREAD

**Issue by Achagit** [serpentiem/ddmk#95]
First, thanks for all the work you've done. The amount of fun to be had with all the new toys you bring to the game is unbelievable.

With the 2.6 beta almost everything works from the start. Don't know what I have to do to be able to weapon switch and I can't seem to find any instructions googling but whatever.

The thing that irks me most is for the style meter to be missing from the ui. It's not always missing but most of the time.

When I do a clean install of the collection and the 2.5 version the style meter always works, but I'm back to not knowing how to make the style switching available.

Thanks again for everything

**Comment by Beyond-simplechain** [comment]
same issue in 2.6_beta2_hotfix, the style meter is missing

**Comment by serpentiem** [comment]
The Style Switcher can be toggled at all times, the Weapon Switcher can only be toggled outside of missions due to some technical restrictions. I'm working on a new design that should 'fix' this as well.

The style meter not showing when it should is a new bug. As a temporary workaround check "Force Single Actor" in the System tab.

**Comment by ymsx8535** [comment]
> 可以随时切换样式切换器，由于某些技术限制，武器切换器只能在任务外切换。我正在研究一种新的设计，该设计也应对此进行“修复”。
> 
> 样式表未显示何时应为新错误。作为临时解决方法，请在“系统”选项卡中检查“强制单个Actor”。

Lock icon in fact representing the blood of the monster can repair it?My English is not good，Please excuse me

**Comment by ymsx8535** [comment]
> 可以随时切换样式切换器，由于某些技术限制，武器切换器只能在任务外切换。我正在研究一种新的设计，该设计也应对此进行“修复”。
> 
> 样式表未显示何时应为新错误。作为临时解决方法，请在“系统”选项卡中检查“强制单个Actor”。

The lock icon actually represents the HP of the monster，Can you fix it？I'm not good at English，Please excuse me

**Comment by serpentiem** [comment]
Should be fixed by now.
