### ISSUE TITLE
Devilarm's  devil.trigger Custom's

### ISSUE THREAD

**Issue by lokilokiad** [serpentiem/ddmk#96]
is it possible to make dmc 3 dante  devil trigger to work with weapon switcher when you change weapons to change devil trigger preset

**Comment by adamkenway007** [comment]
> is it possible to make dmc 3 dante devil trigger to work with weapon switcher when you change weapons to change devil trigger preset

https://github.com/serpentiem/ddmk/issues/96#issue-553854281
Please read this closed thread your question is same as me

**Comment by serpentiem** [comment]
There may be hope now with my current research. Stay tuned.

**Comment by lokilokiad** [comment]
i hope so anyway Good job man your work is amazing
